 // export const RECEIVE_PRODUCT_INFO = "RECEIVE_PRODUCT_INFO";

// export const UPDATE_BASE_PRODUCTS = "UPDATE_BASE_PRODUCTS"
//export const DOMAIN_NAME = "https://access.drs.network";
export const DOMAIN_NAME = "http://localhost:8080";
export const SHOW_LOADING = "SHOW_LOADING";
export const UPDATE_PRODUCT_DATA = "UPDATE_PRODUCT_DATA";
export const UPDATE_CONTROL = "UPDATE_CONTROL";
export const UPDATE_SHOW_PRODUCT = 'UPDATE_SHOW_PRODUCT';
export const UPDATE_BP_OPTIONS = 'UPDATE_BP_OPTIONS';
export const UPDATE_CURRENT_BP = 'UPDATE_CURRENT_BP';

export const REQUEST_PRODUCT_PENDING = 'REQUEST_PRODUCT_PENDING';
export const REQUEST_PRODUCT_SUCCESS = 'REQUEST_PRODUCT_SUCCESS';
export const REQUEST_PRODUCT_FAILED = 'REQUEST_PRODUCT_FAILED';

export const FETCH_SIMPLE_PRODUCT_LIST_PENDING = 'FETCH_SIMPLE_PRODUCT_LIST_PENDING';
export const FETCH_SIMPLE_PRODUCT_LIST_SUCCESS = 'FETCH_SIMPLE_PRODUCT_LIST_SUCCESS';
export const FETCH_SIMPLE_PRODUCT_LIST_FAILED = 'FETCH_SIMPLE_PRODUCT_LIST_FAILED';

export const REQUEST_ADD_PRODUCT_PENDING = 'REQUEST_ADD_PRODUCT_PENDING';
export const REQUEST_ADD_PRODUCT_SUCCESS = 'REQUEST_ADD_PRODUCT_SUCCESS';
export const REQUEST_ADD_PRODUCT_FAILED = 'REQUEST_ADD_PRODUCT_FAILED';
export const REQUEST_ADD_SKU_PENDING = 'REQUEST_ADD_SKU_PENDING';
export const REQUEST_ADD_SKU_SUCCESS = 'REQUEST_ADD_SKU_SUCCESS';
export const REQUEST_ADD_SKU_FAILED = 'REQUEST_ADD_SKU_FAILED';
export const REQUEST_UPDATE_PRODUCT_PENDING = 'UPDATE_PRODUCT_PENDING';
export const REQUEST_UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const REQUEST_UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';
export const REQUEST_EXACT_BP_PENDING = 'REQUEST_EXACT_BP_PENDING';
export const REQUEST_EXACT_BP_SUCCESS = 'REQUEST_EXACT_BP_SUCCESS';
export const REQUEST_EXACT_BP_FAILED = 'REQUEST_EXACT_BP_FAILED';
export const REQUEST_NEXT_BPS_PENDING = 'REQUEST_NEXT_BPS_PENDING';
export const REQUEST_NEXT_BPS_SUCCESS = 'REQUEST_NEXT_BPS_SUCCESS';
export const REQUEST_NEXT_BPS_FAILED = 'REQUEST_NEXT_BPS_FAILED';
export const REQUEST_REMOVE_BP_PENDING = 'REQUEST_REMOVE_BP_PENDING';
export const REQUEST_REMOVE_BP_SUCCESS = 'REQUEST_REMOVE_BP_SUCCESS';
export const REQUEST_REMOVE_BP_FAILED = 'REQUEST_REMOVE_BP_FAILED';
export const UPDATE_MULTITHEME = 'UPDATE_MULTITHEME';
export const UPDATE_INPUTS = 'UPDATE_INPUTS';
export const CHECK_VALID = 'CHECK_VALID';

export const ON_BRANDNAME_CH_CHANGE = 'ON_BRANDNAME_CH_CHANGE';
export const ON_BRANDNAME_EN_CHANGE = 'ON_BRANDNAME_EN_CHANGE';
export const ON_PRODUCTNAME_CH_CHANGE = 'ON_PRODUCTNAME_CH_CHANGE';
export const ON_PRODUCTNAME_EN_CHANGE = 'ON_PRODUCTNAME_EN_CHANGE';
export const ON_MANUFACTURER_CH_CHANGE = 'ON_MANUFACTURER_CH_CHANGE';
export const ON_MANUFACTURER_EN_CHANGE = 'ON_MANUFACTURER_EN_CHANGE';

export const UPDATE_CHECK_VALID = 'UPDATE_CHECK_VALID';

//P2M
export const REQUEST_P2M_APPLICATIONS_SUCCESS = 'REQUEST_P2M_APPLICATIONS_SUCCESS';
export const REQUEST_P2M_APPLICATIONS_FAILED = 'REQUEST_P2M_APPLICATIONS_FAILED';
export const REQUEST_P2M_APPLICATIONS_PENDING = 'REQUEST_P2M_APPLICATIONS_PENDING';

export const UPDATE_CURRENT_APPLICATION = 'UPDATE_CURRENT_APPLICATION';
export const UPDATE_SHOW_BREADCRUMBS = 'UPDATE_SHOW_BREADCRUMBS';
export const UPDATE_CURRENT_SUB_APPLICATION = 'UPDATE_CURRENT_SUB_APPLICATION';

export const INIT_CREATE_P2M_APPLICATION = 'INIT_CREATE_P2M_APPLICATION';

export const LOAD_P2M_MARKETPLACE_INFO_PENDING = 'LOAD_P2M_MARKETPLACE_INFO_PENDING';
export const LOAD_P2M_MARKETPLACE_INFO_SUCCESS = 'LOAD_P2M_MARKETPLACE_INFO_SUCCESS';
export const LOAD_P2M_MARKETPLACE_INFO_FAILED = 'LOAD_P2M_MARKETPLACE_INFO_FAILED';

export const LOAD_P2M_REGIONAL_PENDING = 'LOAD_P2M_REGIONAL_PENDING';
export const LOAD_P2M_REGIONAL_SUCCESS = 'LOAD_P2M_REGIONAL_SUCCESS';
export const LOAD_P2M_REGIONAL_FAILED = 'LOAD_P2M_REGIONAL_FAILED';

export const LOAD_P2M_SHIPPING_PENDING = 'LOAD_P2M_SHIPPING_PENDING';
export const LOAD_P2M_SHIPPING_SUCCESS = 'LOAD_P2M_SHIPPING_SUCCESS';
export const LOAD_P2M_SHIPPING_FAILED = 'LOAD_P2M_SHIPPING_FAILED';

export const LOAD_P2M_INSURANCE_PENDING = 'LOAD_P2M_INSURANCE_PENDING';
export const LOAD_P2M_INSURANCE_SUCCESS = 'LOAD_P2M_INSURANCE_SUCCESS';
export const LOAD_P2M_INSURANCE_FAILED = 'LOAD_P2M_INSURANCE_FAILED';

export const LOAD_P2M_PRODUCT_INFO_PENDING = 'LOAD_P2M_PRODUCT_INFO_PENDING';
export const LOAD_P2M_PRODUCT_INFO_SUCCESS = 'LOAD_P2M_PRODUCT_INFO_SUCCESS';
export const LOAD_P2M_PRODUCT_INFO_FAILED = 'LOAD_P2M_PRODUCT_INFO_FAILED';

export const SAVE_P2M_MARKETPLACE_INFO_PENDING = 'SAVE_P2M_MARKETPLACE_INFO_PENDING';
export const SAVE_P2M_MARKETPLACE_INFO_SUCCESS = 'SAVE_P2M_MARKETPLACE_INFO_SUCCESS';
export const SAVE_P2M_MARKETPLACE_INFO_FAILED = 'SAVE_P2M_MARKETPLACE_INFO_FAILED';

export const SAVE_P2M_REGIONAL_PENDING = 'SAVE_P2M_REGIONAL_PENDING';
export const SAVE_P2M_REGIONAL_SUCCESS = 'SAVE_P2M_REGIONAL_SUCCESS';
export const SAVE_P2M_REGIONAL_FAILED = 'SAVE_P2M_REGIONAL_FAILED';

export const SAVE_P2M_INSURANCE_PENDING = 'SAVE_P2M_INSURANCE_PENDING';
export const SAVE_P2M_INSURANCE_SUCCESS = 'SAVE_P2M_INSURANCE_SUCCESS';
export const SAVE_P2M_INSURANCE_FAILED = 'SAVE_P2M_INSURANCE_FAILED';

export const SAVE_P2M_PRODUCT_INFO_SUCCESS = 'SAVE_P2M_PRODUCT_INFO_SUCCESS';
export const SAVE_P2M_PRODUCT_INFO_PENDING = 'SAVE_P2M_PRODUCT_INFO_PENDING';
export const SAVE_P2M_PRODUCT_INFO_FAILED = 'SAVE_P2M_PRODUCT_INFO_FAILED';

export const SAVE_P2M_SHIPPING_PENDING = 'SAVE_P2M_SHIPPING_PENDING';
export const SAVE_P2M_SHIPPING_SUCCESS = 'SAVE_P2M_SHIPPING_SUCCESS';
export const SAVE_P2M_SHIPPING_FAILED = 'SAVE_P2M_SHIPPING_FAILED';

export const SELECT_P2M_COUNTRY = "SELECT_P2M_COUNTRY"
export const SELECT_P2M_APPLICATION_TYPE = 'SELECT_P2M_APPLICATION_TYPE'
export const SELECT_P2M_APPLICATION_PRODUCT = 'SELECT_P2M_APPLICATION_PRODUCT';
export const SELECT_P2M_APPLICATION_SKU = 'SELECT_P2M_APPLICATION_SKU';
export const SELECT_P2M_APPLICATION_PLATFORM = 'SELECT_P2M_APPLICATION_PLATFORM';
// export const SELECT_P2M_SUBAP_TYPE = "SELECT_P2M_SUBAP_TYPE";
export const SELECT_P2M_APPLICATION_NAME = 'SELECT_P2M_APPLICATION_NAME';
export const SELECT_REMOVAL_SKU = 'SELECT_REMOVAL_SKU';

export const CHANGE_P2M_APPLICATION_PLATFORM_OPTIONS = 'CHANGE_P2M_APPLICATION_PLATFORM_OPTIONS';

export const GET_EXACT_PRODUCT_FOR_AP_PENDING = 'GET_EXACT_PRODUCT_FOR_AP_PENDING'
export const GET_EXACT_PRODUCT_FOR_AP_SUCCESS = 'GET_EXACT_PRODUCT_FOR_AP_SUCCESS'
export const GET_EXACT_PRODUCT_FOR_AP_FAILED = 'GET_EXACT_PRODUCT_FOR_AP_FAILED'

export const CREATE_P2M_APPLICATION_PENDING = 'CREATE_P2M_APPLICATION_PENDING'
export const CREATE_P2M_APPLICATION_SUCCESS = 'CREATE_P2M_APPLICATION_SUCCESS'
export const CREATE_P2M_APPLICATION_FAILED = 'CREATE_P2M_APPLICATION_FAILED'

export const CHANGE_P2M_APPLICATION_PENDING = 'CHANGE_P2M_APPLICATION_PENDING'
export const CHANGE_P2M_APPLICATION_SUCCESS = 'CHANGE_P2M_APPLICATION_SUCCESS'
export const CHANGE_P2M_APPLICATION_FAILED = 'CHANGE_P2M_APPLICATION_FAILED'

export const UPDATE_P2M_APPLICATION_PENDING = 'UPDATE_P2M_APPLICATION_PENDING'
export const UPDATE_P2M_APPLICATION_SUCCESS = 'UPDATE_P2M_APPLICATION_SUCCESS'
export const UPDATE_P2M_APPLICATION_FAILED = 'UPDATE_P2M_APPLICATION_FAILED'

// export const REDIRECT_APPLICATION = 'REDIRECT_APPLICATION'
export const UPDATE_REDIRECT_APPLICATION = 'UPDATE_REDIRECT_APPLICATION'
export const UPDATE_APPLICATION = 'UPDATE_APPLICATION'

export const FETCH_PRODUCT_CATEGORY_SUCCESS = 'FETCH_PRODUCT_CATEGORY_SUCCESS'
export const FETCH_PRODUCT_CATEGORY_PENDING = 'FETCH_PRODUCT_CATEGORY_PENDING'
export const FETCH_PRODUCT_CATEGORY_FAILED = 'FETCH_PRODUCT_CATEGORY_FAILED'

export const UPDATE_PRODUCT_CATEGORY = 'UPDATE_PRODUCT_CATEGORY'
export const UPDATE_CURRENT_PRODUCT_CATEGORY = 'UPDATE_CURRENT_PRODUCT_CATEGORY'

export const SUBMIT_APPLICATION_PENDING = 'SUBMIT_APPLICATION_PENDING';
export const SUBMIT_APPLICATION_SUCCESS = 'SUBMIT_APPLICATION_SUCCESS';
export const SUBMIT_APPLICATION_FAILED = 'SUBMIT_APPLICATION_FAILED';

export const APPLY_TO_REMOVE_PENDING = 'APPLY_TO_REMOVE_PENDING';
export const APPLY_TO_REMOVE_SUCCESS = 'APPLY_TO_REMOVE_SUCCESS';
export const APPLY_TO_REMOVE_FAILED = 'APPLY_TO_REMOVE_FAILED';

export const REJECT_TO_REMOVE_PENDING = 'REJECT_TO_REMOVE_PENDING';
export const REJECT_TO_REMOVE_SUCCESS = 'REJECT_TO_REMOVE_SUCCESS';
export const REJECT_TO_REMOVE_FAILED = 'REJECT_TO_REMOVE_FAILED';

export const APPROVE_TO_REMOVE_PENDING = 'APPROVE_TO_REMOVE_PENDING';
export const APPROVE_TO_REMOVE_SUCCESS = 'APPROVE_TO_REMOVE_SUCCESS';
export const APPROVE_TO_REMOVE_FAILED = 'APPROVE_TO_REMOVE_FAILED';

export const GET_EXACT_APPLICATION_PENDING = 'GET_EXACT_APPLICATION_PENDING';
export const GET_EXACT_APPLICATION_SUCCESS = 'GET_EXACT_APPLICATION_SUCCESS';
export const GET_EXACT_APPLICATION_FAILED = 'GET_EXACT_APPLICATION_FAILED';
export const CHANGE_SKUITEM_SHOW = "CHANGE_SKUITEM_SHOW";

// export const UPDATE_READONLY = 'UPDATE_READONLY';

export const FETCH_USER_PENDING = "FETCH_USER_PENDING";
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const FETCH_SUPPLIERS_PENDING = "FETCH_SUPPLIERS_PENDING";
export const FETCH_SUPPLIERS_SUCCESS = 'FETCH_SUPPLIERS_SUCCESS';
export const FETCH_SUPPLIERS_FAILED = 'FETCH_SUPPLIERS_FAILED';

export const  GET_EXACT_SUBAP_PENDING = "GET_EXACT_SUBAP_PENDING";
export const GET_EXACT_SUBAP_SUCCESS = "GET_EXACT_SUBAP_SUCCESS";
export const GET_EXACT_SUBAP_FAILED = "GET_EXACT_SUBAP_FAILED";

export const APPROVE_APPLICATION_PENDING = "APPROVE_APPLICATION_PENDING";
export const APPROVE_APPLICATION_SUCCESS = "APPROVE_APPLICATION_SUCCESS";
export const APPROVE_APPLICATION_FAILED = "APPROVE_APPLICATION_FAILED";

export const REJECT_APPLICATION_PENDING = "REJECT_APPLICATION_PENDING";
export const REJECT_APPLICATION_SUCCESS = "REJECT_APPLICATION_SUCCESS";
export const REJECT_APPLICATION_FAILED = "REJECT_APPLICATION_FAILED";

export const UPDATE_MODAL_STATE = "UPDATE_MODAL_STATE";
export const HANDLE_SMOOTH_SCROLL = 'HANDLE_SMOOTH_SCROLL';

export const FETCH_P2MAP_COMMENT_PENDING = 'FETCH_P2MAP_COMMENT_PENDING';
export const FETCH_P2MAP_COMMENT_SUCCESS = 'FETCH_P2MAP_COMMENT_SUCCESS';
export const FETCH_P2MAP_COMMENT_FAILED = 'FETCH_P2MAP_COMMENT_FAILED';

export const FETCH_TOTAL_PRODUCT_NUMBER_PENDING = 'FETCH_TOTAL_PRODUCT_NUMBER_PENDING';
export const FETCH_TOTAL_PRODUCT_NUMBER_SUCCESS= 'FETCH_TOTAL_PRODUCT_NUMBER_SUCCESS';
export const FETCH_TOTAL_PRODUCT_NUMBER_FAILED= 'FETCH_TOTAL_PRODUCT_NUMBER_FAILED';

export const FETCH_TOTAL_SKU_NUMBER_PENDING= 'FETCH_TOTAL_SKU_NUMBER_PENDING';
export const FETCH_TOTAL_SKU_NUMBER_SUCCESS= 'FETCH_TOTAL_SKU_NUMBER_SUCCESS';
export const FETCH_TOTAL_SKU_NUMBER_FAILED= 'FETCH_TOTAL_SKU_NUMBER_FAILED';

export const FETCH_TOTAL_APPLIED_SKU_NUMBER_PENDING= 'FETCH_TOTAL_APPLIED_SKU_NUMBER_PENDING';
export const FETCH_TOTAL_APPLIED_SKU_NUMBER_SUCCESS= 'FETCH_TOTAL_APPLIED_SKU_NUMBER_SUCCESS';
export const FETCH_TOTAL_APPLIED_SKU_NUMBER_FAILED= 'FETCH_TOTAL_APPLIED_SKU_NUMBER_FAILED';

export const FETCH_TOTAL_ONSALE_SKU_NUMBER_PENDING= 'FETCH_TOTAL_ONSALE_SKU_NUMBER_PENDING';
export const FETCH_TOTAL_ONSALE_SKU_NUMBER_SUCCESS= 'FETCH_TOTAL_ONSALE_SKU_NUMBER_SUCCESS';
export const FETCH_TOTAL_ONSALE_SKU_NUMBER_FAILED= 'FETCH_TOTAL_ONSALE_SKU_NUMBER_FAILED';

export const REFILL_APPLICATION_PENDING= 'REFILL_APPLICATION_PENDING';
export const REFILL_APPLICATION_SUCCESS= 'REFILL_APPLICATION_SUCCESS';
export const REFILL_APPLICATION_FAILED= 'REFILL_APPLICATION_FAILED';

export const DELETE_AP_PENDING = 'DELETE_AP_PENDING';
export const DELETE_AP_SUCCESS = 'DELETE_AP_SUCCESS';
export const DELETE_AP_FAILED = 'DELETEE_AP_FAILED';

export const SHOW_CREATE_P2M_MODAL = 'SHOW_CREATE_P2M_MODAL';
export const HIDE_CREATE_P2M_MODAL= 'HIDE_CREATE_P2M_MODAL';
export const CHANGE_MP_SKU_VARIATIONNAME_SHOW = 'CHANGE_MP_SKU_VARIATIONNAME_SHOW';
export const CHANGE_MP_SKU_IMG_SHOW = 'CHANGE_MP_SKU_IMG_SHOW'
export const CHANGE_MP_SKU_MAINTITLE_SHOW = 'CHANGE_MP_SKU_MAINTITLE_SHOW'
export const CHANGE_MP_SKU_DES_SHOW = 'CHANGE_MP_SKU_DES_SHOW'
export const CHANGE_MP_SKU_FEATURE_SHOW = 'CHANGE_MP_SKU_FEATURE_SHOW'
export const CHANGE_MP_SKU_KEYWORD_SHOW = 'CHANGE_MP_SKU_KEYWORD_SHOW'

export const UPDATE_MP = 'UPDATE_MP'
export const UPDATE_INS = 'UPDATE_INS'
export const UPDATE_SH = 'UPDATE_SH'
export const UPDATE_RE = 'UPDATE_RE'
export const UPDATE_PAI = 'UPDATE_PAI'
export const UPDATE_SKU_OPTIONS = 'UPDATE_SKU_OPTIONS'

export const CHANGE_AP = 'CHANGE_AP'

export const GET_FILTERLIST_PENDING = 'GET_FILTERLIST_PENDING'
export const GET_FILTERLIST_SUCCESS = 'GET_FILTERLIST_SUCCESS'
export const GET_FILTERLIST_FAILED = 'GET_FILTERLIST_FAILED'

export const CHANGE_FILTER_TARGET = 'CHANGE_FILTER_TARGET'
export const CHANGE_FILTERED_APS = 'CHANGE_FILTERED_APS'