//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 11:40:51 PM CST 
//


package com.kindminds.drs.mws.xml;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AreBatteriesIncluded" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="BatteriesRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="BatteryDescription" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="BatteryLife" type="{}BatteryLifeDimension" minOccurs="0"/&gt;
 *         &lt;element name="ClosureType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="IncludesRechargableBattery" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="LithiumBatteryEnergyContent" type="{}PositiveDimension" minOccurs="0"/&gt;
 *         &lt;element name="LithiumBatteryPackaging" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}String"&gt;
 *               &lt;enumeration value="batteries_contained_in_equipment"/&gt;
 *               &lt;enumeration value="batteries_only"/&gt;
 *               &lt;enumeration value="batteries_packed_with_equipment"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LoadCapacity" type="{}WeightDimension" minOccurs="0"/&gt;
 *         &lt;element name="Material" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfLithiumIonCells" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfLithiumMetalCells" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="OemEquivalentPartNumber" type="{}FortyStringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Viscosity" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="VolumeCapacity" type="{}VolumeDimension" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "areBatteriesIncluded",
    "batteriesRequired",
    "batteryDescription",
    "batteryLife",
    "closureType",
    "includesRechargableBattery",
    "lithiumBatteryEnergyContent",
    "lithiumBatteryPackaging",
    "loadCapacity",
    "material",
    "numberOfLithiumIonCells",
    "numberOfLithiumMetalCells",
    "oemEquivalentPartNumber",
    "viscosity",
    "volumeCapacity"
})
@XmlRootElement(name = "Accessories")
public class Accessories {

    @XmlElement(name = "AreBatteriesIncluded")
    protected Boolean areBatteriesIncluded;
    @XmlElement(name = "BatteriesRequired")
    protected Boolean batteriesRequired;
    @XmlElement(name = "BatteryDescription")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String batteryDescription;
    @XmlElement(name = "BatteryLife")
    protected BatteryLifeDimension batteryLife;
    @XmlElement(name = "ClosureType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String closureType;
    @XmlElement(name = "IncludesRechargableBattery")
    protected Boolean includesRechargableBattery;
    @XmlElement(name = "LithiumBatteryEnergyContent")
    protected BigDecimal lithiumBatteryEnergyContent;
    @XmlElement(name = "LithiumBatteryPackaging")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lithiumBatteryPackaging;
    @XmlElement(name = "LoadCapacity")
    protected WeightDimension loadCapacity;
    @XmlElement(name = "Material")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String material;
    @XmlElement(name = "NumberOfLithiumIonCells")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfLithiumIonCells;
    @XmlElement(name = "NumberOfLithiumMetalCells")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfLithiumMetalCells;
    @XmlElement(name = "OemEquivalentPartNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String oemEquivalentPartNumber;
    @XmlElement(name = "Viscosity")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String viscosity;
    @XmlElement(name = "VolumeCapacity")
    protected VolumeDimension volumeCapacity;

    /**
     * Gets the value of the areBatteriesIncluded property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAreBatteriesIncluded() {
        return areBatteriesIncluded;
    }

    /**
     * Sets the value of the areBatteriesIncluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAreBatteriesIncluded(Boolean value) {
        this.areBatteriesIncluded = value;
    }

    /**
     * Gets the value of the batteriesRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBatteriesRequired() {
        return batteriesRequired;
    }

    /**
     * Sets the value of the batteriesRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBatteriesRequired(Boolean value) {
        this.batteriesRequired = value;
    }

    /**
     * Gets the value of the batteryDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatteryDescription() {
        return batteryDescription;
    }

    /**
     * Sets the value of the batteryDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatteryDescription(String value) {
        this.batteryDescription = value;
    }

    /**
     * Gets the value of the batteryLife property.
     * 
     * @return
     *     possible object is
     *     {@link BatteryLifeDimension }
     *     
     */
    public BatteryLifeDimension getBatteryLife() {
        return batteryLife;
    }

    /**
     * Sets the value of the batteryLife property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatteryLifeDimension }
     *     
     */
    public void setBatteryLife(BatteryLifeDimension value) {
        this.batteryLife = value;
    }

    /**
     * Gets the value of the closureType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClosureType() {
        return closureType;
    }

    /**
     * Sets the value of the closureType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClosureType(String value) {
        this.closureType = value;
    }

    /**
     * Gets the value of the includesRechargableBattery property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludesRechargableBattery() {
        return includesRechargableBattery;
    }

    /**
     * Sets the value of the includesRechargableBattery property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludesRechargableBattery(Boolean value) {
        this.includesRechargableBattery = value;
    }

    /**
     * Gets the value of the lithiumBatteryEnergyContent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLithiumBatteryEnergyContent() {
        return lithiumBatteryEnergyContent;
    }

    /**
     * Sets the value of the lithiumBatteryEnergyContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLithiumBatteryEnergyContent(BigDecimal value) {
        this.lithiumBatteryEnergyContent = value;
    }

    /**
     * Gets the value of the lithiumBatteryPackaging property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLithiumBatteryPackaging() {
        return lithiumBatteryPackaging;
    }

    /**
     * Sets the value of the lithiumBatteryPackaging property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLithiumBatteryPackaging(String value) {
        this.lithiumBatteryPackaging = value;
    }

    /**
     * Gets the value of the loadCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link WeightDimension }
     *     
     */
    public WeightDimension getLoadCapacity() {
        return loadCapacity;
    }

    /**
     * Sets the value of the loadCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightDimension }
     *     
     */
    public void setLoadCapacity(WeightDimension value) {
        this.loadCapacity = value;
    }

    /**
     * Gets the value of the material property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterial() {
        return material;
    }

    /**
     * Sets the value of the material property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterial(String value) {
        this.material = value;
    }

    /**
     * Gets the value of the numberOfLithiumIonCells property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfLithiumIonCells() {
        return numberOfLithiumIonCells;
    }

    /**
     * Sets the value of the numberOfLithiumIonCells property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfLithiumIonCells(BigInteger value) {
        this.numberOfLithiumIonCells = value;
    }

    /**
     * Gets the value of the numberOfLithiumMetalCells property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfLithiumMetalCells() {
        return numberOfLithiumMetalCells;
    }

    /**
     * Sets the value of the numberOfLithiumMetalCells property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfLithiumMetalCells(BigInteger value) {
        this.numberOfLithiumMetalCells = value;
    }

    /**
     * Gets the value of the oemEquivalentPartNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOemEquivalentPartNumber() {
        return oemEquivalentPartNumber;
    }

    /**
     * Sets the value of the oemEquivalentPartNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOemEquivalentPartNumber(String value) {
        this.oemEquivalentPartNumber = value;
    }

    /**
     * Gets the value of the viscosity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViscosity() {
        return viscosity;
    }

    /**
     * Sets the value of the viscosity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViscosity(String value) {
        this.viscosity = value;
    }

    /**
     * Gets the value of the volumeCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeDimension }
     *     
     */
    public VolumeDimension getVolumeCapacity() {
        return volumeCapacity;
    }

    /**
     * Sets the value of the volumeCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeDimension }
     *     
     */
    public void setVolumeCapacity(VolumeDimension value) {
        this.volumeCapacity = value;
    }

}
