//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 11:40:51 PM CST 
//


package com.kindminds.drs.mws.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Capacity" type="{}VolumeDimension" minOccurs="0"/&gt;
 *         &lt;element name="CareInstructions" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Codabar" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="ColorMap" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="ContainsLiquidContents" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="true"/&gt;
 *               &lt;enumeration value="false"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FulfillmentCenterSpecialStorage" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="HazmatException" type="{}TwoThousandString" minOccurs="0"/&gt;
 *         &lt;element name="IsDishwasherSafe" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="true"/&gt;
 *               &lt;enumeration value="false"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IsExclusiveProduct" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="true"/&gt;
 *               &lt;enumeration value="false"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ItemShape" type="{}HundredString" minOccurs="0"/&gt;
 *         &lt;element name="LanguageValue" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="german"/&gt;
 *               &lt;enumeration value="aragonese"/&gt;
 *               &lt;enumeration value="sidamo"/&gt;
 *               &lt;enumeration value="altaic_languages"/&gt;
 *               &lt;enumeration value="luo"/&gt;
 *               &lt;enumeration value="papuan_languages"/&gt;
 *               &lt;enumeration value="khotanese"/&gt;
 *               &lt;enumeration value="kinyarwanda"/&gt;
 *               &lt;enumeration value="elamite"/&gt;
 *               &lt;enumeration value="hausa"/&gt;
 *               &lt;enumeration value="dutch"/&gt;
 *               &lt;enumeration value="old_french"/&gt;
 *               &lt;enumeration value="classical_syriac"/&gt;
 *               &lt;enumeration value="flemish"/&gt;
 *               &lt;enumeration value="kokborok"/&gt;
 *               &lt;enumeration value="songhai_languages"/&gt;
 *               &lt;enumeration value="nepali"/&gt;
 *               &lt;enumeration value="makasar"/&gt;
 *               &lt;enumeration value="ancient_greek"/&gt;
 *               &lt;enumeration value="sardinian"/&gt;
 *               &lt;enumeration value="niger_kordofanian_languages"/&gt;
 *               &lt;enumeration value="chinook_jargon"/&gt;
 *               &lt;enumeration value="cayuga"/&gt;
 *               &lt;enumeration value="castillian"/&gt;
 *               &lt;enumeration value="old_irish"/&gt;
 *               &lt;enumeration value="persian"/&gt;
 *               &lt;enumeration value="aleut"/&gt;
 *               &lt;enumeration value="jula"/&gt;
 *               &lt;enumeration value="siksika"/&gt;
 *               &lt;enumeration value="pohnpeian"/&gt;
 *               &lt;enumeration value="nzima"/&gt;
 *               &lt;enumeration value="chiricahua"/&gt;
 *               &lt;enumeration value="siswati"/&gt;
 *               &lt;enumeration value="sumerian"/&gt;
 *               &lt;enumeration value="north_american_indian_languages"/&gt;
 *               &lt;enumeration value="pidgin_english"/&gt;
 *               &lt;enumeration value="minangkabau"/&gt;
 *               &lt;enumeration value="dravidian_languages"/&gt;
 *               &lt;enumeration value="gorontalo"/&gt;
 *               &lt;enumeration value="slovak"/&gt;
 *               &lt;enumeration value="hebrew"/&gt;
 *               &lt;enumeration value="sasak"/&gt;
 *               &lt;enumeration value="northern_sami"/&gt;
 *               &lt;enumeration value="ekajuk"/&gt;
 *               &lt;enumeration value="chechen"/&gt;
 *               &lt;enumeration value="selkup"/&gt;
 *               &lt;enumeration value="kirundi"/&gt;
 *               &lt;enumeration value="braj"/&gt;
 *               &lt;enumeration value="celtic_languages"/&gt;
 *               &lt;enumeration value="bengali"/&gt;
 *               &lt;enumeration value="azerbaijani"/&gt;
 *               &lt;enumeration value="upper_sorbian"/&gt;
 *               &lt;enumeration value="sorbian_languages"/&gt;
 *               &lt;enumeration value="scots"/&gt;
 *               &lt;enumeration value="afrikaans"/&gt;
 *               &lt;enumeration value="sami"/&gt;
 *               &lt;enumeration value="umbundu"/&gt;
 *               &lt;enumeration value="australian_languages"/&gt;
 *               &lt;enumeration value="assyrian"/&gt;
 *               &lt;enumeration value="navaho"/&gt;
 *               &lt;enumeration value="khoisan_languages"/&gt;
 *               &lt;enumeration value="chamic_languages"/&gt;
 *               &lt;enumeration value="lithuanian"/&gt;
 *               &lt;enumeration value="bambara"/&gt;
 *               &lt;enumeration value="vietnamese"/&gt;
 *               &lt;enumeration value="bini"/&gt;
 *               &lt;enumeration value="maltese"/&gt;
 *               &lt;enumeration value="slave_athapascan"/&gt;
 *               &lt;enumeration value="mandar"/&gt;
 *               &lt;enumeration value="susu"/&gt;
 *               &lt;enumeration value="lule_sami"/&gt;
 *               &lt;enumeration value="apache_languages"/&gt;
 *               &lt;enumeration value="artificial_languages"/&gt;
 *               &lt;enumeration value="algonquian_languages"/&gt;
 *               &lt;enumeration value="bikol"/&gt;
 *               &lt;enumeration value="sanskrit"/&gt;
 *               &lt;enumeration value="tuvinian"/&gt;
 *               &lt;enumeration value="bihari"/&gt;
 *               &lt;enumeration value="wakashan_languages"/&gt;
 *               &lt;enumeration value="gaelic_scots"/&gt;
 *               &lt;enumeration value="tatar"/&gt;
 *               &lt;enumeration value="luba_katanga"/&gt;
 *               &lt;enumeration value="kumyk"/&gt;
 *               &lt;enumeration value="welsh"/&gt;
 *               &lt;enumeration value="chinese"/&gt;
 *               &lt;enumeration value="japanese"/&gt;
 *               &lt;enumeration value="beja"/&gt;
 *               &lt;enumeration value="norwegian_bokmal"/&gt;
 *               &lt;enumeration value="tzeltal"/&gt;
 *               &lt;enumeration value="tiv"/&gt;
 *               &lt;enumeration value="angika"/&gt;
 *               &lt;enumeration value="scots_gaelic"/&gt;
 *               &lt;enumeration value="garo"/&gt;
 *               &lt;enumeration value="otomian_languages"/&gt;
 *               &lt;enumeration value="north_ndebele"/&gt;
 *               &lt;enumeration value="dhivehi"/&gt;
 *               &lt;enumeration value="aramaic"/&gt;
 *               &lt;enumeration value="rarotongan"/&gt;
 *               &lt;enumeration value="setswana"/&gt;
 *               &lt;enumeration value="kanuri"/&gt;
 *               &lt;enumeration value="mon_khmer_languages"/&gt;
 *               &lt;enumeration value="haryanvi"/&gt;
 *               &lt;enumeration value="zaza"/&gt;
 *               &lt;enumeration value="lushai"/&gt;
 *               &lt;enumeration value="ijo_languages"/&gt;
 *               &lt;enumeration value="zande_languages"/&gt;
 *               &lt;enumeration value="indic"/&gt;
 *               &lt;enumeration value="sandawe"/&gt;
 *               &lt;enumeration value="fon"/&gt;
 *               &lt;enumeration value="ndonga"/&gt;
 *               &lt;enumeration value="xhosa"/&gt;
 *               &lt;enumeration value="judeo_persian"/&gt;
 *               &lt;enumeration value="taiwanese_chinese"/&gt;
 *               &lt;enumeration value="karen_languages"/&gt;
 *               &lt;enumeration value="bribri"/&gt;
 *               &lt;enumeration value="marathi"/&gt;
 *               &lt;enumeration value="sinhalese"/&gt;
 *               &lt;enumeration value="inuktitut"/&gt;
 *               &lt;enumeration value="tigre"/&gt;
 *               &lt;enumeration value="slovene"/&gt;
 *               &lt;enumeration value="choctaw"/&gt;
 *               &lt;enumeration value="ga"/&gt;
 *               &lt;enumeration value="northern_frisian"/&gt;
 *               &lt;enumeration value="yugoslavian"/&gt;
 *               &lt;enumeration value="mirandese"/&gt;
 *               &lt;enumeration value="nauru"/&gt;
 *               &lt;enumeration value="spanish"/&gt;
 *               &lt;enumeration value="somali"/&gt;
 *               &lt;enumeration value="dakota"/&gt;
 *               &lt;enumeration value="syriac"/&gt;
 *               &lt;enumeration value="french_canadian"/&gt;
 *               &lt;enumeration value="lower_sorbian"/&gt;
 *               &lt;enumeration value="punjabi"/&gt;
 *               &lt;enumeration value="inari_sami"/&gt;
 *               &lt;enumeration value="gwichin"/&gt;
 *               &lt;enumeration value="inuktitun"/&gt;
 *               &lt;enumeration value="erzya"/&gt;
 *               &lt;enumeration value="cushitic_languages"/&gt;
 *               &lt;enumeration value="kikuyu"/&gt;
 *               &lt;enumeration value="quechua"/&gt;
 *               &lt;enumeration value="nilo_saharan_languages"/&gt;
 *               &lt;enumeration value="sino_tibetan"/&gt;
 *               &lt;enumeration value="kalaallisut"/&gt;
 *               &lt;enumeration value="asturian"/&gt;
 *               &lt;enumeration value="romance"/&gt;
 *               &lt;enumeration value="pampanga"/&gt;
 *               &lt;enumeration value="fanti"/&gt;
 *               &lt;enumeration value="bislama"/&gt;
 *               &lt;enumeration value="bahasa"/&gt;
 *               &lt;enumeration value="aromanian"/&gt;
 *               &lt;enumeration value="madurese"/&gt;
 *               &lt;enumeration value="pedi"/&gt;
 *               &lt;enumeration value="norwegian"/&gt;
 *               &lt;enumeration value="herero"/&gt;
 *               &lt;enumeration value="yoruba"/&gt;
 *               &lt;enumeration value="ottoman_turkish"/&gt;
 *               &lt;enumeration value="latin"/&gt;
 *               &lt;enumeration value="middle_english"/&gt;
 *               &lt;enumeration value="gilbertese"/&gt;
 *               &lt;enumeration value="french"/&gt;
 *               &lt;enumeration value="georgian"/&gt;
 *               &lt;enumeration value="portuguese_brazilian"/&gt;
 *               &lt;enumeration value="old_provencal"/&gt;
 *               &lt;enumeration value="tamashek"/&gt;
 *               &lt;enumeration value="serbian"/&gt;
 *               &lt;enumeration value="marshallese"/&gt;
 *               &lt;enumeration value="kru_languages"/&gt;
 *               &lt;enumeration value="kashubian"/&gt;
 *               &lt;enumeration value="chhattisgarhi"/&gt;
 *               &lt;enumeration value="kosraean"/&gt;
 *               &lt;enumeration value="hindi"/&gt;
 *               &lt;enumeration value="esperanto"/&gt;
 *               &lt;enumeration value="kazakh"/&gt;
 *               &lt;enumeration value="gayo"/&gt;
 *               &lt;enumeration value="afghan_pashtu"/&gt;
 *               &lt;enumeration value="rapanui"/&gt;
 *               &lt;enumeration value="ewondo"/&gt;
 *               &lt;enumeration value="egyptian"/&gt;
 *               &lt;enumeration value="gibberish"/&gt;
 *               &lt;enumeration value="khmer"/&gt;
 *               &lt;enumeration value="banda_languages"/&gt;
 *               &lt;enumeration value="hungarian"/&gt;
 *               &lt;enumeration value="moksha"/&gt;
 *               &lt;enumeration value="creek"/&gt;
 *               &lt;enumeration value="luiseno"/&gt;
 *               &lt;enumeration value="karelian"/&gt;
 *               &lt;enumeration value="greenlandic"/&gt;
 *               &lt;enumeration value="samoan"/&gt;
 *               &lt;enumeration value="romansch"/&gt;
 *               &lt;enumeration value="berber"/&gt;
 *               &lt;enumeration value="cree"/&gt;
 *               &lt;enumeration value="gothic"/&gt;
 *               &lt;enumeration value="nyamwezi"/&gt;
 *               &lt;enumeration value="magahi"/&gt;
 *               &lt;enumeration value="shona"/&gt;
 *               &lt;enumeration value="lunda"/&gt;
 *               &lt;enumeration value="uzbek"/&gt;
 *               &lt;enumeration value="arawak"/&gt;
 *               &lt;enumeration value="friulian"/&gt;
 *               &lt;enumeration value="fiji"/&gt;
 *               &lt;enumeration value="turkmen"/&gt;
 *               &lt;enumeration value="old_persian"/&gt;
 *               &lt;enumeration value="shan"/&gt;
 *               &lt;enumeration value="latvian"/&gt;
 *               &lt;enumeration value="old_english"/&gt;
 *               &lt;enumeration value="tsonga"/&gt;
 *               &lt;enumeration value="faroese"/&gt;
 *               &lt;enumeration value="votic"/&gt;
 *               &lt;enumeration value="ossetian"/&gt;
 *               &lt;enumeration value="iroquoian_languages"/&gt;
 *               &lt;enumeration value="yupik_languages"/&gt;
 *               &lt;enumeration value="dargwa"/&gt;
 *               &lt;enumeration value="papiamento"/&gt;
 *               &lt;enumeration value="phoenician"/&gt;
 *               &lt;enumeration value="mandingo"/&gt;
 *               &lt;enumeration value="delaware"/&gt;
 *               &lt;enumeration value="low_german"/&gt;
 *               &lt;enumeration value="lao"/&gt;
 *               &lt;enumeration value="mongolian"/&gt;
 *               &lt;enumeration value="telugu"/&gt;
 *               &lt;enumeration value="abkhazian"/&gt;
 *               &lt;enumeration value="chagatai"/&gt;
 *               &lt;enumeration value="achinese"/&gt;
 *               &lt;enumeration value="udmurt"/&gt;
 *               &lt;enumeration value="siouan_languages"/&gt;
 *               &lt;enumeration value="malagasy"/&gt;
 *               &lt;enumeration value="pashto"/&gt;
 *               &lt;enumeration value="thai"/&gt;
 *               &lt;enumeration value="efik"/&gt;
 *               &lt;enumeration value="luxembourgish"/&gt;
 *               &lt;enumeration value="bodo"/&gt;
 *               &lt;enumeration value="gbaya"/&gt;
 *               &lt;enumeration value="kara_kalpak"/&gt;
 *               &lt;enumeration value="eastern_frisian"/&gt;
 *               &lt;enumeration value="nepal_bhasa"/&gt;
 *               &lt;enumeration value="malay"/&gt;
 *               &lt;enumeration value="germanic_languages"/&gt;
 *               &lt;enumeration value="tsimshian"/&gt;
 *               &lt;enumeration value="hokkien"/&gt;
 *               &lt;enumeration value="adangme"/&gt;
 *               &lt;enumeration value="dogri"/&gt;
 *               &lt;enumeration value="lamba"/&gt;
 *               &lt;enumeration value="sogdian"/&gt;
 *               &lt;enumeration value="scandanavian_languages"/&gt;
 *               &lt;enumeration value="middle_french"/&gt;
 *               &lt;enumeration value="afrihili"/&gt;
 *               &lt;enumeration value="estonian"/&gt;
 *               &lt;enumeration value="sichuan_yi"/&gt;
 *               &lt;enumeration value="portuguese_creole"/&gt;
 *               &lt;enumeration value="igbo"/&gt;
 *               &lt;enumeration value="awadhi"/&gt;
 *               &lt;enumeration value="ukranian"/&gt;
 *               &lt;enumeration value="interlingua"/&gt;
 *               &lt;enumeration value="gahrwali"/&gt;
 *               &lt;enumeration value="mizo"/&gt;
 *               &lt;enumeration value="interlingue"/&gt;
 *               &lt;enumeration value="cantonese_chinese"/&gt;
 *               &lt;enumeration value="albanian"/&gt;
 *               &lt;enumeration value="italian"/&gt;
 *               &lt;enumeration value="adygei"/&gt;
 *               &lt;enumeration value="korean"/&gt;
 *               &lt;enumeration value="khasi"/&gt;
 *               &lt;enumeration value="tupi_languages"/&gt;
 *               &lt;enumeration value="lojban"/&gt;
 *               &lt;enumeration value="ewe"/&gt;
 *               &lt;enumeration value="gullah"/&gt;
 *               &lt;enumeration value="simplified_chinese"/&gt;
 *               &lt;enumeration value="prakrit_languages"/&gt;
 *               &lt;enumeration value="akan"/&gt;
 *               &lt;enumeration value="kashmiri"/&gt;
 *               &lt;enumeration value="bosnian"/&gt;
 *               &lt;enumeration value="klingon"/&gt;
 *               &lt;enumeration value="tai_languages"/&gt;
 *               &lt;enumeration value="dzongkha"/&gt;
 *               &lt;enumeration value="belgian"/&gt;
 *               &lt;enumeration value="manipuri"/&gt;
 *               &lt;enumeration value="lapp"/&gt;
 *               &lt;enumeration value="guarani"/&gt;
 *               &lt;enumeration value="valencian"/&gt;
 *               &lt;enumeration value="sangho"/&gt;
 *               &lt;enumeration value="yapese"/&gt;
 *               &lt;enumeration value="zuni"/&gt;
 *               &lt;enumeration value="kuanyama"/&gt;
 *               &lt;enumeration value="bhutani"/&gt;
 *               &lt;enumeration value="english"/&gt;
 *               &lt;enumeration value="sign_language"/&gt;
 *               &lt;enumeration value="czech"/&gt;
 *               &lt;enumeration value="hawaiian"/&gt;
 *               &lt;enumeration value="south_ndebele"/&gt;
 *               &lt;enumeration value="palauan"/&gt;
 *               &lt;enumeration value="geez"/&gt;
 *               &lt;enumeration value="austronesian"/&gt;
 *               &lt;enumeration value="tahitian"/&gt;
 *               &lt;enumeration value="ladino"/&gt;
 *               &lt;enumeration value="dinka"/&gt;
 *               &lt;enumeration value="komi"/&gt;
 *               &lt;enumeration value="bhojpuri"/&gt;
 *               &lt;enumeration value="old_norse"/&gt;
 *               &lt;enumeration value="walloon"/&gt;
 *               &lt;enumeration value="central_american_indian_languages"/&gt;
 *               &lt;enumeration value="javanese"/&gt;
 *               &lt;enumeration value="belarusian"/&gt;
 *               &lt;enumeration value="tibetan"/&gt;
 *               &lt;enumeration value="zulu"/&gt;
 *               &lt;enumeration value="cherokee"/&gt;
 *               &lt;enumeration value="swahili"/&gt;
 *               &lt;enumeration value="iranian_languages"/&gt;
 *               &lt;enumeration value="himachali_languages"/&gt;
 *               &lt;enumeration value="oriya"/&gt;
 *               &lt;enumeration value="galibi_carib"/&gt;
 *               &lt;enumeration value="middle_irish"/&gt;
 *               &lt;enumeration value="icelandic"/&gt;
 *               &lt;enumeration value="classical_newari"/&gt;
 *               &lt;enumeration value="baltic_languages"/&gt;
 *               &lt;enumeration value="kamba"/&gt;
 *               &lt;enumeration value="twi"/&gt;
 *               &lt;enumeration value="afro_asiatic_languages"/&gt;
 *               &lt;enumeration value="gujarati"/&gt;
 *               &lt;enumeration value="nyankole"/&gt;
 *               &lt;enumeration value="baluchi"/&gt;
 *               &lt;enumeration value="uighur"/&gt;
 *               &lt;enumeration value="occitan"/&gt;
 *               &lt;enumeration value="pangasinan"/&gt;
 *               &lt;enumeration value="semitic_languages"/&gt;
 *               &lt;enumeration value="sundanese"/&gt;
 *               &lt;enumeration value="nko"/&gt;
 *               &lt;enumeration value="tamil"/&gt;
 *               &lt;enumeration value="gondi"/&gt;
 *               &lt;enumeration value="judeo_arabic"/&gt;
 *               &lt;enumeration value="arapaho"/&gt;
 *               &lt;enumeration value="micmac"/&gt;
 *               &lt;enumeration value="mohawk"/&gt;
 *               &lt;enumeration value="yao"/&gt;
 *               &lt;enumeration value="sranan_tongo"/&gt;
 *               &lt;enumeration value="farsi"/&gt;
 *               &lt;enumeration value="bliss"/&gt;
 *               &lt;enumeration value="gallegan"/&gt;
 *               &lt;enumeration value="buryat"/&gt;
 *               &lt;enumeration value="manx"/&gt;
 *               &lt;enumeration value="tagalog"/&gt;
 *               &lt;enumeration value="assamese"/&gt;
 *               &lt;enumeration value="kurukh"/&gt;
 *               &lt;enumeration value="swiss_german"/&gt;
 *               &lt;enumeration value="scandinavian_languages"/&gt;
 *               &lt;enumeration value="old_high_german"/&gt;
 *               &lt;enumeration value="mandarin_chinese"/&gt;
 *               &lt;enumeration value="polish"/&gt;
 *               &lt;enumeration value="kabyle"/&gt;
 *               &lt;enumeration value="galician"/&gt;
 *               &lt;enumeration value="mayan"/&gt;
 *               &lt;enumeration value="ukrainian"/&gt;
 *               &lt;enumeration value="bamileke_languages"/&gt;
 *               &lt;enumeration value="zenaga"/&gt;
 *               &lt;enumeration value="kalmyk"/&gt;
 *               &lt;enumeration value="ojibwa"/&gt;
 *               &lt;enumeration value="tereno"/&gt;
 *               &lt;enumeration value="karachay_balkar"/&gt;
 *               &lt;enumeration value="yakut"/&gt;
 *               &lt;enumeration value="filipino"/&gt;
 *               &lt;enumeration value="rajasthani"/&gt;
 *               &lt;enumeration value="aymara"/&gt;
 *               &lt;enumeration value="kawi"/&gt;
 *               &lt;enumeration value="manchu"/&gt;
 *               &lt;enumeration value="traditional_chinese"/&gt;
 *               &lt;enumeration value="romanian"/&gt;
 *               &lt;enumeration value="limburgan"/&gt;
 *               &lt;enumeration value="southern_sami"/&gt;
 *               &lt;enumeration value="burmese"/&gt;
 *               &lt;enumeration value="armenian"/&gt;
 *               &lt;enumeration value="breton"/&gt;
 *               &lt;enumeration value="hmong"/&gt;
 *               &lt;enumeration value="indo_european"/&gt;
 *               &lt;enumeration value="middle_high_german"/&gt;
 *               &lt;enumeration value="ido"/&gt;
 *               &lt;enumeration value="sindhi"/&gt;
 *               &lt;enumeration value="bulgarian"/&gt;
 *               &lt;enumeration value="neapolitan"/&gt;
 *               &lt;enumeration value="kachin"/&gt;
 *               &lt;enumeration value="dogrib"/&gt;
 *               &lt;enumeration value="moldavian"/&gt;
 *               &lt;enumeration value="mongo"/&gt;
 *               &lt;enumeration value="blin"/&gt;
 *               &lt;enumeration value="ugaritic"/&gt;
 *               &lt;enumeration value="hiri_motu"/&gt;
 *               &lt;enumeration value="soninke"/&gt;
 *               &lt;enumeration value="tok_pisin"/&gt;
 *               &lt;enumeration value="osage"/&gt;
 *               &lt;enumeration value="romany"/&gt;
 *               &lt;enumeration value="byelorussian"/&gt;
 *               &lt;enumeration value="maharati"/&gt;
 *               &lt;enumeration value="duala"/&gt;
 *               &lt;enumeration value="american_sign_language"/&gt;
 *               &lt;enumeration value="marwari"/&gt;
 *               &lt;enumeration value="sicilian"/&gt;
 *               &lt;enumeration value="akkadian"/&gt;
 *               &lt;enumeration value="timne"/&gt;
 *               &lt;enumeration value="tumbuka"/&gt;
 *               &lt;enumeration value="greek"/&gt;
 *               &lt;enumeration value="basa"/&gt;
 *               &lt;enumeration value="kabardian"/&gt;
 *               &lt;enumeration value="southern_sotho"/&gt;
 *               &lt;enumeration value="haida"/&gt;
 *               &lt;enumeration value="basque"/&gt;
 *               &lt;enumeration value="chipewyan"/&gt;
 *               &lt;enumeration value="serbo-croatian"/&gt;
 *               &lt;enumeration value="finnish"/&gt;
 *               &lt;enumeration value="venda"/&gt;
 *               &lt;enumeration value="avaric"/&gt;
 *               &lt;enumeration value="croatian"/&gt;
 *               &lt;enumeration value="hittite"/&gt;
 *               &lt;enumeration value="southern_altai"/&gt;
 *               &lt;enumeration value="salishan_languages"/&gt;
 *               &lt;enumeration value="mari"/&gt;
 *               &lt;enumeration value="mende"/&gt;
 *               &lt;enumeration value="nahuatl"/&gt;
 *               &lt;enumeration value="haitian"/&gt;
 *               &lt;enumeration value="maori"/&gt;
 *               &lt;enumeration value="sukuma"/&gt;
 *               &lt;enumeration value="corsican"/&gt;
 *               &lt;enumeration value="ingush"/&gt;
 *               &lt;enumeration value="nyoro"/&gt;
 *               &lt;enumeration value="washo"/&gt;
 *               &lt;enumeration value="none"/&gt;
 *               &lt;enumeration value="romansh"/&gt;
 *               &lt;enumeration value="inupiaq"/&gt;
 *               &lt;enumeration value="mossi"/&gt;
 *               &lt;enumeration value="buginese"/&gt;
 *               &lt;enumeration value="pali"/&gt;
 *               &lt;enumeration value="inupiak"/&gt;
 *               &lt;enumeration value="nias"/&gt;
 *               &lt;enumeration value="vai"/&gt;
 *               &lt;enumeration value="kumaoni"/&gt;
 *               &lt;enumeration value="russian"/&gt;
 *               &lt;enumeration value="chichewa"/&gt;
 *               &lt;enumeration value="lahnda"/&gt;
 *               &lt;enumeration value="nogai"/&gt;
 *               &lt;enumeration value="french_creole"/&gt;
 *               &lt;enumeration value="iban"/&gt;
 *               &lt;enumeration value="manobo_languages"/&gt;
 *               &lt;enumeration value="nubian_languages"/&gt;
 *               &lt;enumeration value="pig_latin"/&gt;
 *               &lt;enumeration value="cornish"/&gt;
 *               &lt;enumeration value="walamo"/&gt;
 *               &lt;enumeration value="afar"/&gt;
 *               &lt;enumeration value="yiddish"/&gt;
 *               &lt;enumeration value="bantu"/&gt;
 *               &lt;enumeration value="avestan"/&gt;
 *               &lt;enumeration value="grebo"/&gt;
 *               &lt;enumeration value="irish"/&gt;
 *               &lt;enumeration value="kannada"/&gt;
 *               &lt;enumeration value="niuean"/&gt;
 *               &lt;enumeration value="acoli"/&gt;
 *               &lt;enumeration value="unknown"/&gt;
 *               &lt;enumeration value="norwegian_nynorsk"/&gt;
 *               &lt;enumeration value="arabic"/&gt;
 *               &lt;enumeration value="dari"/&gt;
 *               &lt;enumeration value="multilingual"/&gt;
 *               &lt;enumeration value="indonesian"/&gt;
 *               &lt;enumeration value="danish"/&gt;
 *               &lt;enumeration value="philippine_languages"/&gt;
 *               &lt;enumeration value="chamorro"/&gt;
 *               &lt;enumeration value="tetum"/&gt;
 *               &lt;enumeration value="tonga_nyasa"/&gt;
 *               &lt;enumeration value="lingala"/&gt;
 *               &lt;enumeration value="zhuang"/&gt;
 *               &lt;enumeration value="batak"/&gt;
 *               &lt;enumeration value="zapotec"/&gt;
 *               &lt;enumeration value="caddo"/&gt;
 *               &lt;enumeration value="catalan"/&gt;
 *               &lt;enumeration value="cebuano"/&gt;
 *               &lt;enumeration value="skolt_sami"/&gt;
 *               &lt;enumeration value="kirghiz"/&gt;
 *               &lt;enumeration value="munda_languages"/&gt;
 *               &lt;enumeration value="old_slavonic"/&gt;
 *               &lt;enumeration value="ganda"/&gt;
 *               &lt;enumeration value="serer"/&gt;
 *               &lt;enumeration value="lezghian"/&gt;
 *               &lt;enumeration value="tlingit"/&gt;
 *               &lt;enumeration value="hupa"/&gt;
 *               &lt;enumeration value="unqualified"/&gt;
 *               &lt;enumeration value="provencal"/&gt;
 *               &lt;enumeration value="chuukese"/&gt;
 *               &lt;enumeration value="cambodian"/&gt;
 *               &lt;enumeration value="caucasian_languages"/&gt;
 *               &lt;enumeration value="slovakian"/&gt;
 *               &lt;enumeration value="waray"/&gt;
 *               &lt;enumeration value="fang"/&gt;
 *               &lt;enumeration value="swedish"/&gt;
 *               &lt;enumeration value="maithili"/&gt;
 *               &lt;enumeration value="alsatian"/&gt;
 *               &lt;enumeration value="kutenai"/&gt;
 *               &lt;enumeration value="wolof"/&gt;
 *               &lt;enumeration value="bashkir"/&gt;
 *               &lt;enumeration value="luba_lulua"/&gt;
 *               &lt;enumeration value="fulah"/&gt;
 *               &lt;enumeration value="kpelle"/&gt;
 *               &lt;enumeration value="slavic"/&gt;
 *               &lt;enumeration value="kurdish"/&gt;
 *               &lt;enumeration value="turkish"/&gt;
 *               &lt;enumeration value="cheyenne"/&gt;
 *               &lt;enumeration value="macedonian"/&gt;
 *               &lt;enumeration value="tokelau"/&gt;
 *               &lt;enumeration value="tigrinya"/&gt;
 *               &lt;enumeration value="santali"/&gt;
 *               &lt;enumeration value="crimean_tatar"/&gt;
 *               &lt;enumeration value="south_american_indian"/&gt;
 *               &lt;enumeration value="lozi"/&gt;
 *               &lt;enumeration value="ainu"/&gt;
 *               &lt;enumeration value="sesotho"/&gt;
 *               &lt;enumeration value="mapudungun"/&gt;
 *               &lt;enumeration value="athapascan_languages"/&gt;
 *               &lt;enumeration value="coptic"/&gt;
 *               &lt;enumeration value="pahlavi"/&gt;
 *               &lt;enumeration value="malayalam"/&gt;
 *               &lt;enumeration value="chuvash"/&gt;
 *               &lt;enumeration value="urdu"/&gt;
 *               &lt;enumeration value="land_dayak_languages"/&gt;
 *               &lt;enumeration value="portuguese"/&gt;
 *               &lt;enumeration value="latin_spanish"/&gt;
 *               &lt;enumeration value="bemba"/&gt;
 *               &lt;enumeration value="oromo"/&gt;
 *               &lt;enumeration value="frisian"/&gt;
 *               &lt;enumeration value="amharic"/&gt;
 *               &lt;enumeration value="kongo"/&gt;
 *               &lt;enumeration value="chibcha"/&gt;
 *               &lt;enumeration value="masai"/&gt;
 *               &lt;enumeration value="iloko"/&gt;
 *               &lt;enumeration value="hiligaynon"/&gt;
 *               &lt;enumeration value="finno_ugrian"/&gt;
 *               &lt;enumeration value="tuvalu"/&gt;
 *               &lt;enumeration value="tajik"/&gt;
 *               &lt;enumeration value="volapuk"/&gt;
 *               &lt;enumeration value="balinese"/&gt;
 *               &lt;enumeration value="kimbundu"/&gt;
 *               &lt;enumeration value="creole"/&gt;
 *               &lt;enumeration value="middle_dutch"/&gt;
 *               &lt;enumeration value="tonga"/&gt;
 *               &lt;enumeration value="tulu"/&gt;
 *               &lt;enumeration value="samaritan"/&gt;
 *               &lt;enumeration value="konkani"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LegalComplianceCertificationRegulatoryOrganizationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ModelNumber" type="{}FortyStringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="ModelName" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfBoxes" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="ArtistBiography" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="SpecificationMet" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="WarmthRating" type="{}TemperatureRatingDimension" minOccurs="0"/&gt;
 *         &lt;element name="VariationData" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="VariationTheme"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="size_name"/&gt;
 *                         &lt;enumeration value="sizecolor"/&gt;
 *                         &lt;enumeration value="itempackagequantity"/&gt;
 *                         &lt;enumeration value="colorsize"/&gt;
 *                         &lt;enumeration value="size"/&gt;
 *                         &lt;enumeration value="color_name"/&gt;
 *                         &lt;enumeration value="sizename-colorname"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Parentage"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="parent"/&gt;
 *                         &lt;enumeration value="child"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="WarrantyDescription" type="{}StringNotNull" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "capacity",
    "careInstructions",
    "codabar",
    "colorMap",
    "containsLiquidContents",
    "fulfillmentCenterSpecialStorage",
    "hazmatException",
    "isDishwasherSafe",
    "isExclusiveProduct",
    "itemShape",
    "languageValue",
    "legalComplianceCertificationRegulatoryOrganizationName",
    "modelNumber",
    "modelName",
    "numberOfBoxes",
    "artistBiography",
    "specificationMet",
    "warmthRating",
    "variationData",
    "warrantyDescription"
})
@XmlRootElement(name = "DutchOvens")
public class DutchOvens {

    @XmlElement(name = "Capacity")
    protected VolumeDimension capacity;
    @XmlElement(name = "CareInstructions")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String careInstructions;
    @XmlElement(name = "Codabar")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String codabar;
    @XmlElement(name = "ColorMap")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String colorMap;
    @XmlElement(name = "ContainsLiquidContents")
    protected String containsLiquidContents;
    @XmlElement(name = "FulfillmentCenterSpecialStorage")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String fulfillmentCenterSpecialStorage;
    @XmlElement(name = "HazmatException")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String hazmatException;
    @XmlElement(name = "IsDishwasherSafe")
    protected String isDishwasherSafe;
    @XmlElement(name = "IsExclusiveProduct")
    protected String isExclusiveProduct;
    @XmlElement(name = "ItemShape")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String itemShape;
    @XmlElement(name = "LanguageValue")
    protected String languageValue;
    @XmlElement(name = "LegalComplianceCertificationRegulatoryOrganizationName")
    protected String legalComplianceCertificationRegulatoryOrganizationName;
    @XmlElement(name = "ModelNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String modelNumber;
    @XmlElement(name = "ModelName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String modelName;
    @XmlElement(name = "NumberOfBoxes")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfBoxes;
    @XmlElement(name = "ArtistBiography")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String artistBiography;
    @XmlElement(name = "SpecificationMet")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String specificationMet;
    @XmlElement(name = "WarmthRating")
    protected TemperatureRatingDimension warmthRating;
    @XmlElement(name = "VariationData")
    protected DutchOvens.VariationData variationData;
    @XmlElement(name = "WarrantyDescription")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String warrantyDescription;

    /**
     * Gets the value of the capacity property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeDimension }
     *     
     */
    public VolumeDimension getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeDimension }
     *     
     */
    public void setCapacity(VolumeDimension value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the careInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCareInstructions() {
        return careInstructions;
    }

    /**
     * Sets the value of the careInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCareInstructions(String value) {
        this.careInstructions = value;
    }

    /**
     * Gets the value of the codabar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodabar() {
        return codabar;
    }

    /**
     * Sets the value of the codabar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodabar(String value) {
        this.codabar = value;
    }

    /**
     * Gets the value of the colorMap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorMap() {
        return colorMap;
    }

    /**
     * Sets the value of the colorMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorMap(String value) {
        this.colorMap = value;
    }

    /**
     * Gets the value of the containsLiquidContents property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainsLiquidContents() {
        return containsLiquidContents;
    }

    /**
     * Sets the value of the containsLiquidContents property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainsLiquidContents(String value) {
        this.containsLiquidContents = value;
    }

    /**
     * Gets the value of the fulfillmentCenterSpecialStorage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFulfillmentCenterSpecialStorage() {
        return fulfillmentCenterSpecialStorage;
    }

    /**
     * Sets the value of the fulfillmentCenterSpecialStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFulfillmentCenterSpecialStorage(String value) {
        this.fulfillmentCenterSpecialStorage = value;
    }

    /**
     * Gets the value of the hazmatException property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHazmatException() {
        return hazmatException;
    }

    /**
     * Sets the value of the hazmatException property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHazmatException(String value) {
        this.hazmatException = value;
    }

    /**
     * Gets the value of the isDishwasherSafe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDishwasherSafe() {
        return isDishwasherSafe;
    }

    /**
     * Sets the value of the isDishwasherSafe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDishwasherSafe(String value) {
        this.isDishwasherSafe = value;
    }

    /**
     * Gets the value of the isExclusiveProduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsExclusiveProduct() {
        return isExclusiveProduct;
    }

    /**
     * Sets the value of the isExclusiveProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsExclusiveProduct(String value) {
        this.isExclusiveProduct = value;
    }

    /**
     * Gets the value of the itemShape property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemShape() {
        return itemShape;
    }

    /**
     * Sets the value of the itemShape property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemShape(String value) {
        this.itemShape = value;
    }

    /**
     * Gets the value of the languageValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageValue() {
        return languageValue;
    }

    /**
     * Sets the value of the languageValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageValue(String value) {
        this.languageValue = value;
    }

    /**
     * Gets the value of the legalComplianceCertificationRegulatoryOrganizationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalComplianceCertificationRegulatoryOrganizationName() {
        return legalComplianceCertificationRegulatoryOrganizationName;
    }

    /**
     * Sets the value of the legalComplianceCertificationRegulatoryOrganizationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalComplianceCertificationRegulatoryOrganizationName(String value) {
        this.legalComplianceCertificationRegulatoryOrganizationName = value;
    }

    /**
     * Gets the value of the modelNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelNumber() {
        return modelNumber;
    }

    /**
     * Sets the value of the modelNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelNumber(String value) {
        this.modelNumber = value;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the numberOfBoxes property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfBoxes() {
        return numberOfBoxes;
    }

    /**
     * Sets the value of the numberOfBoxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfBoxes(BigInteger value) {
        this.numberOfBoxes = value;
    }

    /**
     * Gets the value of the artistBiography property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtistBiography() {
        return artistBiography;
    }

    /**
     * Sets the value of the artistBiography property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtistBiography(String value) {
        this.artistBiography = value;
    }

    /**
     * Gets the value of the specificationMet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecificationMet() {
        return specificationMet;
    }

    /**
     * Sets the value of the specificationMet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecificationMet(String value) {
        this.specificationMet = value;
    }

    /**
     * Gets the value of the warmthRating property.
     * 
     * @return
     *     possible object is
     *     {@link TemperatureRatingDimension }
     *     
     */
    public TemperatureRatingDimension getWarmthRating() {
        return warmthRating;
    }

    /**
     * Sets the value of the warmthRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemperatureRatingDimension }
     *     
     */
    public void setWarmthRating(TemperatureRatingDimension value) {
        this.warmthRating = value;
    }

    /**
     * Gets the value of the variationData property.
     * 
     * @return
     *     possible object is
     *     {@link DutchOvens.VariationData }
     *     
     */
    public DutchOvens.VariationData getVariationData() {
        return variationData;
    }

    /**
     * Sets the value of the variationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DutchOvens.VariationData }
     *     
     */
    public void setVariationData(DutchOvens.VariationData value) {
        this.variationData = value;
    }

    /**
     * Gets the value of the warrantyDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarrantyDescription() {
        return warrantyDescription;
    }

    /**
     * Sets the value of the warrantyDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarrantyDescription(String value) {
        this.warrantyDescription = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="VariationTheme"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="size_name"/&gt;
     *               &lt;enumeration value="sizecolor"/&gt;
     *               &lt;enumeration value="itempackagequantity"/&gt;
     *               &lt;enumeration value="colorsize"/&gt;
     *               &lt;enumeration value="size"/&gt;
     *               &lt;enumeration value="color_name"/&gt;
     *               &lt;enumeration value="sizename-colorname"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Parentage"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="parent"/&gt;
     *               &lt;enumeration value="child"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "variationTheme",
        "parentage"
    })
    public static class VariationData {

        @XmlElement(name = "VariationTheme", required = true)
        protected String variationTheme;
        @XmlElement(name = "Parentage", required = true)
        protected String parentage;

        /**
         * Gets the value of the variationTheme property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVariationTheme() {
            return variationTheme;
        }

        /**
         * Sets the value of the variationTheme property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVariationTheme(String value) {
            this.variationTheme = value;
        }

        /**
         * Gets the value of the parentage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParentage() {
            return parentage;
        }

        /**
         * Sets the value of the parentage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParentage(String value) {
            this.parentage = value;
        }

    }

}
