//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 11:40:51 PM CST 
//


package com.kindminds.drs.mws.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GenericUnit.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GenericUnit"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="kilograms"/&gt;
 *     &lt;enumeration value="grams"/&gt;
 *     &lt;enumeration value="milligrams"/&gt;
 *     &lt;enumeration value="ounces"/&gt;
 *     &lt;enumeration value="pounds"/&gt;
 *     &lt;enumeration value="inches"/&gt;
 *     &lt;enumeration value="feet"/&gt;
 *     &lt;enumeration value="meters"/&gt;
 *     &lt;enumeration value="centimeters"/&gt;
 *     &lt;enumeration value="millimeters"/&gt;
 *     &lt;enumeration value="square_meters"/&gt;
 *     &lt;enumeration value="square_centimeters"/&gt;
 *     &lt;enumeration value="square_feet"/&gt;
 *     &lt;enumeration value="square_inches"/&gt;
 *     &lt;enumeration value="gallons"/&gt;
 *     &lt;enumeration value="pints"/&gt;
 *     &lt;enumeration value="quarts"/&gt;
 *     &lt;enumeration value="fluid_ounces"/&gt;
 *     &lt;enumeration value="liters"/&gt;
 *     &lt;enumeration value="cubic_meters"/&gt;
 *     &lt;enumeration value="cubic_feet"/&gt;
 *     &lt;enumeration value="cubic_inches"/&gt;
 *     &lt;enumeration value="cubic_centimeters"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "GenericUnit")
@XmlEnum
public enum GenericUnit {

    @XmlEnumValue("kilograms")
    KILOGRAMS("kilograms"),
    @XmlEnumValue("grams")
    GRAMS("grams"),
    @XmlEnumValue("milligrams")
    MILLIGRAMS("milligrams"),
    @XmlEnumValue("ounces")
    OUNCES("ounces"),
    @XmlEnumValue("pounds")
    POUNDS("pounds"),
    @XmlEnumValue("inches")
    INCHES("inches"),
    @XmlEnumValue("feet")
    FEET("feet"),
    @XmlEnumValue("meters")
    METERS("meters"),
    @XmlEnumValue("centimeters")
    CENTIMETERS("centimeters"),
    @XmlEnumValue("millimeters")
    MILLIMETERS("millimeters"),
    @XmlEnumValue("square_meters")
    SQUARE___METERS("square_meters"),
    @XmlEnumValue("square_centimeters")
    SQUARE___CENTIMETERS("square_centimeters"),
    @XmlEnumValue("square_feet")
    SQUARE___FEET("square_feet"),
    @XmlEnumValue("square_inches")
    SQUARE___INCHES("square_inches"),
    @XmlEnumValue("gallons")
    GALLONS("gallons"),
    @XmlEnumValue("pints")
    PINTS("pints"),
    @XmlEnumValue("quarts")
    QUARTS("quarts"),
    @XmlEnumValue("fluid_ounces")
    FLUID___OUNCES("fluid_ounces"),
    @XmlEnumValue("liters")
    LITERS("liters"),
    @XmlEnumValue("cubic_meters")
    CUBIC___METERS("cubic_meters"),
    @XmlEnumValue("cubic_feet")
    CUBIC___FEET("cubic_feet"),
    @XmlEnumValue("cubic_inches")
    CUBIC___INCHES("cubic_inches"),
    @XmlEnumValue("cubic_centimeters")
    CUBIC___CENTIMETERS("cubic_centimeters");
    private final String value;

    GenericUnit(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GenericUnit fromValue(String v) {
        for (GenericUnit c: GenericUnit.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
