//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 11:40:51 PM CST 
//


package com.kindminds.drs.mws.xml;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for HomeImprovementTools complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HomeImprovementTools"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VariationData" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Parentage"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="parent"/&gt;
 *                         &lt;enumeration value="child"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="VariationTheme" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Size"/&gt;
 *                         &lt;enumeration value="Color"/&gt;
 *                         &lt;enumeration value="Size-Color"/&gt;
 *                         &lt;enumeration value="Style"/&gt;
 *                         &lt;enumeration value="PATTERN"/&gt;
 *                         &lt;enumeration value="ItemWeight"/&gt;
 *                         &lt;enumeration value="ItemPackageQuantity"/&gt;
 *                         &lt;enumeration value="CustomerPackageType"/&gt;
 *                         &lt;enumeration value="ColorName-CustomerPackageType"/&gt;
 *                         &lt;enumeration value="SizeName-CustomerPackageType"/&gt;
 *                         &lt;enumeration value="SizeName-ColorName-CustomerPackageType"/&gt;
 *                         &lt;enumeration value="StyleName-CustomerPackageType"/&gt;
 *                         &lt;enumeration value="SizeName-StyleName-CustomerPackageType"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AccessoryConnectionType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="BladeEdge" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="BladeLength" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="Brightness" type="{}LumensType" minOccurs="0"/&gt;
 *         &lt;element name="BulbType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="CenterLength" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="CompatibleDevices" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Coverage" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="CompatibleFastenerRange" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="CoolingMethod" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="CoolingWattage" type="{}WattageDimension" minOccurs="0"/&gt;
 *         &lt;element name="CornerRadius" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="CuttingDiameter" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="CutType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="CuttingWidth" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="DeviceType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="DisplayStyle" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="EnergyConsumption" type="{}EnergyConsumptionDimension" minOccurs="0"/&gt;
 *         &lt;element name="EnergyEfficiencyRatioCooling" type="{}PositiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="EnvironmentalDescription" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="EuEnergyEfficiencyClassHeating" type="{}EuEnergyEfficiencyClassType" minOccurs="0"/&gt;
 *         &lt;element name="EuEnergyLabelEfficiencyClass" type="{}EuEnergyEfficiencyClassType" minOccurs="0"/&gt;
 *         &lt;element name="ExternalTestingCertification" type="{}StringNotNull" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="FlushType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="HeadStyle" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="HeaterWattage" type="{}WattageDimension" minOccurs="0"/&gt;
 *         &lt;element name="InsideDiameter" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfBasins" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfHoles" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="OutsideDiameter" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="PlugFormat" type="{}HundredString" minOccurs="0"/&gt;
 *         &lt;element name="PlugProfile" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="RecycledContentPercentage" type="{}PositiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="RoughIn" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="SpoutHeight" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="SpoutReach" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="SwitchStyle" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="SwitchType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="ThreadSize" type="{}LengthDimensionOptionalUnit" minOccurs="0"/&gt;
 *         &lt;element name="Size" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Color" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="ColorMap" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="CustomerPackageType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="DisplayDiameter" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="DisplayVolume" type="{}VolumeDimension" minOccurs="0"/&gt;
 *         &lt;element name="DisplayWeight" type="{}WeightDimension" minOccurs="0"/&gt;
 *         &lt;element name="DisplayLength" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="DisplayWidth" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="DisplayHeight" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="FoldedKnifeSize" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="HandleMaterial" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="PowerSource" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Horsepower" type="{}PowerDimension" minOccurs="0"/&gt;
 *         &lt;element name="LaserBeamColor" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Material" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="MaximumPower" type="{}MaximumPowerType" minOccurs="0"/&gt;
 *         &lt;element name="MeasurementAccuracy" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="MeasurementSystem" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Wattage" type="{}WattageDimensionOptionalUnit" minOccurs="0"/&gt;
 *         &lt;element name="Voltage" type="{}Dimension" minOccurs="0"/&gt;
 *         &lt;element name="BatteryCapacity" type="{}BatteryPowerDimension" minOccurs="0"/&gt;
 *         &lt;element name="GritRating" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfItems" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="MinimumAge" type="{}AgeRecommendedDimension" minOccurs="0"/&gt;
 *         &lt;element name="ManufacturerWarrantyDescription" type="{}LongStringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="PerformanceDescription" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Speed" type="{}OptionalSpeedDimension" minOccurs="0"/&gt;
 *         &lt;element name="SellerWarrantyDescription" type="{}SuperLongStringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="ToolTipDescription" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Torque" type="{}TorqueType" minOccurs="0"/&gt;
 *         &lt;element name="UVProtection" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="ViewingArea" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="MinimumEfficiencyReportingValue" type="{}MERVType" minOccurs="0"/&gt;
 *         &lt;element name="BaseDiameter" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="BeamAngle" type="{}DegreeDimension" minOccurs="0"/&gt;
 *         &lt;element name="BladeColor" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="CircuitBreakerType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Efficiency" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="InternationalProtectionRating" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="LightSourceOperatingLife" type="{}TimeDimension" minOccurs="0"/&gt;
 *         &lt;element name="LightingMethod" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="MaximumCompatibleLightSourceWattage" type="{}WattageDimension" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfBlades" type="{}PositiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfLightSources" type="{}PositiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="ShadeDiameter" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="ShadeMaterialType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="ShortProductDescription" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="StartUpTimeDescription" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Strands" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="TubingOutsideDiameter" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="CustomerRestrictionType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="LegalComplianceCertificationMetadata" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="LegalComplianceCertificationDateOfIssue" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="LegalComplianceCertificationExpirationDate" type="{}StringNotNull" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HomeImprovementTools", propOrder = {
    "variationData",
    "accessoryConnectionType",
    "bladeEdge",
    "bladeLength",
    "brightness",
    "bulbType",
    "centerLength",
    "compatibleDevices",
    "coverage",
    "compatibleFastenerRange",
    "coolingMethod",
    "coolingWattage",
    "cornerRadius",
    "cuttingDiameter",
    "cutType",
    "cuttingWidth",
    "deviceType",
    "displayStyle",
    "energyConsumption",
    "energyEfficiencyRatioCooling",
    "environmentalDescription",
    "euEnergyEfficiencyClassHeating",
    "euEnergyLabelEfficiencyClass",
    "externalTestingCertification",
    "flushType",
    "headStyle",
    "heaterWattage",
    "insideDiameter",
    "numberOfBasins",
    "numberOfHoles",
    "outsideDiameter",
    "plugFormat",
    "plugProfile",
    "recycledContentPercentage",
    "roughIn",
    "spoutHeight",
    "spoutReach",
    "switchStyle",
    "switchType",
    "threadSize",
    "size",
    "color",
    "colorMap",
    "customerPackageType",
    "displayDiameter",
    "displayVolume",
    "displayWeight",
    "displayLength",
    "displayWidth",
    "displayHeight",
    "foldedKnifeSize",
    "handleMaterial",
    "powerSource",
    "horsepower",
    "laserBeamColor",
    "material",
    "maximumPower",
    "measurementAccuracy",
    "measurementSystem",
    "wattage",
    "voltage",
    "batteryCapacity",
    "gritRating",
    "numberOfItems",
    "minimumAge",
    "manufacturerWarrantyDescription",
    "performanceDescription",
    "speed",
    "sellerWarrantyDescription",
    "toolTipDescription",
    "torque",
    "uvProtection",
    "viewingArea",
    "minimumEfficiencyReportingValue",
    "baseDiameter",
    "beamAngle",
    "bladeColor",
    "circuitBreakerType",
    "efficiency",
    "internationalProtectionRating",
    "lightSourceOperatingLife",
    "lightingMethod",
    "maximumCompatibleLightSourceWattage",
    "numberOfBlades",
    "numberOfLightSources",
    "shadeDiameter",
    "shadeMaterialType",
    "shortProductDescription",
    "startUpTimeDescription",
    "strands",
    "tubingOutsideDiameter",
    "customerRestrictionType",
    "legalComplianceCertificationMetadata",
    "legalComplianceCertificationDateOfIssue",
    "legalComplianceCertificationExpirationDate"
})
public class HomeImprovementTools {

    @XmlElement(name = "VariationData")
    protected HomeImprovementTools.VariationData variationData;
    @XmlElement(name = "AccessoryConnectionType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String accessoryConnectionType;
    @XmlElement(name = "BladeEdge")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String bladeEdge;
    @XmlElement(name = "BladeLength")
    protected LengthDimension bladeLength;
    @XmlElement(name = "Brightness")
    protected LumensType brightness;
    @XmlElement(name = "BulbType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String bulbType;
    @XmlElement(name = "CenterLength")
    protected LengthDimension centerLength;
    @XmlElement(name = "CompatibleDevices")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String compatibleDevices;
    @XmlElement(name = "Coverage")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String coverage;
    @XmlElement(name = "CompatibleFastenerRange")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String compatibleFastenerRange;
    @XmlElement(name = "CoolingMethod")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String coolingMethod;
    @XmlElement(name = "CoolingWattage")
    protected WattageDimension coolingWattage;
    @XmlElement(name = "CornerRadius")
    protected LengthDimension cornerRadius;
    @XmlElement(name = "CuttingDiameter")
    protected LengthDimension cuttingDiameter;
    @XmlElement(name = "CutType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String cutType;
    @XmlElement(name = "CuttingWidth")
    protected LengthDimension cuttingWidth;
    @XmlElement(name = "DeviceType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String deviceType;
    @XmlElement(name = "DisplayStyle")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String displayStyle;
    @XmlElement(name = "EnergyConsumption")
    protected EnergyConsumptionDimension energyConsumption;
    @XmlElement(name = "EnergyEfficiencyRatioCooling")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger energyEfficiencyRatioCooling;
    @XmlElement(name = "EnvironmentalDescription")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String environmentalDescription;
    @XmlElement(name = "EuEnergyEfficiencyClassHeating")
    @XmlSchemaType(name = "string")
    protected EuEnergyEfficiencyClassType euEnergyEfficiencyClassHeating;
    @XmlElement(name = "EuEnergyLabelEfficiencyClass")
    @XmlSchemaType(name = "string")
    protected EuEnergyEfficiencyClassType euEnergyLabelEfficiencyClass;
    @XmlElement(name = "ExternalTestingCertification")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected List<String> externalTestingCertification;
    @XmlElement(name = "FlushType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String flushType;
    @XmlElement(name = "HeadStyle")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String headStyle;
    @XmlElement(name = "HeaterWattage")
    protected WattageDimension heaterWattage;
    @XmlElement(name = "InsideDiameter")
    protected LengthDimension insideDiameter;
    @XmlElement(name = "NumberOfBasins")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfBasins;
    @XmlElement(name = "NumberOfHoles")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfHoles;
    @XmlElement(name = "OutsideDiameter")
    protected LengthDimension outsideDiameter;
    @XmlElement(name = "PlugFormat")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String plugFormat;
    @XmlElement(name = "PlugProfile")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String plugProfile;
    @XmlElement(name = "RecycledContentPercentage")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger recycledContentPercentage;
    @XmlElement(name = "RoughIn")
    protected LengthDimension roughIn;
    @XmlElement(name = "SpoutHeight")
    protected LengthDimension spoutHeight;
    @XmlElement(name = "SpoutReach")
    protected LengthDimension spoutReach;
    @XmlElement(name = "SwitchStyle")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String switchStyle;
    @XmlElement(name = "SwitchType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String switchType;
    @XmlElement(name = "ThreadSize")
    protected LengthDimensionOptionalUnit threadSize;
    @XmlElement(name = "Size")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String size;
    @XmlElement(name = "Color")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String color;
    @XmlElement(name = "ColorMap")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String colorMap;
    @XmlElement(name = "CustomerPackageType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String customerPackageType;
    @XmlElement(name = "DisplayDiameter")
    protected LengthDimension displayDiameter;
    @XmlElement(name = "DisplayVolume")
    protected VolumeDimension displayVolume;
    @XmlElement(name = "DisplayWeight")
    protected WeightDimension displayWeight;
    @XmlElement(name = "DisplayLength")
    protected LengthDimension displayLength;
    @XmlElement(name = "DisplayWidth")
    protected LengthDimension displayWidth;
    @XmlElement(name = "DisplayHeight")
    protected LengthDimension displayHeight;
    @XmlElement(name = "FoldedKnifeSize")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String foldedKnifeSize;
    @XmlElement(name = "HandleMaterial")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String handleMaterial;
    @XmlElement(name = "PowerSource")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String powerSource;
    @XmlElement(name = "Horsepower")
    protected PowerDimension horsepower;
    @XmlElement(name = "LaserBeamColor")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String laserBeamColor;
    @XmlElement(name = "Material")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String material;
    @XmlElement(name = "MaximumPower")
    protected MaximumPowerType maximumPower;
    @XmlElement(name = "MeasurementAccuracy")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String measurementAccuracy;
    @XmlElement(name = "MeasurementSystem")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String measurementSystem;
    @XmlElement(name = "Wattage")
    protected WattageDimensionOptionalUnit wattage;
    @XmlElement(name = "Voltage")
    protected BigDecimal voltage;
    @XmlElement(name = "BatteryCapacity")
    protected BatteryPowerDimension batteryCapacity;
    @XmlElement(name = "GritRating")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger gritRating;
    @XmlElement(name = "NumberOfItems")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfItems;
    @XmlElement(name = "MinimumAge")
    protected AgeRecommendedDimension minimumAge;
    @XmlElement(name = "ManufacturerWarrantyDescription")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String manufacturerWarrantyDescription;
    @XmlElement(name = "PerformanceDescription")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String performanceDescription;
    @XmlElement(name = "Speed")
    protected OptionalSpeedDimension speed;
    @XmlElement(name = "SellerWarrantyDescription")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String sellerWarrantyDescription;
    @XmlElement(name = "ToolTipDescription")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String toolTipDescription;
    @XmlElement(name = "Torque")
    protected TorqueType torque;
    @XmlElement(name = "UVProtection")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String uvProtection;
    @XmlElement(name = "ViewingArea")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String viewingArea;
    @XmlElement(name = "MinimumEfficiencyReportingValue")
    @XmlSchemaType(name = "positiveInteger")
    protected Integer minimumEfficiencyReportingValue;
    @XmlElement(name = "BaseDiameter")
    protected LengthDimension baseDiameter;
    @XmlElement(name = "BeamAngle")
    protected DegreeDimension beamAngle;
    @XmlElement(name = "BladeColor")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String bladeColor;
    @XmlElement(name = "CircuitBreakerType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String circuitBreakerType;
    @XmlElement(name = "Efficiency")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String efficiency;
    @XmlElement(name = "InternationalProtectionRating")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String internationalProtectionRating;
    @XmlElement(name = "LightSourceOperatingLife")
    protected TimeDimension lightSourceOperatingLife;
    @XmlElement(name = "LightingMethod")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String lightingMethod;
    @XmlElement(name = "MaximumCompatibleLightSourceWattage")
    protected WattageDimension maximumCompatibleLightSourceWattage;
    @XmlElement(name = "NumberOfBlades")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfBlades;
    @XmlElement(name = "NumberOfLightSources")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfLightSources;
    @XmlElement(name = "ShadeDiameter")
    protected LengthDimension shadeDiameter;
    @XmlElement(name = "ShadeMaterialType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String shadeMaterialType;
    @XmlElement(name = "ShortProductDescription")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String shortProductDescription;
    @XmlElement(name = "StartUpTimeDescription")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String startUpTimeDescription;
    @XmlElement(name = "Strands")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String strands;
    @XmlElement(name = "TubingOutsideDiameter")
    protected LengthDimension tubingOutsideDiameter;
    @XmlElement(name = "CustomerRestrictionType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String customerRestrictionType;
    @XmlElement(name = "LegalComplianceCertificationMetadata")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String legalComplianceCertificationMetadata;
    @XmlElement(name = "LegalComplianceCertificationDateOfIssue")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String legalComplianceCertificationDateOfIssue;
    @XmlElement(name = "LegalComplianceCertificationExpirationDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String legalComplianceCertificationExpirationDate;

    /**
     * Gets the value of the variationData property.
     * 
     * @return
     *     possible object is
     *     {@link HomeImprovementTools.VariationData }
     *     
     */
    public HomeImprovementTools.VariationData getVariationData() {
        return variationData;
    }

    /**
     * Sets the value of the variationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link HomeImprovementTools.VariationData }
     *     
     */
    public void setVariationData(HomeImprovementTools.VariationData value) {
        this.variationData = value;
    }

    /**
     * Gets the value of the accessoryConnectionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessoryConnectionType() {
        return accessoryConnectionType;
    }

    /**
     * Sets the value of the accessoryConnectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessoryConnectionType(String value) {
        this.accessoryConnectionType = value;
    }

    /**
     * Gets the value of the bladeEdge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBladeEdge() {
        return bladeEdge;
    }

    /**
     * Sets the value of the bladeEdge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBladeEdge(String value) {
        this.bladeEdge = value;
    }

    /**
     * Gets the value of the bladeLength property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getBladeLength() {
        return bladeLength;
    }

    /**
     * Sets the value of the bladeLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setBladeLength(LengthDimension value) {
        this.bladeLength = value;
    }

    /**
     * Gets the value of the brightness property.
     * 
     * @return
     *     possible object is
     *     {@link LumensType }
     *     
     */
    public LumensType getBrightness() {
        return brightness;
    }

    /**
     * Sets the value of the brightness property.
     * 
     * @param value
     *     allowed object is
     *     {@link LumensType }
     *     
     */
    public void setBrightness(LumensType value) {
        this.brightness = value;
    }

    /**
     * Gets the value of the bulbType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBulbType() {
        return bulbType;
    }

    /**
     * Sets the value of the bulbType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBulbType(String value) {
        this.bulbType = value;
    }

    /**
     * Gets the value of the centerLength property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getCenterLength() {
        return centerLength;
    }

    /**
     * Sets the value of the centerLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setCenterLength(LengthDimension value) {
        this.centerLength = value;
    }

    /**
     * Gets the value of the compatibleDevices property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompatibleDevices() {
        return compatibleDevices;
    }

    /**
     * Sets the value of the compatibleDevices property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompatibleDevices(String value) {
        this.compatibleDevices = value;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverage() {
        return coverage;
    }

    /**
     * Sets the value of the coverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverage(String value) {
        this.coverage = value;
    }

    /**
     * Gets the value of the compatibleFastenerRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompatibleFastenerRange() {
        return compatibleFastenerRange;
    }

    /**
     * Sets the value of the compatibleFastenerRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompatibleFastenerRange(String value) {
        this.compatibleFastenerRange = value;
    }

    /**
     * Gets the value of the coolingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoolingMethod() {
        return coolingMethod;
    }

    /**
     * Sets the value of the coolingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoolingMethod(String value) {
        this.coolingMethod = value;
    }

    /**
     * Gets the value of the coolingWattage property.
     * 
     * @return
     *     possible object is
     *     {@link WattageDimension }
     *     
     */
    public WattageDimension getCoolingWattage() {
        return coolingWattage;
    }

    /**
     * Sets the value of the coolingWattage property.
     * 
     * @param value
     *     allowed object is
     *     {@link WattageDimension }
     *     
     */
    public void setCoolingWattage(WattageDimension value) {
        this.coolingWattage = value;
    }

    /**
     * Gets the value of the cornerRadius property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getCornerRadius() {
        return cornerRadius;
    }

    /**
     * Sets the value of the cornerRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setCornerRadius(LengthDimension value) {
        this.cornerRadius = value;
    }

    /**
     * Gets the value of the cuttingDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getCuttingDiameter() {
        return cuttingDiameter;
    }

    /**
     * Sets the value of the cuttingDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setCuttingDiameter(LengthDimension value) {
        this.cuttingDiameter = value;
    }

    /**
     * Gets the value of the cutType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCutType() {
        return cutType;
    }

    /**
     * Sets the value of the cutType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCutType(String value) {
        this.cutType = value;
    }

    /**
     * Gets the value of the cuttingWidth property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getCuttingWidth() {
        return cuttingWidth;
    }

    /**
     * Sets the value of the cuttingWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setCuttingWidth(LengthDimension value) {
        this.cuttingWidth = value;
    }

    /**
     * Gets the value of the deviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * Sets the value of the deviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceType(String value) {
        this.deviceType = value;
    }

    /**
     * Gets the value of the displayStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayStyle() {
        return displayStyle;
    }

    /**
     * Sets the value of the displayStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayStyle(String value) {
        this.displayStyle = value;
    }

    /**
     * Gets the value of the energyConsumption property.
     * 
     * @return
     *     possible object is
     *     {@link EnergyConsumptionDimension }
     *     
     */
    public EnergyConsumptionDimension getEnergyConsumption() {
        return energyConsumption;
    }

    /**
     * Sets the value of the energyConsumption property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnergyConsumptionDimension }
     *     
     */
    public void setEnergyConsumption(EnergyConsumptionDimension value) {
        this.energyConsumption = value;
    }

    /**
     * Gets the value of the energyEfficiencyRatioCooling property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEnergyEfficiencyRatioCooling() {
        return energyEfficiencyRatioCooling;
    }

    /**
     * Sets the value of the energyEfficiencyRatioCooling property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEnergyEfficiencyRatioCooling(BigInteger value) {
        this.energyEfficiencyRatioCooling = value;
    }

    /**
     * Gets the value of the environmentalDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnvironmentalDescription() {
        return environmentalDescription;
    }

    /**
     * Sets the value of the environmentalDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnvironmentalDescription(String value) {
        this.environmentalDescription = value;
    }

    /**
     * Gets the value of the euEnergyEfficiencyClassHeating property.
     * 
     * @return
     *     possible object is
     *     {@link EuEnergyEfficiencyClassType }
     *     
     */
    public EuEnergyEfficiencyClassType getEuEnergyEfficiencyClassHeating() {
        return euEnergyEfficiencyClassHeating;
    }

    /**
     * Sets the value of the euEnergyEfficiencyClassHeating property.
     * 
     * @param value
     *     allowed object is
     *     {@link EuEnergyEfficiencyClassType }
     *     
     */
    public void setEuEnergyEfficiencyClassHeating(EuEnergyEfficiencyClassType value) {
        this.euEnergyEfficiencyClassHeating = value;
    }

    /**
     * Gets the value of the euEnergyLabelEfficiencyClass property.
     * 
     * @return
     *     possible object is
     *     {@link EuEnergyEfficiencyClassType }
     *     
     */
    public EuEnergyEfficiencyClassType getEuEnergyLabelEfficiencyClass() {
        return euEnergyLabelEfficiencyClass;
    }

    /**
     * Sets the value of the euEnergyLabelEfficiencyClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link EuEnergyEfficiencyClassType }
     *     
     */
    public void setEuEnergyLabelEfficiencyClass(EuEnergyEfficiencyClassType value) {
        this.euEnergyLabelEfficiencyClass = value;
    }

    /**
     * Gets the value of the externalTestingCertification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalTestingCertification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalTestingCertification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getExternalTestingCertification() {
        if (externalTestingCertification == null) {
            externalTestingCertification = new ArrayList<String>();
        }
        return this.externalTestingCertification;
    }

    /**
     * Gets the value of the flushType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlushType() {
        return flushType;
    }

    /**
     * Sets the value of the flushType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlushType(String value) {
        this.flushType = value;
    }

    /**
     * Gets the value of the headStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeadStyle() {
        return headStyle;
    }

    /**
     * Sets the value of the headStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeadStyle(String value) {
        this.headStyle = value;
    }

    /**
     * Gets the value of the heaterWattage property.
     * 
     * @return
     *     possible object is
     *     {@link WattageDimension }
     *     
     */
    public WattageDimension getHeaterWattage() {
        return heaterWattage;
    }

    /**
     * Sets the value of the heaterWattage property.
     * 
     * @param value
     *     allowed object is
     *     {@link WattageDimension }
     *     
     */
    public void setHeaterWattage(WattageDimension value) {
        this.heaterWattage = value;
    }

    /**
     * Gets the value of the insideDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getInsideDiameter() {
        return insideDiameter;
    }

    /**
     * Sets the value of the insideDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setInsideDiameter(LengthDimension value) {
        this.insideDiameter = value;
    }

    /**
     * Gets the value of the numberOfBasins property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfBasins() {
        return numberOfBasins;
    }

    /**
     * Sets the value of the numberOfBasins property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfBasins(BigInteger value) {
        this.numberOfBasins = value;
    }

    /**
     * Gets the value of the numberOfHoles property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfHoles() {
        return numberOfHoles;
    }

    /**
     * Sets the value of the numberOfHoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfHoles(BigInteger value) {
        this.numberOfHoles = value;
    }

    /**
     * Gets the value of the outsideDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getOutsideDiameter() {
        return outsideDiameter;
    }

    /**
     * Sets the value of the outsideDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setOutsideDiameter(LengthDimension value) {
        this.outsideDiameter = value;
    }

    /**
     * Gets the value of the plugFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlugFormat() {
        return plugFormat;
    }

    /**
     * Sets the value of the plugFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlugFormat(String value) {
        this.plugFormat = value;
    }

    /**
     * Gets the value of the plugProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlugProfile() {
        return plugProfile;
    }

    /**
     * Sets the value of the plugProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlugProfile(String value) {
        this.plugProfile = value;
    }

    /**
     * Gets the value of the recycledContentPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRecycledContentPercentage() {
        return recycledContentPercentage;
    }

    /**
     * Sets the value of the recycledContentPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRecycledContentPercentage(BigInteger value) {
        this.recycledContentPercentage = value;
    }

    /**
     * Gets the value of the roughIn property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getRoughIn() {
        return roughIn;
    }

    /**
     * Sets the value of the roughIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setRoughIn(LengthDimension value) {
        this.roughIn = value;
    }

    /**
     * Gets the value of the spoutHeight property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getSpoutHeight() {
        return spoutHeight;
    }

    /**
     * Sets the value of the spoutHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setSpoutHeight(LengthDimension value) {
        this.spoutHeight = value;
    }

    /**
     * Gets the value of the spoutReach property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getSpoutReach() {
        return spoutReach;
    }

    /**
     * Sets the value of the spoutReach property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setSpoutReach(LengthDimension value) {
        this.spoutReach = value;
    }

    /**
     * Gets the value of the switchStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwitchStyle() {
        return switchStyle;
    }

    /**
     * Sets the value of the switchStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwitchStyle(String value) {
        this.switchStyle = value;
    }

    /**
     * Gets the value of the switchType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwitchType() {
        return switchType;
    }

    /**
     * Sets the value of the switchType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwitchType(String value) {
        this.switchType = value;
    }

    /**
     * Gets the value of the threadSize property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimensionOptionalUnit }
     *     
     */
    public LengthDimensionOptionalUnit getThreadSize() {
        return threadSize;
    }

    /**
     * Sets the value of the threadSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimensionOptionalUnit }
     *     
     */
    public void setThreadSize(LengthDimensionOptionalUnit value) {
        this.threadSize = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSize(String value) {
        this.size = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the colorMap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorMap() {
        return colorMap;
    }

    /**
     * Sets the value of the colorMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorMap(String value) {
        this.colorMap = value;
    }

    /**
     * Gets the value of the customerPackageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerPackageType() {
        return customerPackageType;
    }

    /**
     * Sets the value of the customerPackageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerPackageType(String value) {
        this.customerPackageType = value;
    }

    /**
     * Gets the value of the displayDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getDisplayDiameter() {
        return displayDiameter;
    }

    /**
     * Sets the value of the displayDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setDisplayDiameter(LengthDimension value) {
        this.displayDiameter = value;
    }

    /**
     * Gets the value of the displayVolume property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeDimension }
     *     
     */
    public VolumeDimension getDisplayVolume() {
        return displayVolume;
    }

    /**
     * Sets the value of the displayVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeDimension }
     *     
     */
    public void setDisplayVolume(VolumeDimension value) {
        this.displayVolume = value;
    }

    /**
     * Gets the value of the displayWeight property.
     * 
     * @return
     *     possible object is
     *     {@link WeightDimension }
     *     
     */
    public WeightDimension getDisplayWeight() {
        return displayWeight;
    }

    /**
     * Sets the value of the displayWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightDimension }
     *     
     */
    public void setDisplayWeight(WeightDimension value) {
        this.displayWeight = value;
    }

    /**
     * Gets the value of the displayLength property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getDisplayLength() {
        return displayLength;
    }

    /**
     * Sets the value of the displayLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setDisplayLength(LengthDimension value) {
        this.displayLength = value;
    }

    /**
     * Gets the value of the displayWidth property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getDisplayWidth() {
        return displayWidth;
    }

    /**
     * Sets the value of the displayWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setDisplayWidth(LengthDimension value) {
        this.displayWidth = value;
    }

    /**
     * Gets the value of the displayHeight property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getDisplayHeight() {
        return displayHeight;
    }

    /**
     * Sets the value of the displayHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setDisplayHeight(LengthDimension value) {
        this.displayHeight = value;
    }

    /**
     * Gets the value of the foldedKnifeSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFoldedKnifeSize() {
        return foldedKnifeSize;
    }

    /**
     * Sets the value of the foldedKnifeSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFoldedKnifeSize(String value) {
        this.foldedKnifeSize = value;
    }

    /**
     * Gets the value of the handleMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandleMaterial() {
        return handleMaterial;
    }

    /**
     * Sets the value of the handleMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandleMaterial(String value) {
        this.handleMaterial = value;
    }

    /**
     * Gets the value of the powerSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPowerSource() {
        return powerSource;
    }

    /**
     * Sets the value of the powerSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPowerSource(String value) {
        this.powerSource = value;
    }

    /**
     * Gets the value of the horsepower property.
     * 
     * @return
     *     possible object is
     *     {@link PowerDimension }
     *     
     */
    public PowerDimension getHorsepower() {
        return horsepower;
    }

    /**
     * Sets the value of the horsepower property.
     * 
     * @param value
     *     allowed object is
     *     {@link PowerDimension }
     *     
     */
    public void setHorsepower(PowerDimension value) {
        this.horsepower = value;
    }

    /**
     * Gets the value of the laserBeamColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaserBeamColor() {
        return laserBeamColor;
    }

    /**
     * Sets the value of the laserBeamColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaserBeamColor(String value) {
        this.laserBeamColor = value;
    }

    /**
     * Gets the value of the material property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterial() {
        return material;
    }

    /**
     * Sets the value of the material property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterial(String value) {
        this.material = value;
    }

    /**
     * Gets the value of the maximumPower property.
     * 
     * @return
     *     possible object is
     *     {@link MaximumPowerType }
     *     
     */
    public MaximumPowerType getMaximumPower() {
        return maximumPower;
    }

    /**
     * Sets the value of the maximumPower property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaximumPowerType }
     *     
     */
    public void setMaximumPower(MaximumPowerType value) {
        this.maximumPower = value;
    }

    /**
     * Gets the value of the measurementAccuracy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementAccuracy() {
        return measurementAccuracy;
    }

    /**
     * Sets the value of the measurementAccuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementAccuracy(String value) {
        this.measurementAccuracy = value;
    }

    /**
     * Gets the value of the measurementSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementSystem() {
        return measurementSystem;
    }

    /**
     * Sets the value of the measurementSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementSystem(String value) {
        this.measurementSystem = value;
    }

    /**
     * Gets the value of the wattage property.
     * 
     * @return
     *     possible object is
     *     {@link WattageDimensionOptionalUnit }
     *     
     */
    public WattageDimensionOptionalUnit getWattage() {
        return wattage;
    }

    /**
     * Sets the value of the wattage property.
     * 
     * @param value
     *     allowed object is
     *     {@link WattageDimensionOptionalUnit }
     *     
     */
    public void setWattage(WattageDimensionOptionalUnit value) {
        this.wattage = value;
    }

    /**
     * Gets the value of the voltage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVoltage() {
        return voltage;
    }

    /**
     * Sets the value of the voltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVoltage(BigDecimal value) {
        this.voltage = value;
    }

    /**
     * Gets the value of the batteryCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link BatteryPowerDimension }
     *     
     */
    public BatteryPowerDimension getBatteryCapacity() {
        return batteryCapacity;
    }

    /**
     * Sets the value of the batteryCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatteryPowerDimension }
     *     
     */
    public void setBatteryCapacity(BatteryPowerDimension value) {
        this.batteryCapacity = value;
    }

    /**
     * Gets the value of the gritRating property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGritRating() {
        return gritRating;
    }

    /**
     * Sets the value of the gritRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGritRating(BigInteger value) {
        this.gritRating = value;
    }

    /**
     * Gets the value of the numberOfItems property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfItems() {
        return numberOfItems;
    }

    /**
     * Sets the value of the numberOfItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfItems(BigInteger value) {
        this.numberOfItems = value;
    }

    /**
     * Gets the value of the minimumAge property.
     * 
     * @return
     *     possible object is
     *     {@link AgeRecommendedDimension }
     *     
     */
    public AgeRecommendedDimension getMinimumAge() {
        return minimumAge;
    }

    /**
     * Sets the value of the minimumAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgeRecommendedDimension }
     *     
     */
    public void setMinimumAge(AgeRecommendedDimension value) {
        this.minimumAge = value;
    }

    /**
     * Gets the value of the manufacturerWarrantyDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturerWarrantyDescription() {
        return manufacturerWarrantyDescription;
    }

    /**
     * Sets the value of the manufacturerWarrantyDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturerWarrantyDescription(String value) {
        this.manufacturerWarrantyDescription = value;
    }

    /**
     * Gets the value of the performanceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerformanceDescription() {
        return performanceDescription;
    }

    /**
     * Sets the value of the performanceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerformanceDescription(String value) {
        this.performanceDescription = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalSpeedDimension }
     *     
     */
    public OptionalSpeedDimension getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalSpeedDimension }
     *     
     */
    public void setSpeed(OptionalSpeedDimension value) {
        this.speed = value;
    }

    /**
     * Gets the value of the sellerWarrantyDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerWarrantyDescription() {
        return sellerWarrantyDescription;
    }

    /**
     * Sets the value of the sellerWarrantyDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerWarrantyDescription(String value) {
        this.sellerWarrantyDescription = value;
    }

    /**
     * Gets the value of the toolTipDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToolTipDescription() {
        return toolTipDescription;
    }

    /**
     * Sets the value of the toolTipDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToolTipDescription(String value) {
        this.toolTipDescription = value;
    }

    /**
     * Gets the value of the torque property.
     * 
     * @return
     *     possible object is
     *     {@link TorqueType }
     *     
     */
    public TorqueType getTorque() {
        return torque;
    }

    /**
     * Sets the value of the torque property.
     * 
     * @param value
     *     allowed object is
     *     {@link TorqueType }
     *     
     */
    public void setTorque(TorqueType value) {
        this.torque = value;
    }

    /**
     * Gets the value of the uvProtection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUVProtection() {
        return uvProtection;
    }

    /**
     * Sets the value of the uvProtection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUVProtection(String value) {
        this.uvProtection = value;
    }

    /**
     * Gets the value of the viewingArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewingArea() {
        return viewingArea;
    }

    /**
     * Sets the value of the viewingArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewingArea(String value) {
        this.viewingArea = value;
    }

    /**
     * Gets the value of the minimumEfficiencyReportingValue property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinimumEfficiencyReportingValue() {
        return minimumEfficiencyReportingValue;
    }

    /**
     * Sets the value of the minimumEfficiencyReportingValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinimumEfficiencyReportingValue(Integer value) {
        this.minimumEfficiencyReportingValue = value;
    }

    /**
     * Gets the value of the baseDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getBaseDiameter() {
        return baseDiameter;
    }

    /**
     * Sets the value of the baseDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setBaseDiameter(LengthDimension value) {
        this.baseDiameter = value;
    }

    /**
     * Gets the value of the beamAngle property.
     * 
     * @return
     *     possible object is
     *     {@link DegreeDimension }
     *     
     */
    public DegreeDimension getBeamAngle() {
        return beamAngle;
    }

    /**
     * Sets the value of the beamAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link DegreeDimension }
     *     
     */
    public void setBeamAngle(DegreeDimension value) {
        this.beamAngle = value;
    }

    /**
     * Gets the value of the bladeColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBladeColor() {
        return bladeColor;
    }

    /**
     * Sets the value of the bladeColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBladeColor(String value) {
        this.bladeColor = value;
    }

    /**
     * Gets the value of the circuitBreakerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCircuitBreakerType() {
        return circuitBreakerType;
    }

    /**
     * Sets the value of the circuitBreakerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCircuitBreakerType(String value) {
        this.circuitBreakerType = value;
    }

    /**
     * Gets the value of the efficiency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEfficiency() {
        return efficiency;
    }

    /**
     * Sets the value of the efficiency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEfficiency(String value) {
        this.efficiency = value;
    }

    /**
     * Gets the value of the internationalProtectionRating property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalProtectionRating() {
        return internationalProtectionRating;
    }

    /**
     * Sets the value of the internationalProtectionRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalProtectionRating(String value) {
        this.internationalProtectionRating = value;
    }

    /**
     * Gets the value of the lightSourceOperatingLife property.
     * 
     * @return
     *     possible object is
     *     {@link TimeDimension }
     *     
     */
    public TimeDimension getLightSourceOperatingLife() {
        return lightSourceOperatingLife;
    }

    /**
     * Sets the value of the lightSourceOperatingLife property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeDimension }
     *     
     */
    public void setLightSourceOperatingLife(TimeDimension value) {
        this.lightSourceOperatingLife = value;
    }

    /**
     * Gets the value of the lightingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLightingMethod() {
        return lightingMethod;
    }

    /**
     * Sets the value of the lightingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLightingMethod(String value) {
        this.lightingMethod = value;
    }

    /**
     * Gets the value of the maximumCompatibleLightSourceWattage property.
     * 
     * @return
     *     possible object is
     *     {@link WattageDimension }
     *     
     */
    public WattageDimension getMaximumCompatibleLightSourceWattage() {
        return maximumCompatibleLightSourceWattage;
    }

    /**
     * Sets the value of the maximumCompatibleLightSourceWattage property.
     * 
     * @param value
     *     allowed object is
     *     {@link WattageDimension }
     *     
     */
    public void setMaximumCompatibleLightSourceWattage(WattageDimension value) {
        this.maximumCompatibleLightSourceWattage = value;
    }

    /**
     * Gets the value of the numberOfBlades property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfBlades() {
        return numberOfBlades;
    }

    /**
     * Sets the value of the numberOfBlades property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfBlades(BigInteger value) {
        this.numberOfBlades = value;
    }

    /**
     * Gets the value of the numberOfLightSources property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfLightSources() {
        return numberOfLightSources;
    }

    /**
     * Sets the value of the numberOfLightSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfLightSources(BigInteger value) {
        this.numberOfLightSources = value;
    }

    /**
     * Gets the value of the shadeDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getShadeDiameter() {
        return shadeDiameter;
    }

    /**
     * Sets the value of the shadeDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setShadeDiameter(LengthDimension value) {
        this.shadeDiameter = value;
    }

    /**
     * Gets the value of the shadeMaterialType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShadeMaterialType() {
        return shadeMaterialType;
    }

    /**
     * Sets the value of the shadeMaterialType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShadeMaterialType(String value) {
        this.shadeMaterialType = value;
    }

    /**
     * Gets the value of the shortProductDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortProductDescription() {
        return shortProductDescription;
    }

    /**
     * Sets the value of the shortProductDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortProductDescription(String value) {
        this.shortProductDescription = value;
    }

    /**
     * Gets the value of the startUpTimeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartUpTimeDescription() {
        return startUpTimeDescription;
    }

    /**
     * Sets the value of the startUpTimeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartUpTimeDescription(String value) {
        this.startUpTimeDescription = value;
    }

    /**
     * Gets the value of the strands property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrands() {
        return strands;
    }

    /**
     * Sets the value of the strands property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrands(String value) {
        this.strands = value;
    }

    /**
     * Gets the value of the tubingOutsideDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getTubingOutsideDiameter() {
        return tubingOutsideDiameter;
    }

    /**
     * Sets the value of the tubingOutsideDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setTubingOutsideDiameter(LengthDimension value) {
        this.tubingOutsideDiameter = value;
    }

    /**
     * Gets the value of the customerRestrictionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerRestrictionType() {
        return customerRestrictionType;
    }

    /**
     * Sets the value of the customerRestrictionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerRestrictionType(String value) {
        this.customerRestrictionType = value;
    }

    /**
     * Gets the value of the legalComplianceCertificationMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalComplianceCertificationMetadata() {
        return legalComplianceCertificationMetadata;
    }

    /**
     * Sets the value of the legalComplianceCertificationMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalComplianceCertificationMetadata(String value) {
        this.legalComplianceCertificationMetadata = value;
    }

    /**
     * Gets the value of the legalComplianceCertificationDateOfIssue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalComplianceCertificationDateOfIssue() {
        return legalComplianceCertificationDateOfIssue;
    }

    /**
     * Sets the value of the legalComplianceCertificationDateOfIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalComplianceCertificationDateOfIssue(String value) {
        this.legalComplianceCertificationDateOfIssue = value;
    }

    /**
     * Gets the value of the legalComplianceCertificationExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalComplianceCertificationExpirationDate() {
        return legalComplianceCertificationExpirationDate;
    }

    /**
     * Sets the value of the legalComplianceCertificationExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalComplianceCertificationExpirationDate(String value) {
        this.legalComplianceCertificationExpirationDate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Parentage"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="parent"/&gt;
     *               &lt;enumeration value="child"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="VariationTheme" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Size"/&gt;
     *               &lt;enumeration value="Color"/&gt;
     *               &lt;enumeration value="Size-Color"/&gt;
     *               &lt;enumeration value="Style"/&gt;
     *               &lt;enumeration value="PATTERN"/&gt;
     *               &lt;enumeration value="ItemWeight"/&gt;
     *               &lt;enumeration value="ItemPackageQuantity"/&gt;
     *               &lt;enumeration value="CustomerPackageType"/&gt;
     *               &lt;enumeration value="ColorName-CustomerPackageType"/&gt;
     *               &lt;enumeration value="SizeName-CustomerPackageType"/&gt;
     *               &lt;enumeration value="SizeName-ColorName-CustomerPackageType"/&gt;
     *               &lt;enumeration value="StyleName-CustomerPackageType"/&gt;
     *               &lt;enumeration value="SizeName-StyleName-CustomerPackageType"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parentage",
        "variationTheme"
    })
    public static class VariationData {

        @XmlElement(name = "Parentage", required = true)
        protected String parentage;
        @XmlElement(name = "VariationTheme")
        protected String variationTheme;

        /**
         * Gets the value of the parentage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParentage() {
            return parentage;
        }

        /**
         * Sets the value of the parentage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParentage(String value) {
            this.parentage = value;
        }

        /**
         * Gets the value of the variationTheme property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVariationTheme() {
            return variationTheme;
        }

        /**
         * Sets the value of the variationTheme property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVariationTheme(String value) {
            this.variationTheme = value;
        }

    }

}
