//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 11:40:51 PM CST 
//


package com.kindminds.drs.mws.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InternalConnectorTypeValues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InternalConnectorTypeValues"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="eide"/&gt;
 *     &lt;enumeration value="fibre_channel"/&gt;
 *     &lt;enumeration value="ide"/&gt;
 *     &lt;enumeration value="pci_express_x4"/&gt;
 *     &lt;enumeration value="pci_express_x8"/&gt;
 *     &lt;enumeration value="serial_scsi"/&gt;
 *     &lt;enumeration value="serial_ata150"/&gt;
 *     &lt;enumeration value="serial_ata300"/&gt;
 *     &lt;enumeration value="serial_ata600"/&gt;
 *     &lt;enumeration value="scsi"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "InternalConnectorTypeValues")
@XmlEnum
public enum InternalConnectorTypeValues {

    @XmlEnumValue("eide")
    EIDE("eide"),
    @XmlEnumValue("fibre_channel")
    FIBRE___CHANNEL("fibre_channel"),
    @XmlEnumValue("ide")
    IDE("ide"),
    @XmlEnumValue("pci_express_x4")
    PCI___EXPRESS___X_4("pci_express_x4"),
    @XmlEnumValue("pci_express_x8")
    PCI___EXPRESS___X_8("pci_express_x8"),
    @XmlEnumValue("serial_scsi")
    SERIAL___SCSI("serial_scsi"),
    @XmlEnumValue("serial_ata150")
    SERIAL___ATA_150("serial_ata150"),
    @XmlEnumValue("serial_ata300")
    SERIAL___ATA_300("serial_ata300"),
    @XmlEnumValue("serial_ata600")
    SERIAL___ATA_600("serial_ata600"),
    @XmlEnumValue("scsi")
    SCSI("scsi");
    private final String value;

    InternalConnectorTypeValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InternalConnectorTypeValues fromValue(String v) {
        for (InternalConnectorTypeValues c: InternalConnectorTypeValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
