//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 11:40:51 PM CST 
//


package com.kindminds.drs.mws.xml;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Rebate" type="{}RebateType" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="ProductType"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element ref="{}BrassAndWoodwindInstruments"/&gt;
 *                   &lt;element ref="{}Guitars"/&gt;
 *                   &lt;element ref="{}InstrumentPartsAndAccessories"/&gt;
 *                   &lt;element ref="{}KeyboardInstruments"/&gt;
 *                   &lt;element ref="{}MiscWorldInstruments"/&gt;
 *                   &lt;element ref="{}PercussionInstruments"/&gt;
 *                   &lt;element ref="{}SoundAndRecordingEquipment"/&gt;
 *                   &lt;element ref="{}StringedInstruments"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="BatteryAverageLife" type="{}PositiveDimension" minOccurs="0"/&gt;
 *         &lt;element name="BatteryAverageLifeStandby" type="{}PositiveDimension" minOccurs="0"/&gt;
 *         &lt;element name="BatteryChargeTime" type="{}PositiveDimension" minOccurs="0"/&gt;
 *         &lt;element name="BatteryTypeLithiumIon" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="BatteryTypeLithiumMetal" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="CountryOfOrigin" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="LithiumBatteryEnergyContent" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="LithiumBatteryPackaging" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="batteries_contained_in_equipment"/&gt;
 *               &lt;enumeration value="batteries_only"/&gt;
 *               &lt;enumeration value="batteries_packed_with_equipment"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LithiumBatteryVoltage" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="LithiumBatteryWeight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="MfgWarrantyDescriptionLabor" type="{}SuperLongStringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="MfgWarrantyDescriptionParts" type="{}SuperLongStringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="ManufacturerWarrantyType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfLithiumIonCells" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfLithiumMetalCells" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="PowerSource" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="TargetGender" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Warnings" type="{}LongStringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="WarrantyDescription" type="{}SuperLongStringNotNull" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rebate",
    "productType",
    "batteryAverageLife",
    "batteryAverageLifeStandby",
    "batteryChargeTime",
    "batteryTypeLithiumIon",
    "batteryTypeLithiumMetal",
    "countryOfOrigin",
    "lithiumBatteryEnergyContent",
    "lithiumBatteryPackaging",
    "lithiumBatteryVoltage",
    "lithiumBatteryWeight",
    "mfgWarrantyDescriptionLabor",
    "mfgWarrantyDescriptionParts",
    "manufacturerWarrantyType",
    "numberOfLithiumIonCells",
    "numberOfLithiumMetalCells",
    "powerSource",
    "targetGender",
    "warnings",
    "warrantyDescription"
})
@XmlRootElement(name = "MusicalInstruments")
public class MusicalInstruments {

    @XmlElement(name = "Rebate")
    protected List<RebateType> rebate;
    @XmlElement(name = "ProductType", required = true)
    protected MusicalInstruments.ProductType productType;
    @XmlElement(name = "BatteryAverageLife")
    protected BigDecimal batteryAverageLife;
    @XmlElement(name = "BatteryAverageLifeStandby")
    protected BigDecimal batteryAverageLifeStandby;
    @XmlElement(name = "BatteryChargeTime")
    protected BigDecimal batteryChargeTime;
    @XmlElement(name = "BatteryTypeLithiumIon")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger batteryTypeLithiumIon;
    @XmlElement(name = "BatteryTypeLithiumMetal")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger batteryTypeLithiumMetal;
    @XmlElement(name = "CountryOfOrigin")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String countryOfOrigin;
    @XmlElement(name = "LithiumBatteryEnergyContent")
    protected BigDecimal lithiumBatteryEnergyContent;
    @XmlElement(name = "LithiumBatteryPackaging")
    protected String lithiumBatteryPackaging;
    @XmlElement(name = "LithiumBatteryVoltage")
    protected BigDecimal lithiumBatteryVoltage;
    @XmlElement(name = "LithiumBatteryWeight")
    protected BigDecimal lithiumBatteryWeight;
    @XmlElement(name = "MfgWarrantyDescriptionLabor")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String mfgWarrantyDescriptionLabor;
    @XmlElement(name = "MfgWarrantyDescriptionParts")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String mfgWarrantyDescriptionParts;
    @XmlElement(name = "ManufacturerWarrantyType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String manufacturerWarrantyType;
    @XmlElement(name = "NumberOfLithiumIonCells")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfLithiumIonCells;
    @XmlElement(name = "NumberOfLithiumMetalCells")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfLithiumMetalCells;
    @XmlElement(name = "PowerSource")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String powerSource;
    @XmlElement(name = "TargetGender")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String targetGender;
    @XmlElement(name = "Warnings")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String warnings;
    @XmlElement(name = "WarrantyDescription")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String warrantyDescription;

    /**
     * Gets the value of the rebate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rebate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRebate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RebateType }
     * 
     * 
     */
    public List<RebateType> getRebate() {
        if (rebate == null) {
            rebate = new ArrayList<RebateType>();
        }
        return this.rebate;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link MusicalInstruments.ProductType }
     *     
     */
    public MusicalInstruments.ProductType getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MusicalInstruments.ProductType }
     *     
     */
    public void setProductType(MusicalInstruments.ProductType value) {
        this.productType = value;
    }

    /**
     * Gets the value of the batteryAverageLife property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBatteryAverageLife() {
        return batteryAverageLife;
    }

    /**
     * Sets the value of the batteryAverageLife property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBatteryAverageLife(BigDecimal value) {
        this.batteryAverageLife = value;
    }

    /**
     * Gets the value of the batteryAverageLifeStandby property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBatteryAverageLifeStandby() {
        return batteryAverageLifeStandby;
    }

    /**
     * Sets the value of the batteryAverageLifeStandby property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBatteryAverageLifeStandby(BigDecimal value) {
        this.batteryAverageLifeStandby = value;
    }

    /**
     * Gets the value of the batteryChargeTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBatteryChargeTime() {
        return batteryChargeTime;
    }

    /**
     * Sets the value of the batteryChargeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBatteryChargeTime(BigDecimal value) {
        this.batteryChargeTime = value;
    }

    /**
     * Gets the value of the batteryTypeLithiumIon property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBatteryTypeLithiumIon() {
        return batteryTypeLithiumIon;
    }

    /**
     * Sets the value of the batteryTypeLithiumIon property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBatteryTypeLithiumIon(BigInteger value) {
        this.batteryTypeLithiumIon = value;
    }

    /**
     * Gets the value of the batteryTypeLithiumMetal property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBatteryTypeLithiumMetal() {
        return batteryTypeLithiumMetal;
    }

    /**
     * Sets the value of the batteryTypeLithiumMetal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBatteryTypeLithiumMetal(BigInteger value) {
        this.batteryTypeLithiumMetal = value;
    }

    /**
     * Gets the value of the countryOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfOrigin() {
        return countryOfOrigin;
    }

    /**
     * Sets the value of the countryOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfOrigin(String value) {
        this.countryOfOrigin = value;
    }

    /**
     * Gets the value of the lithiumBatteryEnergyContent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLithiumBatteryEnergyContent() {
        return lithiumBatteryEnergyContent;
    }

    /**
     * Sets the value of the lithiumBatteryEnergyContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLithiumBatteryEnergyContent(BigDecimal value) {
        this.lithiumBatteryEnergyContent = value;
    }

    /**
     * Gets the value of the lithiumBatteryPackaging property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLithiumBatteryPackaging() {
        return lithiumBatteryPackaging;
    }

    /**
     * Sets the value of the lithiumBatteryPackaging property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLithiumBatteryPackaging(String value) {
        this.lithiumBatteryPackaging = value;
    }

    /**
     * Gets the value of the lithiumBatteryVoltage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLithiumBatteryVoltage() {
        return lithiumBatteryVoltage;
    }

    /**
     * Sets the value of the lithiumBatteryVoltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLithiumBatteryVoltage(BigDecimal value) {
        this.lithiumBatteryVoltage = value;
    }

    /**
     * Gets the value of the lithiumBatteryWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLithiumBatteryWeight() {
        return lithiumBatteryWeight;
    }

    /**
     * Sets the value of the lithiumBatteryWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLithiumBatteryWeight(BigDecimal value) {
        this.lithiumBatteryWeight = value;
    }

    /**
     * Gets the value of the mfgWarrantyDescriptionLabor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMfgWarrantyDescriptionLabor() {
        return mfgWarrantyDescriptionLabor;
    }

    /**
     * Sets the value of the mfgWarrantyDescriptionLabor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMfgWarrantyDescriptionLabor(String value) {
        this.mfgWarrantyDescriptionLabor = value;
    }

    /**
     * Gets the value of the mfgWarrantyDescriptionParts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMfgWarrantyDescriptionParts() {
        return mfgWarrantyDescriptionParts;
    }

    /**
     * Sets the value of the mfgWarrantyDescriptionParts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMfgWarrantyDescriptionParts(String value) {
        this.mfgWarrantyDescriptionParts = value;
    }

    /**
     * Gets the value of the manufacturerWarrantyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturerWarrantyType() {
        return manufacturerWarrantyType;
    }

    /**
     * Sets the value of the manufacturerWarrantyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturerWarrantyType(String value) {
        this.manufacturerWarrantyType = value;
    }

    /**
     * Gets the value of the numberOfLithiumIonCells property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfLithiumIonCells() {
        return numberOfLithiumIonCells;
    }

    /**
     * Sets the value of the numberOfLithiumIonCells property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfLithiumIonCells(BigInteger value) {
        this.numberOfLithiumIonCells = value;
    }

    /**
     * Gets the value of the numberOfLithiumMetalCells property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfLithiumMetalCells() {
        return numberOfLithiumMetalCells;
    }

    /**
     * Sets the value of the numberOfLithiumMetalCells property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfLithiumMetalCells(BigInteger value) {
        this.numberOfLithiumMetalCells = value;
    }

    /**
     * Gets the value of the powerSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPowerSource() {
        return powerSource;
    }

    /**
     * Sets the value of the powerSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPowerSource(String value) {
        this.powerSource = value;
    }

    /**
     * Gets the value of the targetGender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetGender() {
        return targetGender;
    }

    /**
     * Sets the value of the targetGender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetGender(String value) {
        this.targetGender = value;
    }

    /**
     * Gets the value of the warnings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarnings() {
        return warnings;
    }

    /**
     * Sets the value of the warnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarnings(String value) {
        this.warnings = value;
    }

    /**
     * Gets the value of the warrantyDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarrantyDescription() {
        return warrantyDescription;
    }

    /**
     * Sets the value of the warrantyDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarrantyDescription(String value) {
        this.warrantyDescription = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element ref="{}BrassAndWoodwindInstruments"/&gt;
     *         &lt;element ref="{}Guitars"/&gt;
     *         &lt;element ref="{}InstrumentPartsAndAccessories"/&gt;
     *         &lt;element ref="{}KeyboardInstruments"/&gt;
     *         &lt;element ref="{}MiscWorldInstruments"/&gt;
     *         &lt;element ref="{}PercussionInstruments"/&gt;
     *         &lt;element ref="{}SoundAndRecordingEquipment"/&gt;
     *         &lt;element ref="{}StringedInstruments"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brassAndWoodwindInstruments",
        "guitars",
        "instrumentPartsAndAccessories",
        "keyboardInstruments",
        "miscWorldInstruments",
        "percussionInstruments",
        "soundAndRecordingEquipment",
        "stringedInstruments"
    })
    public static class ProductType {

        @XmlElement(name = "BrassAndWoodwindInstruments")
        protected BrassAndWoodwindInstruments brassAndWoodwindInstruments;
        @XmlElement(name = "Guitars")
        protected Guitars guitars;
        @XmlElement(name = "InstrumentPartsAndAccessories")
        protected InstrumentPartsAndAccessories instrumentPartsAndAccessories;
        @XmlElement(name = "KeyboardInstruments")
        protected KeyboardInstruments keyboardInstruments;
        @XmlElement(name = "MiscWorldInstruments")
        protected MiscWorldInstruments miscWorldInstruments;
        @XmlElement(name = "PercussionInstruments")
        protected PercussionInstruments percussionInstruments;
        @XmlElement(name = "SoundAndRecordingEquipment")
        protected SoundAndRecordingEquipment soundAndRecordingEquipment;
        @XmlElement(name = "StringedInstruments")
        protected StringedInstruments stringedInstruments;

        /**
         * Gets the value of the brassAndWoodwindInstruments property.
         * 
         * @return
         *     possible object is
         *     {@link BrassAndWoodwindInstruments }
         *     
         */
        public BrassAndWoodwindInstruments getBrassAndWoodwindInstruments() {
            return brassAndWoodwindInstruments;
        }

        /**
         * Sets the value of the brassAndWoodwindInstruments property.
         * 
         * @param value
         *     allowed object is
         *     {@link BrassAndWoodwindInstruments }
         *     
         */
        public void setBrassAndWoodwindInstruments(BrassAndWoodwindInstruments value) {
            this.brassAndWoodwindInstruments = value;
        }

        /**
         * Gets the value of the guitars property.
         * 
         * @return
         *     possible object is
         *     {@link Guitars }
         *     
         */
        public Guitars getGuitars() {
            return guitars;
        }

        /**
         * Sets the value of the guitars property.
         * 
         * @param value
         *     allowed object is
         *     {@link Guitars }
         *     
         */
        public void setGuitars(Guitars value) {
            this.guitars = value;
        }

        /**
         * Gets the value of the instrumentPartsAndAccessories property.
         * 
         * @return
         *     possible object is
         *     {@link InstrumentPartsAndAccessories }
         *     
         */
        public InstrumentPartsAndAccessories getInstrumentPartsAndAccessories() {
            return instrumentPartsAndAccessories;
        }

        /**
         * Sets the value of the instrumentPartsAndAccessories property.
         * 
         * @param value
         *     allowed object is
         *     {@link InstrumentPartsAndAccessories }
         *     
         */
        public void setInstrumentPartsAndAccessories(InstrumentPartsAndAccessories value) {
            this.instrumentPartsAndAccessories = value;
        }

        /**
         * Gets the value of the keyboardInstruments property.
         * 
         * @return
         *     possible object is
         *     {@link KeyboardInstruments }
         *     
         */
        public KeyboardInstruments getKeyboardInstruments() {
            return keyboardInstruments;
        }

        /**
         * Sets the value of the keyboardInstruments property.
         * 
         * @param value
         *     allowed object is
         *     {@link KeyboardInstruments }
         *     
         */
        public void setKeyboardInstruments(KeyboardInstruments value) {
            this.keyboardInstruments = value;
        }

        /**
         * Gets the value of the miscWorldInstruments property.
         * 
         * @return
         *     possible object is
         *     {@link MiscWorldInstruments }
         *     
         */
        public MiscWorldInstruments getMiscWorldInstruments() {
            return miscWorldInstruments;
        }

        /**
         * Sets the value of the miscWorldInstruments property.
         * 
         * @param value
         *     allowed object is
         *     {@link MiscWorldInstruments }
         *     
         */
        public void setMiscWorldInstruments(MiscWorldInstruments value) {
            this.miscWorldInstruments = value;
        }

        /**
         * Gets the value of the percussionInstruments property.
         * 
         * @return
         *     possible object is
         *     {@link PercussionInstruments }
         *     
         */
        public PercussionInstruments getPercussionInstruments() {
            return percussionInstruments;
        }

        /**
         * Sets the value of the percussionInstruments property.
         * 
         * @param value
         *     allowed object is
         *     {@link PercussionInstruments }
         *     
         */
        public void setPercussionInstruments(PercussionInstruments value) {
            this.percussionInstruments = value;
        }

        /**
         * Gets the value of the soundAndRecordingEquipment property.
         * 
         * @return
         *     possible object is
         *     {@link SoundAndRecordingEquipment }
         *     
         */
        public SoundAndRecordingEquipment getSoundAndRecordingEquipment() {
            return soundAndRecordingEquipment;
        }

        /**
         * Sets the value of the soundAndRecordingEquipment property.
         * 
         * @param value
         *     allowed object is
         *     {@link SoundAndRecordingEquipment }
         *     
         */
        public void setSoundAndRecordingEquipment(SoundAndRecordingEquipment value) {
            this.soundAndRecordingEquipment = value;
        }

        /**
         * Gets the value of the stringedInstruments property.
         * 
         * @return
         *     possible object is
         *     {@link StringedInstruments }
         *     
         */
        public StringedInstruments getStringedInstruments() {
            return stringedInstruments;
        }

        /**
         * Sets the value of the stringedInstruments property.
         * 
         * @param value
         *     allowed object is
         *     {@link StringedInstruments }
         *     
         */
        public void setStringedInstruments(StringedInstruments value) {
            this.stringedInstruments = value;
        }

    }

}
