//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 11:40:51 PM CST 
//


package com.kindminds.drs.mws.xml;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Battery" minOccurs="0"/&gt;
 *         &lt;element name="CanShipInOriginalContainer" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ColorMap" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="EngineType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="IdentityPackageType" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}StringNotNull"&gt;
 *               &lt;enumeration value="bulk"/&gt;
 *               &lt;enumeration value="frustration_free"/&gt;
 *               &lt;enumeration value="traditional"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IsStainResistant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="HoseLength" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="Material" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfSets" type="{}TenDigitInteger" minOccurs="0"/&gt;
 *         &lt;element name="PoolType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="PowerSource" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Theme" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="VariationData" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="VariationTheme" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Size"/&gt;
 *                         &lt;enumeration value="Color"/&gt;
 *                         &lt;enumeration value="Size-Color"/&gt;
 *                         &lt;enumeration value="ItemDisplayLength-ItemDisplayWidth"/&gt;
 *                         &lt;enumeration value="ItemDisplayLength-MaterialType"/&gt;
 *                         &lt;enumeration value="ItemDisplayLength-SizeName"/&gt;
 *                         &lt;enumeration value="ItemDisplayLength-ColorName"/&gt;
 *                         &lt;enumeration value="ItemDisplayLength-ItemDisplayHeight"/&gt;
 *                         &lt;enumeration value="ItemDisplayWidth-MaterialType"/&gt;
 *                         &lt;enumeration value="ItemDisplayWidth-SizeName"/&gt;
 *                         &lt;enumeration value="ItemDisplayWidth-ColorName"/&gt;
 *                         &lt;enumeration value="ItemDisplayWidth-ItemDisplayHeight"/&gt;
 *                         &lt;enumeration value="ItemPackageQuantity-MaterialType"/&gt;
 *                         &lt;enumeration value="ItemPackageQuantity-SizeName"/&gt;
 *                         &lt;enumeration value="ItemPackageQuantity-ColorName"/&gt;
 *                         &lt;enumeration value="ItemPackageQuantity-ItemDisplayHeight"/&gt;
 *                         &lt;enumeration value="ItemDisplayWeight-ItemPackageQuantity"/&gt;
 *                         &lt;enumeration value="ItemDisplayWeight-MaterialType"/&gt;
 *                         &lt;enumeration value="ItemDisplayWeight-SizeName"/&gt;
 *                         &lt;enumeration value="ItemDisplayWeight-ColorName"/&gt;
 *                         &lt;enumeration value="ItemDisplayWeight-ItemDisplayHeight"/&gt;
 *                         &lt;enumeration value="MaterialType-ItemDisplayLength"/&gt;
 *                         &lt;enumeration value="MaterialType-ItemDisplayWidth"/&gt;
 *                         &lt;enumeration value="MaterialType-SizeName"/&gt;
 *                         &lt;enumeration value="MaterialType-ColorName"/&gt;
 *                         &lt;enumeration value="MaterialType-ItemDisplayHeight"/&gt;
 *                         &lt;enumeration value="SizeName-ItemDisplayLength"/&gt;
 *                         &lt;enumeration value="SizeName-ItemDisplayWidth"/&gt;
 *                         &lt;enumeration value="SizeName-ItemDisplayWeight"/&gt;
 *                         &lt;enumeration value="SizeName-MaterialType"/&gt;
 *                         &lt;enumeration value="SizeName-ColorName"/&gt;
 *                         &lt;enumeration value="SizeName-ItemDisplayHeight"/&gt;
 *                         &lt;enumeration value="ColorName-ItemDisplayLength"/&gt;
 *                         &lt;enumeration value="ColorName-ItemDisplayWidth"/&gt;
 *                         &lt;enumeration value="ColorName-ItemPackageQuantity"/&gt;
 *                         &lt;enumeration value="ColorName-ItemDisplayWeight"/&gt;
 *                         &lt;enumeration value="ColorName-MaterialType"/&gt;
 *                         &lt;enumeration value="ColorName-SizeName"/&gt;
 *                         &lt;enumeration value="ColorName-ItemDisplayHeight"/&gt;
 *                         &lt;enumeration value="ItemDisplayHeight"/&gt;
 *                         &lt;enumeration value="MaterialType"/&gt;
 *                         &lt;enumeration value="ItemDisplayWeight"/&gt;
 *                         &lt;enumeration value="ItemDisplayLength"/&gt;
 *                         &lt;enumeration value="ItemPackageQuantity"/&gt;
 *                         &lt;enumeration value="ItemDisplayLength-PatternName"/&gt;
 *                         &lt;enumeration value="ItemDisplayLength-StyleName"/&gt;
 *                         &lt;enumeration value="ItemDisplayWidth-PatternName"/&gt;
 *                         &lt;enumeration value="ItemDisplayWidth-StyleName"/&gt;
 *                         &lt;enumeration value="Occasion-PatternName"/&gt;
 *                         &lt;enumeration value="Occasion-ItemPackageQuantity"/&gt;
 *                         &lt;enumeration value="Occasion-MaterialType"/&gt;
 *                         &lt;enumeration value="Occasion-StyleName"/&gt;
 *                         &lt;enumeration value="Occasion-SizeName"/&gt;
 *                         &lt;enumeration value="Occasion-ColorName"/&gt;
 *                         &lt;enumeration value="Occasion-ItemDisplayHeight"/&gt;
 *                         &lt;enumeration value="PatternName-ItemDisplayLength"/&gt;
 *                         &lt;enumeration value="PatternName-ItemDisplayWidth"/&gt;
 *                         &lt;enumeration value="PatternName-Occasion"/&gt;
 *                         &lt;enumeration value="PatternName-MaterialType"/&gt;
 *                         &lt;enumeration value="PatternName-StyleName"/&gt;
 *                         &lt;enumeration value="PatternName-SizeName"/&gt;
 *                         &lt;enumeration value="PatternName-ColorName"/&gt;
 *                         &lt;enumeration value="PatternName-ItemDisplayHeight"/&gt;
 *                         &lt;enumeration value="MatteStyle-MaterialType"/&gt;
 *                         &lt;enumeration value="MatteStyle-StyleName"/&gt;
 *                         &lt;enumeration value="MatteStyle-SizeName"/&gt;
 *                         &lt;enumeration value="MatteStyle-ColorName"/&gt;
 *                         &lt;enumeration value="ItemPackageQuantity-Occasion"/&gt;
 *                         &lt;enumeration value="ItemPackageQuantity-StyleName"/&gt;
 *                         &lt;enumeration value="ItemDisplayWeight-StyleName"/&gt;
 *                         &lt;enumeration value="MaterialType-PatternName"/&gt;
 *                         &lt;enumeration value="MaterialType-MatteStyle"/&gt;
 *                         &lt;enumeration value="MaterialType-StyleName"/&gt;
 *                         &lt;enumeration value="StyleName-ItemDisplayLength"/&gt;
 *                         &lt;enumeration value="StyleName-ItemDisplayWidth"/&gt;
 *                         &lt;enumeration value="StyleName-Occasion"/&gt;
 *                         &lt;enumeration value="StyleName-PatternName"/&gt;
 *                         &lt;enumeration value="StyleName-ItemDisplayWeight"/&gt;
 *                         &lt;enumeration value="StyleName-MaterialType"/&gt;
 *                         &lt;enumeration value="StyleName-SizeName"/&gt;
 *                         &lt;enumeration value="StyleName-ColorName"/&gt;
 *                         &lt;enumeration value="SizeName-Occasion"/&gt;
 *                         &lt;enumeration value="SizeName-PatternName"/&gt;
 *                         &lt;enumeration value="SizeName-MatteStyle"/&gt;
 *                         &lt;enumeration value="SizeName-StyleName"/&gt;
 *                         &lt;enumeration value="ColorName-Occasion"/&gt;
 *                         &lt;enumeration value="ColorName-PatternName"/&gt;
 *                         &lt;enumeration value="ColorName-MatteStyle"/&gt;
 *                         &lt;enumeration value="ColorName-StyleName"/&gt;
 *                         &lt;enumeration value="MatteStyle"/&gt;
 *                         &lt;enumeration value="PatternName"/&gt;
 *                         &lt;enumeration value="Occasion"/&gt;
 *                         &lt;enumeration value="StyleName"/&gt;
 *                         &lt;enumeration value="ScentName"/&gt;
 *                         &lt;enumeration value="CustomerPackageType"/&gt;
 *                         &lt;enumeration value="ColorName-CustomerPackageType"/&gt;
 *                         &lt;enumeration value="SizeName-CustomerPackageType"/&gt;
 *                         &lt;enumeration value="SizeName-ColorName-CustomerPackageType"/&gt;
 *                         &lt;enumeration value="StyleName-CustomerPackageType"/&gt;
 *                         &lt;enumeration value="SizeName-StyleName-CustomerPackageType"/&gt;
 *                         &lt;enumeration value="MetalType"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Size" type="{}StringNotNull" minOccurs="0"/&gt;
 *                   &lt;element name="Color" type="{}StringNotNull" minOccurs="0"/&gt;
 *                   &lt;element name="StyleName" type="{}StringNotNull" minOccurs="0"/&gt;
 *                   &lt;element name="ScentName" type="{}StringNotNull" minOccurs="0"/&gt;
 *                   &lt;element name="CustomerPackageType" type="{}StringNotNull" minOccurs="0"/&gt;
 *                   &lt;element name="MetalType" type="{}StringNotNull" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Wattage" type="{}WattageDimensionOptionalUnit" minOccurs="0"/&gt;
 *         &lt;element name="Voltage" type="{}PositiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="ThreadCount" type="{}PositiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="ItemForm" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="CuttingLengthDerived" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="CutType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="OuterMaterialType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="WarrantyDescription" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="UnitCount" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;decimal"&gt;
 *                 &lt;attribute name="unitOfMeasure" use="required" type="{}StringNotNull" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Shape" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="InstallationType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Efficiency" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="OutputCapacity" type="{}VolumeRateDimension" minOccurs="0"/&gt;
 *         &lt;element name="BatteryWeight" type="{}WeightDimension" minOccurs="0"/&gt;
 *         &lt;element name="CuttingWidth" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="OccasionType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="CustomerRestrictionType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="BaseMaterialType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="BaseType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="FastenerType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="HeatingMethod" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="LiftingMechanism" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfLevels" type="{}PositiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfLightSources" type="{}PositiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="SeatingCapacity" type="{}PositiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="TopMaterialType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="BreedRecommendation" type="{}HundredFiftyStringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="ClosureType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Codabar" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="CompatibleDevices" type="{}StringNotNull" maxOccurs="10" minOccurs="0"/&gt;
 *         &lt;element name="ConnectivityProtocol" type="{}StringNotNull" maxOccurs="5" minOccurs="0"/&gt;
 *         &lt;element name="ControlMethod" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="voice"/&gt;
 *               &lt;enumeration value="application"/&gt;
 *               &lt;enumeration value="touch"/&gt;
 *               &lt;enumeration value="remote"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ControllerType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Directions" type="{}LongStringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="EuEnergyLabelEfficiencyClass" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="a"/&gt;
 *               &lt;enumeration value="b"/&gt;
 *               &lt;enumeration value="c"/&gt;
 *               &lt;enumeration value="d"/&gt;
 *               &lt;enumeration value="e"/&gt;
 *               &lt;enumeration value="f"/&gt;
 *               &lt;enumeration value="g"/&gt;
 *               &lt;enumeration value="a_plus_plus_plus"/&gt;
 *               &lt;enumeration value="a_plus_plus"/&gt;
 *               &lt;enumeration value="a_plus"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FillMaterialType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="ImporterContactInformation" type="{}String" minOccurs="0"/&gt;
 *         &lt;element name="ProductFeature" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Ingredients" type="{}SuperLongStringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="InsideDepth" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="IsAssemblyRequired" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="true"/&gt;
 *               &lt;enumeration value="false"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IsFragile" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsWhiteGloveRequired" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="true"/&gt;
 *               &lt;enumeration value="false"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ItemDiameter" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="ItemTypeName" type="{}String" minOccurs="0"/&gt;
 *         &lt;element name="LegalComplianceCertificationDateOfIssue" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="LegalComplianceCertificationExpirationDate" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="LegalComplianceCertificationRegulatoryOrganizationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ManufacturerContactInformation" type="{}String" minOccurs="0"/&gt;
 *         &lt;element name="MaterialComposition" type="{}String" minOccurs="0"/&gt;
 *         &lt;element name="MaximumWeightRecommendation" type="{}PositiveWeightDimension" minOccurs="0"/&gt;
 *         &lt;element name="MaximumAgeRecommendation" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="MinimumAgeRecommendation" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="ModelNumber" type="{}FortyStringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="ModelName" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="ArtistBiography" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="PackerContactInformation" type="{}String" minOccurs="0"/&gt;
 *         &lt;element name="PlatinumKeywords" type="{}StringNotNull" maxOccurs="20" minOccurs="0"/&gt;
 *         &lt;element name="PowerPlugType" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="type_d_3pin_in"/&gt;
 *               &lt;enumeration value="type_m_3pin_za"/&gt;
 *               &lt;enumeration value="type_g_3pin_uk"/&gt;
 *               &lt;enumeration value="type_n_3pin_br"/&gt;
 *               &lt;enumeration value="type_k_3pin_dk"/&gt;
 *               &lt;enumeration value="no_plug"/&gt;
 *               &lt;enumeration value="type_e_2pin_fr"/&gt;
 *               &lt;enumeration value="type_i_3pin_au"/&gt;
 *               &lt;enumeration value="type_a_2pin_jp"/&gt;
 *               &lt;enumeration value="type_h_3pin_il"/&gt;
 *               &lt;enumeration value="type_c_2pin_eu"/&gt;
 *               &lt;enumeration value="type_ef_2pin_eu"/&gt;
 *               &lt;enumeration value="type_b_3pin_na"/&gt;
 *               &lt;enumeration value="type_j_3pin_ch"/&gt;
 *               &lt;enumeration value="type_l_3pin_it"/&gt;
 *               &lt;enumeration value="type_f_2pin_de"/&gt;
 *               &lt;enumeration value="type_b_3pin_jp"/&gt;
 *               &lt;enumeration value="type_a_2pin_na"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ShaftType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="SpecificationMet" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="StorageInstructions" type="{}HundredString" minOccurs="0"/&gt;
 *         &lt;element name="TargetAudienceBase" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="TunerTechnology" type="{}StringNotNull" maxOccurs="5" minOccurs="0"/&gt;
 *         &lt;element name="PPUCountType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="WeeeTaxValue" type="{}CurencyDimension" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "battery",
    "canShipInOriginalContainer",
    "colorMap",
    "engineType",
    "identityPackageType",
    "isStainResistant",
    "hoseLength",
    "material",
    "numberOfSets",
    "poolType",
    "powerSource",
    "theme",
    "variationData",
    "wattage",
    "voltage",
    "threadCount",
    "itemForm",
    "cuttingLengthDerived",
    "cutType",
    "outerMaterialType",
    "warrantyDescription",
    "unitCount",
    "shape",
    "installationType",
    "efficiency",
    "outputCapacity",
    "batteryWeight",
    "cuttingWidth",
    "occasionType",
    "customerRestrictionType",
    "baseMaterialType",
    "baseType",
    "fastenerType",
    "heatingMethod",
    "liftingMechanism",
    "numberOfLevels",
    "numberOfLightSources",
    "seatingCapacity",
    "topMaterialType",
    "breedRecommendation",
    "closureType",
    "codabar",
    "compatibleDevices",
    "connectivityProtocol",
    "controlMethod",
    "controllerType",
    "directions",
    "euEnergyLabelEfficiencyClass",
    "fillMaterialType",
    "importerContactInformation",
    "productFeature",
    "ingredients",
    "insideDepth",
    "isAssemblyRequired",
    "isFragile",
    "isWhiteGloveRequired",
    "itemDiameter",
    "itemTypeName",
    "legalComplianceCertificationDateOfIssue",
    "legalComplianceCertificationExpirationDate",
    "legalComplianceCertificationRegulatoryOrganizationName",
    "manufacturerContactInformation",
    "materialComposition",
    "maximumWeightRecommendation",
    "maximumAgeRecommendation",
    "minimumAgeRecommendation",
    "modelNumber",
    "modelName",
    "artistBiography",
    "packerContactInformation",
    "platinumKeywords",
    "powerPlugType",
    "shaftType",
    "specificationMet",
    "storageInstructions",
    "targetAudienceBase",
    "tunerTechnology",
    "ppuCountType",
    "weeeTaxValue"
})
@XmlRootElement(name = "OutdoorLiving")
public class OutdoorLiving {

    @XmlElement(name = "Battery")
    protected Battery battery;
    @XmlElement(name = "CanShipInOriginalContainer")
    protected Boolean canShipInOriginalContainer;
    @XmlElement(name = "ColorMap")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String colorMap;
    @XmlElement(name = "EngineType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String engineType;
    @XmlElement(name = "IdentityPackageType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String identityPackageType;
    @XmlElement(name = "IsStainResistant")
    protected Boolean isStainResistant;
    @XmlElement(name = "HoseLength")
    protected LengthDimension hoseLength;
    @XmlElement(name = "Material")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String material;
    @XmlElement(name = "NumberOfSets")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfSets;
    @XmlElement(name = "PoolType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String poolType;
    @XmlElement(name = "PowerSource")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String powerSource;
    @XmlElement(name = "Theme")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String theme;
    @XmlElement(name = "VariationData")
    protected OutdoorLiving.VariationData variationData;
    @XmlElement(name = "Wattage")
    protected WattageDimensionOptionalUnit wattage;
    @XmlElement(name = "Voltage")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger voltage;
    @XmlElement(name = "ThreadCount")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger threadCount;
    @XmlElement(name = "ItemForm")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String itemForm;
    @XmlElement(name = "CuttingLengthDerived")
    protected LengthDimension cuttingLengthDerived;
    @XmlElement(name = "CutType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String cutType;
    @XmlElement(name = "OuterMaterialType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String outerMaterialType;
    @XmlElement(name = "WarrantyDescription")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String warrantyDescription;
    @XmlElement(name = "UnitCount")
    protected OutdoorLiving.UnitCount unitCount;
    @XmlElement(name = "Shape")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String shape;
    @XmlElement(name = "InstallationType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String installationType;
    @XmlElement(name = "Efficiency")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String efficiency;
    @XmlElement(name = "OutputCapacity")
    protected VolumeRateDimension outputCapacity;
    @XmlElement(name = "BatteryWeight")
    protected WeightDimension batteryWeight;
    @XmlElement(name = "CuttingWidth")
    protected LengthDimension cuttingWidth;
    @XmlElement(name = "OccasionType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String occasionType;
    @XmlElement(name = "CustomerRestrictionType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String customerRestrictionType;
    @XmlElement(name = "BaseMaterialType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String baseMaterialType;
    @XmlElement(name = "BaseType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String baseType;
    @XmlElement(name = "FastenerType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String fastenerType;
    @XmlElement(name = "HeatingMethod")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String heatingMethod;
    @XmlElement(name = "LiftingMechanism")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String liftingMechanism;
    @XmlElement(name = "NumberOfLevels")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfLevels;
    @XmlElement(name = "NumberOfLightSources")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfLightSources;
    @XmlElement(name = "SeatingCapacity")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger seatingCapacity;
    @XmlElement(name = "TopMaterialType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String topMaterialType;
    @XmlElement(name = "BreedRecommendation")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String breedRecommendation;
    @XmlElement(name = "ClosureType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String closureType;
    @XmlElement(name = "Codabar")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String codabar;
    @XmlElement(name = "CompatibleDevices")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected List<String> compatibleDevices;
    @XmlElement(name = "ConnectivityProtocol")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected List<String> connectivityProtocol;
    @XmlElement(name = "ControlMethod")
    protected String controlMethod;
    @XmlElement(name = "ControllerType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String controllerType;
    @XmlElement(name = "Directions")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String directions;
    @XmlElement(name = "EuEnergyLabelEfficiencyClass")
    protected String euEnergyLabelEfficiencyClass;
    @XmlElement(name = "FillMaterialType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String fillMaterialType;
    @XmlElement(name = "ImporterContactInformation")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String importerContactInformation;
    @XmlElement(name = "ProductFeature")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String productFeature;
    @XmlElement(name = "Ingredients")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String ingredients;
    @XmlElement(name = "InsideDepth")
    protected LengthDimension insideDepth;
    @XmlElement(name = "IsAssemblyRequired")
    protected String isAssemblyRequired;
    @XmlElement(name = "IsFragile")
    protected Boolean isFragile;
    @XmlElement(name = "IsWhiteGloveRequired")
    protected String isWhiteGloveRequired;
    @XmlElement(name = "ItemDiameter")
    protected LengthDimension itemDiameter;
    @XmlElement(name = "ItemTypeName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String itemTypeName;
    @XmlElement(name = "LegalComplianceCertificationDateOfIssue")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String legalComplianceCertificationDateOfIssue;
    @XmlElement(name = "LegalComplianceCertificationExpirationDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String legalComplianceCertificationExpirationDate;
    @XmlElement(name = "LegalComplianceCertificationRegulatoryOrganizationName")
    protected String legalComplianceCertificationRegulatoryOrganizationName;
    @XmlElement(name = "ManufacturerContactInformation")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String manufacturerContactInformation;
    @XmlElement(name = "MaterialComposition")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String materialComposition;
    @XmlElement(name = "MaximumWeightRecommendation")
    protected PositiveWeightDimension maximumWeightRecommendation;
    @XmlElement(name = "MaximumAgeRecommendation")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maximumAgeRecommendation;
    @XmlElement(name = "MinimumAgeRecommendation")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger minimumAgeRecommendation;
    @XmlElement(name = "ModelNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String modelNumber;
    @XmlElement(name = "ModelName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String modelName;
    @XmlElement(name = "ArtistBiography")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String artistBiography;
    @XmlElement(name = "PackerContactInformation")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String packerContactInformation;
    @XmlElement(name = "PlatinumKeywords")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected List<String> platinumKeywords;
    @XmlElement(name = "PowerPlugType")
    protected String powerPlugType;
    @XmlElement(name = "ShaftType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String shaftType;
    @XmlElement(name = "SpecificationMet")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String specificationMet;
    @XmlElement(name = "StorageInstructions")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String storageInstructions;
    @XmlElement(name = "TargetAudienceBase")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String targetAudienceBase;
    @XmlElement(name = "TunerTechnology")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected List<String> tunerTechnology;
    @XmlElement(name = "PPUCountType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String ppuCountType;
    @XmlElement(name = "WeeeTaxValue")
    protected CurencyDimension weeeTaxValue;

    /**
     * Gets the value of the battery property.
     * 
     * @return
     *     possible object is
     *     {@link Battery }
     *     
     */
    public Battery getBattery() {
        return battery;
    }

    /**
     * Sets the value of the battery property.
     * 
     * @param value
     *     allowed object is
     *     {@link Battery }
     *     
     */
    public void setBattery(Battery value) {
        this.battery = value;
    }

    /**
     * Gets the value of the canShipInOriginalContainer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCanShipInOriginalContainer() {
        return canShipInOriginalContainer;
    }

    /**
     * Sets the value of the canShipInOriginalContainer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanShipInOriginalContainer(Boolean value) {
        this.canShipInOriginalContainer = value;
    }

    /**
     * Gets the value of the colorMap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorMap() {
        return colorMap;
    }

    /**
     * Sets the value of the colorMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorMap(String value) {
        this.colorMap = value;
    }

    /**
     * Gets the value of the engineType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineType() {
        return engineType;
    }

    /**
     * Sets the value of the engineType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineType(String value) {
        this.engineType = value;
    }

    /**
     * Gets the value of the identityPackageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentityPackageType() {
        return identityPackageType;
    }

    /**
     * Sets the value of the identityPackageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentityPackageType(String value) {
        this.identityPackageType = value;
    }

    /**
     * Gets the value of the isStainResistant property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsStainResistant() {
        return isStainResistant;
    }

    /**
     * Sets the value of the isStainResistant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsStainResistant(Boolean value) {
        this.isStainResistant = value;
    }

    /**
     * Gets the value of the hoseLength property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getHoseLength() {
        return hoseLength;
    }

    /**
     * Sets the value of the hoseLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setHoseLength(LengthDimension value) {
        this.hoseLength = value;
    }

    /**
     * Gets the value of the material property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterial() {
        return material;
    }

    /**
     * Sets the value of the material property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterial(String value) {
        this.material = value;
    }

    /**
     * Gets the value of the numberOfSets property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfSets() {
        return numberOfSets;
    }

    /**
     * Sets the value of the numberOfSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfSets(BigInteger value) {
        this.numberOfSets = value;
    }

    /**
     * Gets the value of the poolType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoolType() {
        return poolType;
    }

    /**
     * Sets the value of the poolType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoolType(String value) {
        this.poolType = value;
    }

    /**
     * Gets the value of the powerSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPowerSource() {
        return powerSource;
    }

    /**
     * Sets the value of the powerSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPowerSource(String value) {
        this.powerSource = value;
    }

    /**
     * Gets the value of the theme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTheme() {
        return theme;
    }

    /**
     * Sets the value of the theme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTheme(String value) {
        this.theme = value;
    }

    /**
     * Gets the value of the variationData property.
     * 
     * @return
     *     possible object is
     *     {@link OutdoorLiving.VariationData }
     *     
     */
    public OutdoorLiving.VariationData getVariationData() {
        return variationData;
    }

    /**
     * Sets the value of the variationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutdoorLiving.VariationData }
     *     
     */
    public void setVariationData(OutdoorLiving.VariationData value) {
        this.variationData = value;
    }

    /**
     * Gets the value of the wattage property.
     * 
     * @return
     *     possible object is
     *     {@link WattageDimensionOptionalUnit }
     *     
     */
    public WattageDimensionOptionalUnit getWattage() {
        return wattage;
    }

    /**
     * Sets the value of the wattage property.
     * 
     * @param value
     *     allowed object is
     *     {@link WattageDimensionOptionalUnit }
     *     
     */
    public void setWattage(WattageDimensionOptionalUnit value) {
        this.wattage = value;
    }

    /**
     * Gets the value of the voltage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVoltage() {
        return voltage;
    }

    /**
     * Sets the value of the voltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVoltage(BigInteger value) {
        this.voltage = value;
    }

    /**
     * Gets the value of the threadCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getThreadCount() {
        return threadCount;
    }

    /**
     * Sets the value of the threadCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setThreadCount(BigInteger value) {
        this.threadCount = value;
    }

    /**
     * Gets the value of the itemForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemForm() {
        return itemForm;
    }

    /**
     * Sets the value of the itemForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemForm(String value) {
        this.itemForm = value;
    }

    /**
     * Gets the value of the cuttingLengthDerived property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getCuttingLengthDerived() {
        return cuttingLengthDerived;
    }

    /**
     * Sets the value of the cuttingLengthDerived property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setCuttingLengthDerived(LengthDimension value) {
        this.cuttingLengthDerived = value;
    }

    /**
     * Gets the value of the cutType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCutType() {
        return cutType;
    }

    /**
     * Sets the value of the cutType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCutType(String value) {
        this.cutType = value;
    }

    /**
     * Gets the value of the outerMaterialType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOuterMaterialType() {
        return outerMaterialType;
    }

    /**
     * Sets the value of the outerMaterialType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOuterMaterialType(String value) {
        this.outerMaterialType = value;
    }

    /**
     * Gets the value of the warrantyDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarrantyDescription() {
        return warrantyDescription;
    }

    /**
     * Sets the value of the warrantyDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarrantyDescription(String value) {
        this.warrantyDescription = value;
    }

    /**
     * Gets the value of the unitCount property.
     * 
     * @return
     *     possible object is
     *     {@link OutdoorLiving.UnitCount }
     *     
     */
    public OutdoorLiving.UnitCount getUnitCount() {
        return unitCount;
    }

    /**
     * Sets the value of the unitCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutdoorLiving.UnitCount }
     *     
     */
    public void setUnitCount(OutdoorLiving.UnitCount value) {
        this.unitCount = value;
    }

    /**
     * Gets the value of the shape property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShape() {
        return shape;
    }

    /**
     * Sets the value of the shape property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShape(String value) {
        this.shape = value;
    }

    /**
     * Gets the value of the installationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstallationType() {
        return installationType;
    }

    /**
     * Sets the value of the installationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstallationType(String value) {
        this.installationType = value;
    }

    /**
     * Gets the value of the efficiency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEfficiency() {
        return efficiency;
    }

    /**
     * Sets the value of the efficiency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEfficiency(String value) {
        this.efficiency = value;
    }

    /**
     * Gets the value of the outputCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeRateDimension }
     *     
     */
    public VolumeRateDimension getOutputCapacity() {
        return outputCapacity;
    }

    /**
     * Sets the value of the outputCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeRateDimension }
     *     
     */
    public void setOutputCapacity(VolumeRateDimension value) {
        this.outputCapacity = value;
    }

    /**
     * Gets the value of the batteryWeight property.
     * 
     * @return
     *     possible object is
     *     {@link WeightDimension }
     *     
     */
    public WeightDimension getBatteryWeight() {
        return batteryWeight;
    }

    /**
     * Sets the value of the batteryWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightDimension }
     *     
     */
    public void setBatteryWeight(WeightDimension value) {
        this.batteryWeight = value;
    }

    /**
     * Gets the value of the cuttingWidth property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getCuttingWidth() {
        return cuttingWidth;
    }

    /**
     * Sets the value of the cuttingWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setCuttingWidth(LengthDimension value) {
        this.cuttingWidth = value;
    }

    /**
     * Gets the value of the occasionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccasionType() {
        return occasionType;
    }

    /**
     * Sets the value of the occasionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccasionType(String value) {
        this.occasionType = value;
    }

    /**
     * Gets the value of the customerRestrictionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerRestrictionType() {
        return customerRestrictionType;
    }

    /**
     * Sets the value of the customerRestrictionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerRestrictionType(String value) {
        this.customerRestrictionType = value;
    }

    /**
     * Gets the value of the baseMaterialType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseMaterialType() {
        return baseMaterialType;
    }

    /**
     * Sets the value of the baseMaterialType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseMaterialType(String value) {
        this.baseMaterialType = value;
    }

    /**
     * Gets the value of the baseType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseType() {
        return baseType;
    }

    /**
     * Sets the value of the baseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseType(String value) {
        this.baseType = value;
    }

    /**
     * Gets the value of the fastenerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFastenerType() {
        return fastenerType;
    }

    /**
     * Sets the value of the fastenerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFastenerType(String value) {
        this.fastenerType = value;
    }

    /**
     * Gets the value of the heatingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeatingMethod() {
        return heatingMethod;
    }

    /**
     * Sets the value of the heatingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeatingMethod(String value) {
        this.heatingMethod = value;
    }

    /**
     * Gets the value of the liftingMechanism property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLiftingMechanism() {
        return liftingMechanism;
    }

    /**
     * Sets the value of the liftingMechanism property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLiftingMechanism(String value) {
        this.liftingMechanism = value;
    }

    /**
     * Gets the value of the numberOfLevels property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfLevels() {
        return numberOfLevels;
    }

    /**
     * Sets the value of the numberOfLevels property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfLevels(BigInteger value) {
        this.numberOfLevels = value;
    }

    /**
     * Gets the value of the numberOfLightSources property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfLightSources() {
        return numberOfLightSources;
    }

    /**
     * Sets the value of the numberOfLightSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfLightSources(BigInteger value) {
        this.numberOfLightSources = value;
    }

    /**
     * Gets the value of the seatingCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeatingCapacity() {
        return seatingCapacity;
    }

    /**
     * Sets the value of the seatingCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeatingCapacity(BigInteger value) {
        this.seatingCapacity = value;
    }

    /**
     * Gets the value of the topMaterialType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopMaterialType() {
        return topMaterialType;
    }

    /**
     * Sets the value of the topMaterialType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopMaterialType(String value) {
        this.topMaterialType = value;
    }

    /**
     * Gets the value of the breedRecommendation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBreedRecommendation() {
        return breedRecommendation;
    }

    /**
     * Sets the value of the breedRecommendation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBreedRecommendation(String value) {
        this.breedRecommendation = value;
    }

    /**
     * Gets the value of the closureType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClosureType() {
        return closureType;
    }

    /**
     * Sets the value of the closureType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClosureType(String value) {
        this.closureType = value;
    }

    /**
     * Gets the value of the codabar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodabar() {
        return codabar;
    }

    /**
     * Sets the value of the codabar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodabar(String value) {
        this.codabar = value;
    }

    /**
     * Gets the value of the compatibleDevices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compatibleDevices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompatibleDevices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCompatibleDevices() {
        if (compatibleDevices == null) {
            compatibleDevices = new ArrayList<String>();
        }
        return this.compatibleDevices;
    }

    /**
     * Gets the value of the connectivityProtocol property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connectivityProtocol property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnectivityProtocol().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getConnectivityProtocol() {
        if (connectivityProtocol == null) {
            connectivityProtocol = new ArrayList<String>();
        }
        return this.connectivityProtocol;
    }

    /**
     * Gets the value of the controlMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlMethod() {
        return controlMethod;
    }

    /**
     * Sets the value of the controlMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlMethod(String value) {
        this.controlMethod = value;
    }

    /**
     * Gets the value of the controllerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControllerType() {
        return controllerType;
    }

    /**
     * Sets the value of the controllerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControllerType(String value) {
        this.controllerType = value;
    }

    /**
     * Gets the value of the directions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirections() {
        return directions;
    }

    /**
     * Sets the value of the directions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirections(String value) {
        this.directions = value;
    }

    /**
     * Gets the value of the euEnergyLabelEfficiencyClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEuEnergyLabelEfficiencyClass() {
        return euEnergyLabelEfficiencyClass;
    }

    /**
     * Sets the value of the euEnergyLabelEfficiencyClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEuEnergyLabelEfficiencyClass(String value) {
        this.euEnergyLabelEfficiencyClass = value;
    }

    /**
     * Gets the value of the fillMaterialType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillMaterialType() {
        return fillMaterialType;
    }

    /**
     * Sets the value of the fillMaterialType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillMaterialType(String value) {
        this.fillMaterialType = value;
    }

    /**
     * Gets the value of the importerContactInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporterContactInformation() {
        return importerContactInformation;
    }

    /**
     * Sets the value of the importerContactInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporterContactInformation(String value) {
        this.importerContactInformation = value;
    }

    /**
     * Gets the value of the productFeature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductFeature() {
        return productFeature;
    }

    /**
     * Sets the value of the productFeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductFeature(String value) {
        this.productFeature = value;
    }

    /**
     * Gets the value of the ingredients property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIngredients() {
        return ingredients;
    }

    /**
     * Sets the value of the ingredients property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIngredients(String value) {
        this.ingredients = value;
    }

    /**
     * Gets the value of the insideDepth property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getInsideDepth() {
        return insideDepth;
    }

    /**
     * Sets the value of the insideDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setInsideDepth(LengthDimension value) {
        this.insideDepth = value;
    }

    /**
     * Gets the value of the isAssemblyRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsAssemblyRequired() {
        return isAssemblyRequired;
    }

    /**
     * Sets the value of the isAssemblyRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsAssemblyRequired(String value) {
        this.isAssemblyRequired = value;
    }

    /**
     * Gets the value of the isFragile property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsFragile() {
        return isFragile;
    }

    /**
     * Sets the value of the isFragile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsFragile(Boolean value) {
        this.isFragile = value;
    }

    /**
     * Gets the value of the isWhiteGloveRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsWhiteGloveRequired() {
        return isWhiteGloveRequired;
    }

    /**
     * Sets the value of the isWhiteGloveRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsWhiteGloveRequired(String value) {
        this.isWhiteGloveRequired = value;
    }

    /**
     * Gets the value of the itemDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getItemDiameter() {
        return itemDiameter;
    }

    /**
     * Sets the value of the itemDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setItemDiameter(LengthDimension value) {
        this.itemDiameter = value;
    }

    /**
     * Gets the value of the itemTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemTypeName() {
        return itemTypeName;
    }

    /**
     * Sets the value of the itemTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemTypeName(String value) {
        this.itemTypeName = value;
    }

    /**
     * Gets the value of the legalComplianceCertificationDateOfIssue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalComplianceCertificationDateOfIssue() {
        return legalComplianceCertificationDateOfIssue;
    }

    /**
     * Sets the value of the legalComplianceCertificationDateOfIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalComplianceCertificationDateOfIssue(String value) {
        this.legalComplianceCertificationDateOfIssue = value;
    }

    /**
     * Gets the value of the legalComplianceCertificationExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalComplianceCertificationExpirationDate() {
        return legalComplianceCertificationExpirationDate;
    }

    /**
     * Sets the value of the legalComplianceCertificationExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalComplianceCertificationExpirationDate(String value) {
        this.legalComplianceCertificationExpirationDate = value;
    }

    /**
     * Gets the value of the legalComplianceCertificationRegulatoryOrganizationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalComplianceCertificationRegulatoryOrganizationName() {
        return legalComplianceCertificationRegulatoryOrganizationName;
    }

    /**
     * Sets the value of the legalComplianceCertificationRegulatoryOrganizationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalComplianceCertificationRegulatoryOrganizationName(String value) {
        this.legalComplianceCertificationRegulatoryOrganizationName = value;
    }

    /**
     * Gets the value of the manufacturerContactInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturerContactInformation() {
        return manufacturerContactInformation;
    }

    /**
     * Sets the value of the manufacturerContactInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturerContactInformation(String value) {
        this.manufacturerContactInformation = value;
    }

    /**
     * Gets the value of the materialComposition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialComposition() {
        return materialComposition;
    }

    /**
     * Sets the value of the materialComposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialComposition(String value) {
        this.materialComposition = value;
    }

    /**
     * Gets the value of the maximumWeightRecommendation property.
     * 
     * @return
     *     possible object is
     *     {@link PositiveWeightDimension }
     *     
     */
    public PositiveWeightDimension getMaximumWeightRecommendation() {
        return maximumWeightRecommendation;
    }

    /**
     * Sets the value of the maximumWeightRecommendation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositiveWeightDimension }
     *     
     */
    public void setMaximumWeightRecommendation(PositiveWeightDimension value) {
        this.maximumWeightRecommendation = value;
    }

    /**
     * Gets the value of the maximumAgeRecommendation property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaximumAgeRecommendation() {
        return maximumAgeRecommendation;
    }

    /**
     * Sets the value of the maximumAgeRecommendation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaximumAgeRecommendation(BigInteger value) {
        this.maximumAgeRecommendation = value;
    }

    /**
     * Gets the value of the minimumAgeRecommendation property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinimumAgeRecommendation() {
        return minimumAgeRecommendation;
    }

    /**
     * Sets the value of the minimumAgeRecommendation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinimumAgeRecommendation(BigInteger value) {
        this.minimumAgeRecommendation = value;
    }

    /**
     * Gets the value of the modelNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelNumber() {
        return modelNumber;
    }

    /**
     * Sets the value of the modelNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelNumber(String value) {
        this.modelNumber = value;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the artistBiography property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtistBiography() {
        return artistBiography;
    }

    /**
     * Sets the value of the artistBiography property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtistBiography(String value) {
        this.artistBiography = value;
    }

    /**
     * Gets the value of the packerContactInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackerContactInformation() {
        return packerContactInformation;
    }

    /**
     * Sets the value of the packerContactInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackerContactInformation(String value) {
        this.packerContactInformation = value;
    }

    /**
     * Gets the value of the platinumKeywords property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the platinumKeywords property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlatinumKeywords().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPlatinumKeywords() {
        if (platinumKeywords == null) {
            platinumKeywords = new ArrayList<String>();
        }
        return this.platinumKeywords;
    }

    /**
     * Gets the value of the powerPlugType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPowerPlugType() {
        return powerPlugType;
    }

    /**
     * Sets the value of the powerPlugType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPowerPlugType(String value) {
        this.powerPlugType = value;
    }

    /**
     * Gets the value of the shaftType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShaftType() {
        return shaftType;
    }

    /**
     * Sets the value of the shaftType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShaftType(String value) {
        this.shaftType = value;
    }

    /**
     * Gets the value of the specificationMet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecificationMet() {
        return specificationMet;
    }

    /**
     * Sets the value of the specificationMet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecificationMet(String value) {
        this.specificationMet = value;
    }

    /**
     * Gets the value of the storageInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStorageInstructions() {
        return storageInstructions;
    }

    /**
     * Sets the value of the storageInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStorageInstructions(String value) {
        this.storageInstructions = value;
    }

    /**
     * Gets the value of the targetAudienceBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetAudienceBase() {
        return targetAudienceBase;
    }

    /**
     * Sets the value of the targetAudienceBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetAudienceBase(String value) {
        this.targetAudienceBase = value;
    }

    /**
     * Gets the value of the tunerTechnology property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tunerTechnology property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTunerTechnology().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTunerTechnology() {
        if (tunerTechnology == null) {
            tunerTechnology = new ArrayList<String>();
        }
        return this.tunerTechnology;
    }

    /**
     * Gets the value of the ppuCountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPPUCountType() {
        return ppuCountType;
    }

    /**
     * Sets the value of the ppuCountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPPUCountType(String value) {
        this.ppuCountType = value;
    }

    /**
     * Gets the value of the weeeTaxValue property.
     * 
     * @return
     *     possible object is
     *     {@link CurencyDimension }
     *     
     */
    public CurencyDimension getWeeeTaxValue() {
        return weeeTaxValue;
    }

    /**
     * Sets the value of the weeeTaxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurencyDimension }
     *     
     */
    public void setWeeeTaxValue(CurencyDimension value) {
        this.weeeTaxValue = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;decimal"&gt;
     *       &lt;attribute name="unitOfMeasure" use="required" type="{}StringNotNull" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class UnitCount {

        @XmlValue
        protected BigDecimal value;
        @XmlAttribute(name = "unitOfMeasure", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String unitOfMeasure;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValue(BigDecimal value) {
            this.value = value;
        }

        /**
         * Gets the value of the unitOfMeasure property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnitOfMeasure() {
            return unitOfMeasure;
        }

        /**
         * Sets the value of the unitOfMeasure property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnitOfMeasure(String value) {
            this.unitOfMeasure = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="VariationTheme" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Size"/&gt;
     *               &lt;enumeration value="Color"/&gt;
     *               &lt;enumeration value="Size-Color"/&gt;
     *               &lt;enumeration value="ItemDisplayLength-ItemDisplayWidth"/&gt;
     *               &lt;enumeration value="ItemDisplayLength-MaterialType"/&gt;
     *               &lt;enumeration value="ItemDisplayLength-SizeName"/&gt;
     *               &lt;enumeration value="ItemDisplayLength-ColorName"/&gt;
     *               &lt;enumeration value="ItemDisplayLength-ItemDisplayHeight"/&gt;
     *               &lt;enumeration value="ItemDisplayWidth-MaterialType"/&gt;
     *               &lt;enumeration value="ItemDisplayWidth-SizeName"/&gt;
     *               &lt;enumeration value="ItemDisplayWidth-ColorName"/&gt;
     *               &lt;enumeration value="ItemDisplayWidth-ItemDisplayHeight"/&gt;
     *               &lt;enumeration value="ItemPackageQuantity-MaterialType"/&gt;
     *               &lt;enumeration value="ItemPackageQuantity-SizeName"/&gt;
     *               &lt;enumeration value="ItemPackageQuantity-ColorName"/&gt;
     *               &lt;enumeration value="ItemPackageQuantity-ItemDisplayHeight"/&gt;
     *               &lt;enumeration value="ItemDisplayWeight-ItemPackageQuantity"/&gt;
     *               &lt;enumeration value="ItemDisplayWeight-MaterialType"/&gt;
     *               &lt;enumeration value="ItemDisplayWeight-SizeName"/&gt;
     *               &lt;enumeration value="ItemDisplayWeight-ColorName"/&gt;
     *               &lt;enumeration value="ItemDisplayWeight-ItemDisplayHeight"/&gt;
     *               &lt;enumeration value="MaterialType-ItemDisplayLength"/&gt;
     *               &lt;enumeration value="MaterialType-ItemDisplayWidth"/&gt;
     *               &lt;enumeration value="MaterialType-SizeName"/&gt;
     *               &lt;enumeration value="MaterialType-ColorName"/&gt;
     *               &lt;enumeration value="MaterialType-ItemDisplayHeight"/&gt;
     *               &lt;enumeration value="SizeName-ItemDisplayLength"/&gt;
     *               &lt;enumeration value="SizeName-ItemDisplayWidth"/&gt;
     *               &lt;enumeration value="SizeName-ItemDisplayWeight"/&gt;
     *               &lt;enumeration value="SizeName-MaterialType"/&gt;
     *               &lt;enumeration value="SizeName-ColorName"/&gt;
     *               &lt;enumeration value="SizeName-ItemDisplayHeight"/&gt;
     *               &lt;enumeration value="ColorName-ItemDisplayLength"/&gt;
     *               &lt;enumeration value="ColorName-ItemDisplayWidth"/&gt;
     *               &lt;enumeration value="ColorName-ItemPackageQuantity"/&gt;
     *               &lt;enumeration value="ColorName-ItemDisplayWeight"/&gt;
     *               &lt;enumeration value="ColorName-MaterialType"/&gt;
     *               &lt;enumeration value="ColorName-SizeName"/&gt;
     *               &lt;enumeration value="ColorName-ItemDisplayHeight"/&gt;
     *               &lt;enumeration value="ItemDisplayHeight"/&gt;
     *               &lt;enumeration value="MaterialType"/&gt;
     *               &lt;enumeration value="ItemDisplayWeight"/&gt;
     *               &lt;enumeration value="ItemDisplayLength"/&gt;
     *               &lt;enumeration value="ItemPackageQuantity"/&gt;
     *               &lt;enumeration value="ItemDisplayLength-PatternName"/&gt;
     *               &lt;enumeration value="ItemDisplayLength-StyleName"/&gt;
     *               &lt;enumeration value="ItemDisplayWidth-PatternName"/&gt;
     *               &lt;enumeration value="ItemDisplayWidth-StyleName"/&gt;
     *               &lt;enumeration value="Occasion-PatternName"/&gt;
     *               &lt;enumeration value="Occasion-ItemPackageQuantity"/&gt;
     *               &lt;enumeration value="Occasion-MaterialType"/&gt;
     *               &lt;enumeration value="Occasion-StyleName"/&gt;
     *               &lt;enumeration value="Occasion-SizeName"/&gt;
     *               &lt;enumeration value="Occasion-ColorName"/&gt;
     *               &lt;enumeration value="Occasion-ItemDisplayHeight"/&gt;
     *               &lt;enumeration value="PatternName-ItemDisplayLength"/&gt;
     *               &lt;enumeration value="PatternName-ItemDisplayWidth"/&gt;
     *               &lt;enumeration value="PatternName-Occasion"/&gt;
     *               &lt;enumeration value="PatternName-MaterialType"/&gt;
     *               &lt;enumeration value="PatternName-StyleName"/&gt;
     *               &lt;enumeration value="PatternName-SizeName"/&gt;
     *               &lt;enumeration value="PatternName-ColorName"/&gt;
     *               &lt;enumeration value="PatternName-ItemDisplayHeight"/&gt;
     *               &lt;enumeration value="MatteStyle-MaterialType"/&gt;
     *               &lt;enumeration value="MatteStyle-StyleName"/&gt;
     *               &lt;enumeration value="MatteStyle-SizeName"/&gt;
     *               &lt;enumeration value="MatteStyle-ColorName"/&gt;
     *               &lt;enumeration value="ItemPackageQuantity-Occasion"/&gt;
     *               &lt;enumeration value="ItemPackageQuantity-StyleName"/&gt;
     *               &lt;enumeration value="ItemDisplayWeight-StyleName"/&gt;
     *               &lt;enumeration value="MaterialType-PatternName"/&gt;
     *               &lt;enumeration value="MaterialType-MatteStyle"/&gt;
     *               &lt;enumeration value="MaterialType-StyleName"/&gt;
     *               &lt;enumeration value="StyleName-ItemDisplayLength"/&gt;
     *               &lt;enumeration value="StyleName-ItemDisplayWidth"/&gt;
     *               &lt;enumeration value="StyleName-Occasion"/&gt;
     *               &lt;enumeration value="StyleName-PatternName"/&gt;
     *               &lt;enumeration value="StyleName-ItemDisplayWeight"/&gt;
     *               &lt;enumeration value="StyleName-MaterialType"/&gt;
     *               &lt;enumeration value="StyleName-SizeName"/&gt;
     *               &lt;enumeration value="StyleName-ColorName"/&gt;
     *               &lt;enumeration value="SizeName-Occasion"/&gt;
     *               &lt;enumeration value="SizeName-PatternName"/&gt;
     *               &lt;enumeration value="SizeName-MatteStyle"/&gt;
     *               &lt;enumeration value="SizeName-StyleName"/&gt;
     *               &lt;enumeration value="ColorName-Occasion"/&gt;
     *               &lt;enumeration value="ColorName-PatternName"/&gt;
     *               &lt;enumeration value="ColorName-MatteStyle"/&gt;
     *               &lt;enumeration value="ColorName-StyleName"/&gt;
     *               &lt;enumeration value="MatteStyle"/&gt;
     *               &lt;enumeration value="PatternName"/&gt;
     *               &lt;enumeration value="Occasion"/&gt;
     *               &lt;enumeration value="StyleName"/&gt;
     *               &lt;enumeration value="ScentName"/&gt;
     *               &lt;enumeration value="CustomerPackageType"/&gt;
     *               &lt;enumeration value="ColorName-CustomerPackageType"/&gt;
     *               &lt;enumeration value="SizeName-CustomerPackageType"/&gt;
     *               &lt;enumeration value="SizeName-ColorName-CustomerPackageType"/&gt;
     *               &lt;enumeration value="StyleName-CustomerPackageType"/&gt;
     *               &lt;enumeration value="SizeName-StyleName-CustomerPackageType"/&gt;
     *               &lt;enumeration value="MetalType"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Size" type="{}StringNotNull" minOccurs="0"/&gt;
     *         &lt;element name="Color" type="{}StringNotNull" minOccurs="0"/&gt;
     *         &lt;element name="StyleName" type="{}StringNotNull" minOccurs="0"/&gt;
     *         &lt;element name="ScentName" type="{}StringNotNull" minOccurs="0"/&gt;
     *         &lt;element name="CustomerPackageType" type="{}StringNotNull" minOccurs="0"/&gt;
     *         &lt;element name="MetalType" type="{}StringNotNull" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "variationTheme",
        "size",
        "color",
        "styleName",
        "scentName",
        "customerPackageType",
        "metalType"
    })
    public static class VariationData {

        @XmlElement(name = "VariationTheme")
        protected String variationTheme;
        @XmlElement(name = "Size")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String size;
        @XmlElement(name = "Color")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String color;
        @XmlElement(name = "StyleName")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String styleName;
        @XmlElement(name = "ScentName")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String scentName;
        @XmlElement(name = "CustomerPackageType")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String customerPackageType;
        @XmlElement(name = "MetalType")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String metalType;

        /**
         * Gets the value of the variationTheme property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVariationTheme() {
            return variationTheme;
        }

        /**
         * Sets the value of the variationTheme property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVariationTheme(String value) {
            this.variationTheme = value;
        }

        /**
         * Gets the value of the size property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSize() {
            return size;
        }

        /**
         * Sets the value of the size property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSize(String value) {
            this.size = value;
        }

        /**
         * Gets the value of the color property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getColor() {
            return color;
        }

        /**
         * Sets the value of the color property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setColor(String value) {
            this.color = value;
        }

        /**
         * Gets the value of the styleName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStyleName() {
            return styleName;
        }

        /**
         * Sets the value of the styleName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStyleName(String value) {
            this.styleName = value;
        }

        /**
         * Gets the value of the scentName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScentName() {
            return scentName;
        }

        /**
         * Sets the value of the scentName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScentName(String value) {
            this.scentName = value;
        }

        /**
         * Gets the value of the customerPackageType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomerPackageType() {
            return customerPackageType;
        }

        /**
         * Sets the value of the customerPackageType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomerPackageType(String value) {
            this.customerPackageType = value;
        }

        /**
         * Gets the value of the metalType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMetalType() {
            return metalType;
        }

        /**
         * Sets the value of the metalType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMetalType(String value) {
            this.metalType = value;
        }

    }

}
