//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 11:40:51 PM CST 
//


package com.kindminds.drs.mws.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PencilLeadHardnessType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PencilLeadHardnessType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="6B"/&gt;
 *     &lt;enumeration value="4B"/&gt;
 *     &lt;enumeration value="2B"/&gt;
 *     &lt;enumeration value="B"/&gt;
 *     &lt;enumeration value="HB"/&gt;
 *     &lt;enumeration value="F"/&gt;
 *     &lt;enumeration value="H"/&gt;
 *     &lt;enumeration value="2H"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PencilLeadHardnessType")
@XmlEnum
public enum PencilLeadHardnessType {

    @XmlEnumValue("6B")
    VALUE_1("6B"),
    @XmlEnumValue("4B")
    VALUE_2("4B"),
    @XmlEnumValue("2B")
    VALUE_3("2B"),
    @XmlEnumValue("B")
    VALUE_4("B"),
    @XmlEnumValue("HB")
    VALUE_5("HB"),
    @XmlEnumValue("F")
    VALUE_6("F"),
    @XmlEnumValue("H")
    VALUE_7("H"),
    @XmlEnumValue("2H")
    VALUE_8("2H");
    private final String value;

    PencilLeadHardnessType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PencilLeadHardnessType fromValue(String v) {
        for (PencilLeadHardnessType c: PencilLeadHardnessType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
