//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 11:40:51 PM CST 
//


package com.kindminds.drs.mws.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ParentSKU" type="{}SKUType"/&gt;
 *         &lt;element name="Relation" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{}SKU"/&gt;
 *                   &lt;element name="Type"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Variation"/&gt;
 *                         &lt;enumeration value="DisplaySet"/&gt;
 *                         &lt;enumeration value="Collection"/&gt;
 *                         &lt;enumeration value="Accessory"/&gt;
 *                         &lt;enumeration value="Customized"/&gt;
 *                         &lt;enumeration value="Part"/&gt;
 *                         &lt;enumeration value="Complements"/&gt;
 *                         &lt;enumeration value="Piece"/&gt;
 *                         &lt;enumeration value="Necessary"/&gt;
 *                         &lt;enumeration value="ReplacementPart"/&gt;
 *                         &lt;enumeration value="Similar"/&gt;
 *                         &lt;enumeration value="Episode"/&gt;
 *                         &lt;enumeration value="Season"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parentSKU",
    "relation"
})
@XmlRootElement(name = "Relationship")
public class Relationship {

    @XmlElement(name = "ParentSKU", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String parentSKU;
    @XmlElement(name = "Relation", required = true)
    protected List<Relationship.Relation> relation;

    /**
     * Gets the value of the parentSKU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentSKU() {
        return parentSKU;
    }

    /**
     * Sets the value of the parentSKU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentSKU(String value) {
        this.parentSKU = value;
    }

    /**
     * Gets the value of the relation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Relationship.Relation }
     * 
     * 
     */
    public List<Relationship.Relation> getRelation() {
        if (relation == null) {
            relation = new ArrayList<Relationship.Relation>();
        }
        return this.relation;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{}SKU"/&gt;
     *         &lt;element name="Type"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Variation"/&gt;
     *               &lt;enumeration value="DisplaySet"/&gt;
     *               &lt;enumeration value="Collection"/&gt;
     *               &lt;enumeration value="Accessory"/&gt;
     *               &lt;enumeration value="Customized"/&gt;
     *               &lt;enumeration value="Part"/&gt;
     *               &lt;enumeration value="Complements"/&gt;
     *               &lt;enumeration value="Piece"/&gt;
     *               &lt;enumeration value="Necessary"/&gt;
     *               &lt;enumeration value="ReplacementPart"/&gt;
     *               &lt;enumeration value="Similar"/&gt;
     *               &lt;enumeration value="Episode"/&gt;
     *               &lt;enumeration value="Season"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sku",
        "type"
    })
    public static class Relation {

        @XmlElement(name = "SKU", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String sku;
        @XmlElement(name = "Type", required = true)
        protected String type;

        /**
         * Gets the value of the sku property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSKU() {
            return sku;
        }

        /**
         * Sets the value of the sku property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSKU(String value) {
            this.sku = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }

}
