//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 11:40:51 PM CST 
//


package com.kindminds.drs.mws.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShoeSafetyCodeIso20345Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ShoeSafetyCodeIso20345Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="sb"/&gt;
 *     &lt;enumeration value="s1"/&gt;
 *     &lt;enumeration value="s2"/&gt;
 *     &lt;enumeration value="s3"/&gt;
 *     &lt;enumeration value="hro"/&gt;
 *     &lt;enumeration value="p"/&gt;
 *     &lt;enumeration value="e"/&gt;
 *     &lt;enumeration value="wru"/&gt;
 *     &lt;enumeration value="o"/&gt;
 *     &lt;enumeration value="a"/&gt;
 *     &lt;enumeration value="ci"/&gt;
 *     &lt;enumeration value="hi"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ShoeSafetyCodeIso20345Type")
@XmlEnum
public enum ShoeSafetyCodeIso20345Type {

    @XmlEnumValue("sb")
    SB("sb"),
    @XmlEnumValue("s1")
    S_1("s1"),
    @XmlEnumValue("s2")
    S_2("s2"),
    @XmlEnumValue("s3")
    S_3("s3"),
    @XmlEnumValue("hro")
    HRO("hro"),
    @XmlEnumValue("p")
    P("p"),
    @XmlEnumValue("e")
    E("e"),
    @XmlEnumValue("wru")
    WRU("wru"),
    @XmlEnumValue("o")
    O("o"),
    @XmlEnumValue("a")
    A("a"),
    @XmlEnumValue("ci")
    CI("ci"),
    @XmlEnumValue("hi")
    HI("hi");
    private final String value;

    ShoeSafetyCodeIso20345Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ShoeSafetyCodeIso20345Type fromValue(String v) {
        for (ShoeSafetyCodeIso20345Type c: ShoeSafetyCodeIso20345Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
