//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 11:40:51 PM CST 
//


package com.kindminds.drs.mws.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThicknessUnitOfMeasure.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ThicknessUnitOfMeasure"&gt;
 *   &lt;restriction base="{}StringNotNull"&gt;
 *     &lt;enumeration value="IN"/&gt;
 *     &lt;enumeration value="CM"/&gt;
 *     &lt;enumeration value="MM"/&gt;
 *     &lt;enumeration value="gauge"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ThicknessUnitOfMeasure")
@XmlEnum
public enum ThicknessUnitOfMeasure {

    IN("IN"),
    CM("CM"),
    MM("MM"),
    @XmlEnumValue("gauge")
    GAUGE("gauge");
    private final String value;

    ThicknessUnitOfMeasure(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ThicknessUnitOfMeasure fromValue(String v) {
        for (ThicknessUnitOfMeasure c: ThicknessUnitOfMeasure.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
