//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 11:40:51 PM CST 
//


package com.kindminds.drs.mws.xml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BoreDiameter" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element ref="{}ColorSpecification" minOccurs="0"/&gt;
 *         &lt;element name="ConstructionType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Offset" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="LoadIndex" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="Material" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfHoles" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="OemEquivalentPartNumber" type="{}FortyStringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="PitchCircleDiameter" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="RimDiameter" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="RimWidth" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="Seasons" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="SectionWidth" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="SpecialFeatures" type="{}StringNotNull" maxOccurs="5" minOccurs="0"/&gt;
 *         &lt;element name="SpeedRating" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="A1"/&gt;
 *               &lt;enumeration value="A2"/&gt;
 *               &lt;enumeration value="A3"/&gt;
 *               &lt;enumeration value="A4"/&gt;
 *               &lt;enumeration value="A5"/&gt;
 *               &lt;enumeration value="A6"/&gt;
 *               &lt;enumeration value="A7"/&gt;
 *               &lt;enumeration value="A8"/&gt;
 *               &lt;enumeration value="B"/&gt;
 *               &lt;enumeration value="C"/&gt;
 *               &lt;enumeration value="D"/&gt;
 *               &lt;enumeration value="E"/&gt;
 *               &lt;enumeration value="F"/&gt;
 *               &lt;enumeration value="G"/&gt;
 *               &lt;enumeration value="J"/&gt;
 *               &lt;enumeration value="K"/&gt;
 *               &lt;enumeration value="L"/&gt;
 *               &lt;enumeration value="M"/&gt;
 *               &lt;enumeration value="N"/&gt;
 *               &lt;enumeration value="P"/&gt;
 *               &lt;enumeration value="Q"/&gt;
 *               &lt;enumeration value="R"/&gt;
 *               &lt;enumeration value="S"/&gt;
 *               &lt;enumeration value="T"/&gt;
 *               &lt;enumeration value="U"/&gt;
 *               &lt;enumeration value="H"/&gt;
 *               &lt;enumeration value="V"/&gt;
 *               &lt;enumeration value="Z"/&gt;
 *               &lt;enumeration value="W"/&gt;
 *               &lt;enumeration value="Y"/&gt;
 *               &lt;enumeration value="SR"/&gt;
 *               &lt;enumeration value="HR"/&gt;
 *               &lt;enumeration value="VR"/&gt;
 *               &lt;enumeration value="ZR"/&gt;
 *               &lt;enumeration value="Other"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ModelName" type="{}FortyStringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="TireAspectRatio" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="TireType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="TreadType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Amperage" type="{}AmperageDimension" minOccurs="0"/&gt;
 *         &lt;element name="CareInstructions" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Diameter" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="DisplayLength" type="{}LengthDimension" minOccurs="0"/&gt;
 *         &lt;element name="DisplayVolume" type="{}VolumeDimension" minOccurs="0"/&gt;
 *         &lt;element name="DisplayWeight" type="{}WeightDimension" minOccurs="0"/&gt;
 *         &lt;element name="Lifestyle" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="ManufacturerWarrantyDescription" type="{}SuperLongStringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="ModelYear" type="{}FourDigitYear" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfPieces" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="RecallDescription" type="{}SuperLongStringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Size" type="{}String" minOccurs="0"/&gt;
 *         &lt;element name="SizeMap" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="SpecificationMet" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="StyleName" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="VariationData" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Parentage"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{}String"&gt;
 *                         &lt;enumeration value="parent"/&gt;
 *                         &lt;enumeration value="child"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="VariationTheme" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{}String"&gt;
 *                         &lt;enumeration value="Color"/&gt;
 *                         &lt;enumeration value="Size"/&gt;
 *                         &lt;enumeration value="SizeColor"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Voltage" type="{}VoltageDecimalDimension" minOccurs="0"/&gt;
 *         &lt;element name="Wattage" type="{}WattageDimension" minOccurs="0"/&gt;
 *         &lt;element name="VehicleFitmentCode" type="{}TwoThousandString" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "boreDiameter",
    "colorSpecification",
    "constructionType",
    "offset",
    "loadIndex",
    "material",
    "numberOfHoles",
    "oemEquivalentPartNumber",
    "pitchCircleDiameter",
    "rimDiameter",
    "rimWidth",
    "seasons",
    "sectionWidth",
    "specialFeatures",
    "speedRating",
    "modelName",
    "tireAspectRatio",
    "tireType",
    "treadType",
    "amperage",
    "careInstructions",
    "diameter",
    "displayLength",
    "displayVolume",
    "displayWeight",
    "lifestyle",
    "manufacturerWarrantyDescription",
    "modelYear",
    "numberOfPieces",
    "recallDescription",
    "size",
    "sizeMap",
    "specificationMet",
    "styleName",
    "variationData",
    "voltage",
    "wattage",
    "vehicleFitmentCode"
})
@XmlRootElement(name = "TireAndWheelAssemblies")
public class TireAndWheelAssemblies {

    @XmlElement(name = "BoreDiameter")
    protected LengthDimension boreDiameter;
    @XmlElement(name = "ColorSpecification")
    protected ColorSpecification colorSpecification;
    @XmlElement(name = "ConstructionType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String constructionType;
    @XmlElement(name = "Offset")
    protected LengthDimension offset;
    @XmlElement(name = "LoadIndex")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger loadIndex;
    @XmlElement(name = "Material")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String material;
    @XmlElement(name = "NumberOfHoles")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfHoles;
    @XmlElement(name = "OemEquivalentPartNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String oemEquivalentPartNumber;
    @XmlElement(name = "PitchCircleDiameter")
    protected LengthDimension pitchCircleDiameter;
    @XmlElement(name = "RimDiameter")
    protected LengthDimension rimDiameter;
    @XmlElement(name = "RimWidth")
    protected LengthDimension rimWidth;
    @XmlElement(name = "Seasons")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String seasons;
    @XmlElement(name = "SectionWidth")
    protected LengthDimension sectionWidth;
    @XmlElement(name = "SpecialFeatures")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected List<String> specialFeatures;
    @XmlElement(name = "SpeedRating")
    protected String speedRating;
    @XmlElement(name = "ModelName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String modelName;
    @XmlElement(name = "TireAspectRatio")
    protected LengthDimension tireAspectRatio;
    @XmlElement(name = "TireType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String tireType;
    @XmlElement(name = "TreadType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String treadType;
    @XmlElement(name = "Amperage")
    protected AmperageDimension amperage;
    @XmlElement(name = "CareInstructions")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String careInstructions;
    @XmlElement(name = "Diameter")
    protected LengthDimension diameter;
    @XmlElement(name = "DisplayLength")
    protected LengthDimension displayLength;
    @XmlElement(name = "DisplayVolume")
    protected VolumeDimension displayVolume;
    @XmlElement(name = "DisplayWeight")
    protected WeightDimension displayWeight;
    @XmlElement(name = "Lifestyle")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String lifestyle;
    @XmlElement(name = "ManufacturerWarrantyDescription")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String manufacturerWarrantyDescription;
    @XmlElement(name = "ModelYear")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger modelYear;
    @XmlElement(name = "NumberOfPieces")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfPieces;
    @XmlElement(name = "RecallDescription")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String recallDescription;
    @XmlElement(name = "Size")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String size;
    @XmlElement(name = "SizeMap")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String sizeMap;
    @XmlElement(name = "SpecificationMet")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String specificationMet;
    @XmlElement(name = "StyleName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String styleName;
    @XmlElement(name = "VariationData")
    protected TireAndWheelAssemblies.VariationData variationData;
    @XmlElement(name = "Voltage")
    protected VoltageDecimalDimension voltage;
    @XmlElement(name = "Wattage")
    protected WattageDimension wattage;
    @XmlElement(name = "VehicleFitmentCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String vehicleFitmentCode;

    /**
     * Gets the value of the boreDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getBoreDiameter() {
        return boreDiameter;
    }

    /**
     * Sets the value of the boreDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setBoreDiameter(LengthDimension value) {
        this.boreDiameter = value;
    }

    /**
     * Gets the value of the colorSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link ColorSpecification }
     *     
     */
    public ColorSpecification getColorSpecification() {
        return colorSpecification;
    }

    /**
     * Sets the value of the colorSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorSpecification }
     *     
     */
    public void setColorSpecification(ColorSpecification value) {
        this.colorSpecification = value;
    }

    /**
     * Gets the value of the constructionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConstructionType() {
        return constructionType;
    }

    /**
     * Sets the value of the constructionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConstructionType(String value) {
        this.constructionType = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setOffset(LengthDimension value) {
        this.offset = value;
    }

    /**
     * Gets the value of the loadIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLoadIndex() {
        return loadIndex;
    }

    /**
     * Sets the value of the loadIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLoadIndex(BigInteger value) {
        this.loadIndex = value;
    }

    /**
     * Gets the value of the material property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterial() {
        return material;
    }

    /**
     * Sets the value of the material property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterial(String value) {
        this.material = value;
    }

    /**
     * Gets the value of the numberOfHoles property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfHoles() {
        return numberOfHoles;
    }

    /**
     * Sets the value of the numberOfHoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfHoles(BigInteger value) {
        this.numberOfHoles = value;
    }

    /**
     * Gets the value of the oemEquivalentPartNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOemEquivalentPartNumber() {
        return oemEquivalentPartNumber;
    }

    /**
     * Sets the value of the oemEquivalentPartNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOemEquivalentPartNumber(String value) {
        this.oemEquivalentPartNumber = value;
    }

    /**
     * Gets the value of the pitchCircleDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getPitchCircleDiameter() {
        return pitchCircleDiameter;
    }

    /**
     * Sets the value of the pitchCircleDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setPitchCircleDiameter(LengthDimension value) {
        this.pitchCircleDiameter = value;
    }

    /**
     * Gets the value of the rimDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getRimDiameter() {
        return rimDiameter;
    }

    /**
     * Sets the value of the rimDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setRimDiameter(LengthDimension value) {
        this.rimDiameter = value;
    }

    /**
     * Gets the value of the rimWidth property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getRimWidth() {
        return rimWidth;
    }

    /**
     * Sets the value of the rimWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setRimWidth(LengthDimension value) {
        this.rimWidth = value;
    }

    /**
     * Gets the value of the seasons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeasons() {
        return seasons;
    }

    /**
     * Sets the value of the seasons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeasons(String value) {
        this.seasons = value;
    }

    /**
     * Gets the value of the sectionWidth property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getSectionWidth() {
        return sectionWidth;
    }

    /**
     * Sets the value of the sectionWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setSectionWidth(LengthDimension value) {
        this.sectionWidth = value;
    }

    /**
     * Gets the value of the specialFeatures property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialFeatures property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialFeatures().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSpecialFeatures() {
        if (specialFeatures == null) {
            specialFeatures = new ArrayList<String>();
        }
        return this.specialFeatures;
    }

    /**
     * Gets the value of the speedRating property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeedRating() {
        return speedRating;
    }

    /**
     * Sets the value of the speedRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeedRating(String value) {
        this.speedRating = value;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the tireAspectRatio property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getTireAspectRatio() {
        return tireAspectRatio;
    }

    /**
     * Sets the value of the tireAspectRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setTireAspectRatio(LengthDimension value) {
        this.tireAspectRatio = value;
    }

    /**
     * Gets the value of the tireType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTireType() {
        return tireType;
    }

    /**
     * Sets the value of the tireType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTireType(String value) {
        this.tireType = value;
    }

    /**
     * Gets the value of the treadType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTreadType() {
        return treadType;
    }

    /**
     * Sets the value of the treadType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTreadType(String value) {
        this.treadType = value;
    }

    /**
     * Gets the value of the amperage property.
     * 
     * @return
     *     possible object is
     *     {@link AmperageDimension }
     *     
     */
    public AmperageDimension getAmperage() {
        return amperage;
    }

    /**
     * Sets the value of the amperage property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmperageDimension }
     *     
     */
    public void setAmperage(AmperageDimension value) {
        this.amperage = value;
    }

    /**
     * Gets the value of the careInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCareInstructions() {
        return careInstructions;
    }

    /**
     * Sets the value of the careInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCareInstructions(String value) {
        this.careInstructions = value;
    }

    /**
     * Gets the value of the diameter property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getDiameter() {
        return diameter;
    }

    /**
     * Sets the value of the diameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setDiameter(LengthDimension value) {
        this.diameter = value;
    }

    /**
     * Gets the value of the displayLength property.
     * 
     * @return
     *     possible object is
     *     {@link LengthDimension }
     *     
     */
    public LengthDimension getDisplayLength() {
        return displayLength;
    }

    /**
     * Sets the value of the displayLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthDimension }
     *     
     */
    public void setDisplayLength(LengthDimension value) {
        this.displayLength = value;
    }

    /**
     * Gets the value of the displayVolume property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeDimension }
     *     
     */
    public VolumeDimension getDisplayVolume() {
        return displayVolume;
    }

    /**
     * Sets the value of the displayVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeDimension }
     *     
     */
    public void setDisplayVolume(VolumeDimension value) {
        this.displayVolume = value;
    }

    /**
     * Gets the value of the displayWeight property.
     * 
     * @return
     *     possible object is
     *     {@link WeightDimension }
     *     
     */
    public WeightDimension getDisplayWeight() {
        return displayWeight;
    }

    /**
     * Sets the value of the displayWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightDimension }
     *     
     */
    public void setDisplayWeight(WeightDimension value) {
        this.displayWeight = value;
    }

    /**
     * Gets the value of the lifestyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLifestyle() {
        return lifestyle;
    }

    /**
     * Sets the value of the lifestyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLifestyle(String value) {
        this.lifestyle = value;
    }

    /**
     * Gets the value of the manufacturerWarrantyDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturerWarrantyDescription() {
        return manufacturerWarrantyDescription;
    }

    /**
     * Sets the value of the manufacturerWarrantyDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturerWarrantyDescription(String value) {
        this.manufacturerWarrantyDescription = value;
    }

    /**
     * Gets the value of the modelYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getModelYear() {
        return modelYear;
    }

    /**
     * Sets the value of the modelYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setModelYear(BigInteger value) {
        this.modelYear = value;
    }

    /**
     * Gets the value of the numberOfPieces property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfPieces() {
        return numberOfPieces;
    }

    /**
     * Sets the value of the numberOfPieces property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfPieces(BigInteger value) {
        this.numberOfPieces = value;
    }

    /**
     * Gets the value of the recallDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecallDescription() {
        return recallDescription;
    }

    /**
     * Sets the value of the recallDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecallDescription(String value) {
        this.recallDescription = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSize(String value) {
        this.size = value;
    }

    /**
     * Gets the value of the sizeMap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizeMap() {
        return sizeMap;
    }

    /**
     * Sets the value of the sizeMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizeMap(String value) {
        this.sizeMap = value;
    }

    /**
     * Gets the value of the specificationMet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecificationMet() {
        return specificationMet;
    }

    /**
     * Sets the value of the specificationMet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecificationMet(String value) {
        this.specificationMet = value;
    }

    /**
     * Gets the value of the styleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyleName() {
        return styleName;
    }

    /**
     * Sets the value of the styleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyleName(String value) {
        this.styleName = value;
    }

    /**
     * Gets the value of the variationData property.
     * 
     * @return
     *     possible object is
     *     {@link TireAndWheelAssemblies.VariationData }
     *     
     */
    public TireAndWheelAssemblies.VariationData getVariationData() {
        return variationData;
    }

    /**
     * Sets the value of the variationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TireAndWheelAssemblies.VariationData }
     *     
     */
    public void setVariationData(TireAndWheelAssemblies.VariationData value) {
        this.variationData = value;
    }

    /**
     * Gets the value of the voltage property.
     * 
     * @return
     *     possible object is
     *     {@link VoltageDecimalDimension }
     *     
     */
    public VoltageDecimalDimension getVoltage() {
        return voltage;
    }

    /**
     * Sets the value of the voltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link VoltageDecimalDimension }
     *     
     */
    public void setVoltage(VoltageDecimalDimension value) {
        this.voltage = value;
    }

    /**
     * Gets the value of the wattage property.
     * 
     * @return
     *     possible object is
     *     {@link WattageDimension }
     *     
     */
    public WattageDimension getWattage() {
        return wattage;
    }

    /**
     * Sets the value of the wattage property.
     * 
     * @param value
     *     allowed object is
     *     {@link WattageDimension }
     *     
     */
    public void setWattage(WattageDimension value) {
        this.wattage = value;
    }

    /**
     * Gets the value of the vehicleFitmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleFitmentCode() {
        return vehicleFitmentCode;
    }

    /**
     * Sets the value of the vehicleFitmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleFitmentCode(String value) {
        this.vehicleFitmentCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Parentage"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{}String"&gt;
     *               &lt;enumeration value="parent"/&gt;
     *               &lt;enumeration value="child"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="VariationTheme" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{}String"&gt;
     *               &lt;enumeration value="Color"/&gt;
     *               &lt;enumeration value="Size"/&gt;
     *               &lt;enumeration value="SizeColor"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parentage",
        "variationTheme"
    })
    public static class VariationData {

        @XmlElement(name = "Parentage", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String parentage;
        @XmlElement(name = "VariationTheme")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String variationTheme;

        /**
         * Gets the value of the parentage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParentage() {
            return parentage;
        }

        /**
         * Sets the value of the parentage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParentage(String value) {
            this.parentage = value;
        }

        /**
         * Gets the value of the variationTheme property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVariationTheme() {
            return variationTheme;
        }

        /**
         * Sets the value of the variationTheme property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVariationTheme(String value) {
            this.variationTheme = value;
        }

    }

}
