//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 11:40:51 PM CST 
//


package com.kindminds.drs.mws.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VideoDVDMediaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VideoDVDMediaType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="dvd"/&gt;
 *     &lt;enumeration value="hd_dvd"/&gt;
 *     &lt;enumeration value="blu_ray"/&gt;
 *     &lt;enumeration value="videodisc"/&gt;
 *     &lt;enumeration value="dvd_i"/&gt;
 *     &lt;enumeration value="dvd_r"/&gt;
 *     &lt;enumeration value="umd"/&gt;
 *     &lt;enumeration value="video_cd"/&gt;
 *     &lt;enumeration value="mini_disc"/&gt;
 *     &lt;enumeration value="laser_disc"/&gt;
 *     &lt;enumeration value="cassette"/&gt;
 *     &lt;enumeration value="blu_ray"/&gt;
 *     &lt;enumeration value="audioCD"/&gt;
 *     &lt;enumeration value="usb_flash_drive"/&gt;
 *     &lt;enumeration value="mp3_cd"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "VideoDVDMediaType")
@XmlEnum
public enum VideoDVDMediaType {

    @XmlEnumValue("dvd")
    DVD("dvd"),
    @XmlEnumValue("hd_dvd")
    HD___DVD("hd_dvd"),
    @XmlEnumValue("blu_ray")
    BLU___RAY("blu_ray"),
    @XmlEnumValue("videodisc")
    VIDEODISC("videodisc"),
    @XmlEnumValue("dvd_i")
    DVD___I("dvd_i"),
    @XmlEnumValue("dvd_r")
    DVD___R("dvd_r"),
    @XmlEnumValue("umd")
    UMD("umd"),
    @XmlEnumValue("video_cd")
    VIDEO___CD("video_cd"),
    @XmlEnumValue("mini_disc")
    MINI___DISC("mini_disc"),
    @XmlEnumValue("laser_disc")
    LASER___DISC("laser_disc"),
    @XmlEnumValue("cassette")
    CASSETTE("cassette"),
    @XmlEnumValue("audioCD")
    AUDIO_CD("audioCD"),
    @XmlEnumValue("usb_flash_drive")
    USB___FLASH___DRIVE("usb_flash_drive"),
    @XmlEnumValue("mp3_cd")
    MP_3___CD("mp3_cd");
    private final String value;

    VideoDVDMediaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VideoDVDMediaType fromValue(String v) {
        for (VideoDVDMediaType c: VideoDVDMediaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
