//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 11:40:51 PM CST 
//


package com.kindminds.drs.mws.xml;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}VariationData" minOccurs="0"/&gt;
 *         &lt;element name="HasGreyScale" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="LightSourceType" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="ScannerResolution" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element ref="{}AspectRatio" minOccurs="0"/&gt;
 *         &lt;element ref="{}AudibleNoise" minOccurs="0"/&gt;
 *         &lt;element ref="{}BuiltinSpeaker" minOccurs="0"/&gt;
 *         &lt;element ref="{}ContrastRatio" minOccurs="0"/&gt;
 *         &lt;element ref="{}DisplayResolutionMaximum" minOccurs="0"/&gt;
 *         &lt;element ref="{}DisplayTechnology" minOccurs="0"/&gt;
 *         &lt;element ref="{}ImageDiagonalSize" minOccurs="0"/&gt;
 *         &lt;element ref="{}InputVideoCompatability" maxOccurs="3" minOccurs="0"/&gt;
 *         &lt;element ref="{}InputVideoConnectors" minOccurs="0"/&gt;
 *         &lt;element ref="{}KeystoneCorrection" minOccurs="0"/&gt;
 *         &lt;element ref="{}LampLife" minOccurs="0"/&gt;
 *         &lt;element ref="{}LampWattage" minOccurs="0"/&gt;
 *         &lt;element name="Lens" type="{}String" minOccurs="0"/&gt;
 *         &lt;element ref="{}MaximumHorizontalRefreshRate" minOccurs="0"/&gt;
 *         &lt;element ref="{}MaximumImageSize" minOccurs="0"/&gt;
 *         &lt;element ref="{}MaximumThrowDistance" minOccurs="0"/&gt;
 *         &lt;element ref="{}MaximumThrowRatio" minOccurs="0"/&gt;
 *         &lt;element ref="{}MaximumVerticalRefreshRate" minOccurs="0"/&gt;
 *         &lt;element ref="{}MediaInput" minOccurs="0"/&gt;
 *         &lt;element ref="{}MinimumHorizontalRefreshRate" minOccurs="0"/&gt;
 *         &lt;element ref="{}MinimumImageSize" minOccurs="0"/&gt;
 *         &lt;element ref="{}MinimumThrowDistance" minOccurs="0"/&gt;
 *         &lt;element ref="{}MinimumThrowRatio" minOccurs="0"/&gt;
 *         &lt;element ref="{}MinimumVerticalRefreshRate" minOccurs="0"/&gt;
 *         &lt;element ref="{}ModelNumber" minOccurs="0"/&gt;
 *         &lt;element ref="{}ProjectorBrightness" minOccurs="0"/&gt;
 *         &lt;element ref="{}Remote" minOccurs="0"/&gt;
 *         &lt;element ref="{}ScreenResolution" minOccurs="0"/&gt;
 *         &lt;element ref="{}ScreenTrigger" minOccurs="0"/&gt;
 *         &lt;element ref="{}ThreeDReady" minOccurs="0"/&gt;
 *         &lt;element ref="{}WirelessStandard" minOccurs="0"/&gt;
 *         &lt;element ref="{}Zoom" minOccurs="0"/&gt;
 *         &lt;element ref="{}ZoomRatio" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfDVIPorts" type="{}PositiveInteger" minOccurs="0"/&gt;
 *         &lt;element name="Efficiency" type="{}StringNotNull" minOccurs="0"/&gt;
 *         &lt;element name="Voltage" type="{}PositiveInteger" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "variationData",
    "hasGreyScale",
    "lightSourceType",
    "scannerResolution",
    "aspectRatio",
    "audibleNoise",
    "builtinSpeaker",
    "contrastRatio",
    "displayResolutionMaximum",
    "displayTechnology",
    "imageDiagonalSize",
    "inputVideoCompatability",
    "inputVideoConnectors",
    "keystoneCorrection",
    "lampLife",
    "lampWattage",
    "lens",
    "maximumHorizontalRefreshRate",
    "maximumImageSize",
    "maximumThrowDistance",
    "maximumThrowRatio",
    "maximumVerticalRefreshRate",
    "mediaInput",
    "minimumHorizontalRefreshRate",
    "minimumImageSize",
    "minimumThrowDistance",
    "minimumThrowRatio",
    "minimumVerticalRefreshRate",
    "modelNumber",
    "projectorBrightness",
    "remote",
    "screenResolution",
    "screenTrigger",
    "threeDReady",
    "wirelessStandard",
    "zoom",
    "zoomRatio",
    "numberOfDVIPorts",
    "efficiency",
    "voltage"
})
@XmlRootElement(name = "VideoProjector")
public class VideoProjector {

    @XmlElement(name = "VariationData")
    protected VariationData variationData;
    @XmlElement(name = "HasGreyScale")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String hasGreyScale;
    @XmlElement(name = "LightSourceType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String lightSourceType;
    @XmlElement(name = "ScannerResolution")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String scannerResolution;
    @XmlElement(name = "AspectRatio")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String aspectRatio;
    @XmlElement(name = "AudibleNoise")
    protected BigDecimal audibleNoise;
    @XmlElement(name = "BuiltinSpeaker")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger builtinSpeaker;
    @XmlElement(name = "ContrastRatio")
    protected String contrastRatio;
    @XmlElement(name = "DisplayResolutionMaximum")
    protected String displayResolutionMaximum;
    @XmlElement(name = "DisplayTechnology")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String displayTechnology;
    @XmlElement(name = "ImageDiagonalSize")
    protected LengthSevenDigitDimension imageDiagonalSize;
    @XmlElement(name = "InputVideoCompatability")
    protected List<String> inputVideoCompatability;
    @XmlElement(name = "InputVideoConnectors")
    @XmlSchemaType(name = "string")
    protected InputVideoConnectorsTypeValues inputVideoConnectors;
    @XmlElement(name = "KeystoneCorrection")
    protected LengthSevenDigitDimension keystoneCorrection;
    @XmlElement(name = "LampLife")
    protected BurnTimeSixDigitDimension lampLife;
    @XmlElement(name = "LampWattage")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger lampWattage;
    @XmlElement(name = "Lens")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String lens;
    @XmlElement(name = "MaximumHorizontalRefreshRate")
    protected FrequencyFiveDigitIntegerDimension maximumHorizontalRefreshRate;
    @XmlElement(name = "MaximumImageSize")
    protected LengthSevenDigitDimension maximumImageSize;
    @XmlElement(name = "MaximumThrowDistance")
    protected BigDecimal maximumThrowDistance;
    @XmlElement(name = "MaximumThrowRatio")
    protected String maximumThrowRatio;
    @XmlElement(name = "MaximumVerticalRefreshRate")
    protected FrequencyFiveDigitIntegerDimension maximumVerticalRefreshRate;
    @XmlElement(name = "MediaInput")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String mediaInput;
    @XmlElement(name = "MinimumHorizontalRefreshRate")
    protected FrequencyFiveDigitIntegerDimension minimumHorizontalRefreshRate;
    @XmlElement(name = "MinimumImageSize")
    protected LengthSevenDigitDimension minimumImageSize;
    @XmlElement(name = "MinimumThrowDistance")
    protected BigDecimal minimumThrowDistance;
    @XmlElement(name = "MinimumThrowRatio")
    protected String minimumThrowRatio;
    @XmlElement(name = "MinimumVerticalRefreshRate")
    protected FrequencyFiveDigitIntegerDimension minimumVerticalRefreshRate;
    @XmlElement(name = "ModelNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String modelNumber;
    @XmlElement(name = "ProjectorBrightness")
    protected LuminanceFiveDigitDimension projectorBrightness;
    @XmlElement(name = "Remote")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String remote;
    @XmlElement(name = "ScreenResolution")
    protected String screenResolution;
    @XmlElement(name = "ScreenTrigger")
    protected VoltageFiveDigitIntegerDimension screenTrigger;
    @XmlElement(name = "ThreeDReady")
    protected String threeDReady;
    @XmlElement(name = "WirelessStandard")
    @XmlSchemaType(name = "string")
    protected WirelessStandardTypeValues wirelessStandard;
    @XmlElement(name = "Zoom")
    protected String zoom;
    @XmlElement(name = "ZoomRatio")
    protected String zoomRatio;
    @XmlElement(name = "NumberOfDVIPorts")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfDVIPorts;
    @XmlElement(name = "Efficiency")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String efficiency;
    @XmlElement(name = "Voltage")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger voltage;

    /**
     * Gets the value of the variationData property.
     * 
     * @return
     *     possible object is
     *     {@link VariationData }
     *     
     */
    public VariationData getVariationData() {
        return variationData;
    }

    /**
     * Sets the value of the variationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariationData }
     *     
     */
    public void setVariationData(VariationData value) {
        this.variationData = value;
    }

    /**
     * Gets the value of the hasGreyScale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasGreyScale() {
        return hasGreyScale;
    }

    /**
     * Sets the value of the hasGreyScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasGreyScale(String value) {
        this.hasGreyScale = value;
    }

    /**
     * Gets the value of the lightSourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLightSourceType() {
        return lightSourceType;
    }

    /**
     * Sets the value of the lightSourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLightSourceType(String value) {
        this.lightSourceType = value;
    }

    /**
     * Gets the value of the scannerResolution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScannerResolution() {
        return scannerResolution;
    }

    /**
     * Sets the value of the scannerResolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScannerResolution(String value) {
        this.scannerResolution = value;
    }

    /**
     * Gets the value of the aspectRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAspectRatio() {
        return aspectRatio;
    }

    /**
     * Sets the value of the aspectRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAspectRatio(String value) {
        this.aspectRatio = value;
    }

    /**
     * Gets the value of the audibleNoise property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAudibleNoise() {
        return audibleNoise;
    }

    /**
     * Sets the value of the audibleNoise property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAudibleNoise(BigDecimal value) {
        this.audibleNoise = value;
    }

    /**
     * Gets the value of the builtinSpeaker property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBuiltinSpeaker() {
        return builtinSpeaker;
    }

    /**
     * Sets the value of the builtinSpeaker property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBuiltinSpeaker(BigInteger value) {
        this.builtinSpeaker = value;
    }

    /**
     * Gets the value of the contrastRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContrastRatio() {
        return contrastRatio;
    }

    /**
     * Sets the value of the contrastRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContrastRatio(String value) {
        this.contrastRatio = value;
    }

    /**
     * Gets the value of the displayResolutionMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayResolutionMaximum() {
        return displayResolutionMaximum;
    }

    /**
     * Sets the value of the displayResolutionMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayResolutionMaximum(String value) {
        this.displayResolutionMaximum = value;
    }

    /**
     * Gets the value of the displayTechnology property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayTechnology() {
        return displayTechnology;
    }

    /**
     * Sets the value of the displayTechnology property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayTechnology(String value) {
        this.displayTechnology = value;
    }

    /**
     * Gets the value of the imageDiagonalSize property.
     * 
     * @return
     *     possible object is
     *     {@link LengthSevenDigitDimension }
     *     
     */
    public LengthSevenDigitDimension getImageDiagonalSize() {
        return imageDiagonalSize;
    }

    /**
     * Sets the value of the imageDiagonalSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthSevenDigitDimension }
     *     
     */
    public void setImageDiagonalSize(LengthSevenDigitDimension value) {
        this.imageDiagonalSize = value;
    }

    /**
     * Gets the value of the inputVideoCompatability property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputVideoCompatability property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputVideoCompatability().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getInputVideoCompatability() {
        if (inputVideoCompatability == null) {
            inputVideoCompatability = new ArrayList<String>();
        }
        return this.inputVideoCompatability;
    }

    /**
     * Gets the value of the inputVideoConnectors property.
     * 
     * @return
     *     possible object is
     *     {@link InputVideoConnectorsTypeValues }
     *     
     */
    public InputVideoConnectorsTypeValues getInputVideoConnectors() {
        return inputVideoConnectors;
    }

    /**
     * Sets the value of the inputVideoConnectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputVideoConnectorsTypeValues }
     *     
     */
    public void setInputVideoConnectors(InputVideoConnectorsTypeValues value) {
        this.inputVideoConnectors = value;
    }

    /**
     * Gets the value of the keystoneCorrection property.
     * 
     * @return
     *     possible object is
     *     {@link LengthSevenDigitDimension }
     *     
     */
    public LengthSevenDigitDimension getKeystoneCorrection() {
        return keystoneCorrection;
    }

    /**
     * Sets the value of the keystoneCorrection property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthSevenDigitDimension }
     *     
     */
    public void setKeystoneCorrection(LengthSevenDigitDimension value) {
        this.keystoneCorrection = value;
    }

    /**
     * Gets the value of the lampLife property.
     * 
     * @return
     *     possible object is
     *     {@link BurnTimeSixDigitDimension }
     *     
     */
    public BurnTimeSixDigitDimension getLampLife() {
        return lampLife;
    }

    /**
     * Sets the value of the lampLife property.
     * 
     * @param value
     *     allowed object is
     *     {@link BurnTimeSixDigitDimension }
     *     
     */
    public void setLampLife(BurnTimeSixDigitDimension value) {
        this.lampLife = value;
    }

    /**
     * Gets the value of the lampWattage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLampWattage() {
        return lampWattage;
    }

    /**
     * Sets the value of the lampWattage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLampWattage(BigInteger value) {
        this.lampWattage = value;
    }

    /**
     * Gets the value of the lens property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLens() {
        return lens;
    }

    /**
     * Sets the value of the lens property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLens(String value) {
        this.lens = value;
    }

    /**
     * Gets the value of the maximumHorizontalRefreshRate property.
     * 
     * @return
     *     possible object is
     *     {@link FrequencyFiveDigitIntegerDimension }
     *     
     */
    public FrequencyFiveDigitIntegerDimension getMaximumHorizontalRefreshRate() {
        return maximumHorizontalRefreshRate;
    }

    /**
     * Sets the value of the maximumHorizontalRefreshRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrequencyFiveDigitIntegerDimension }
     *     
     */
    public void setMaximumHorizontalRefreshRate(FrequencyFiveDigitIntegerDimension value) {
        this.maximumHorizontalRefreshRate = value;
    }

    /**
     * Gets the value of the maximumImageSize property.
     * 
     * @return
     *     possible object is
     *     {@link LengthSevenDigitDimension }
     *     
     */
    public LengthSevenDigitDimension getMaximumImageSize() {
        return maximumImageSize;
    }

    /**
     * Sets the value of the maximumImageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthSevenDigitDimension }
     *     
     */
    public void setMaximumImageSize(LengthSevenDigitDimension value) {
        this.maximumImageSize = value;
    }

    /**
     * Gets the value of the maximumThrowDistance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaximumThrowDistance() {
        return maximumThrowDistance;
    }

    /**
     * Sets the value of the maximumThrowDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaximumThrowDistance(BigDecimal value) {
        this.maximumThrowDistance = value;
    }

    /**
     * Gets the value of the maximumThrowRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximumThrowRatio() {
        return maximumThrowRatio;
    }

    /**
     * Sets the value of the maximumThrowRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximumThrowRatio(String value) {
        this.maximumThrowRatio = value;
    }

    /**
     * Gets the value of the maximumVerticalRefreshRate property.
     * 
     * @return
     *     possible object is
     *     {@link FrequencyFiveDigitIntegerDimension }
     *     
     */
    public FrequencyFiveDigitIntegerDimension getMaximumVerticalRefreshRate() {
        return maximumVerticalRefreshRate;
    }

    /**
     * Sets the value of the maximumVerticalRefreshRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrequencyFiveDigitIntegerDimension }
     *     
     */
    public void setMaximumVerticalRefreshRate(FrequencyFiveDigitIntegerDimension value) {
        this.maximumVerticalRefreshRate = value;
    }

    /**
     * Gets the value of the mediaInput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaInput() {
        return mediaInput;
    }

    /**
     * Sets the value of the mediaInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaInput(String value) {
        this.mediaInput = value;
    }

    /**
     * Gets the value of the minimumHorizontalRefreshRate property.
     * 
     * @return
     *     possible object is
     *     {@link FrequencyFiveDigitIntegerDimension }
     *     
     */
    public FrequencyFiveDigitIntegerDimension getMinimumHorizontalRefreshRate() {
        return minimumHorizontalRefreshRate;
    }

    /**
     * Sets the value of the minimumHorizontalRefreshRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrequencyFiveDigitIntegerDimension }
     *     
     */
    public void setMinimumHorizontalRefreshRate(FrequencyFiveDigitIntegerDimension value) {
        this.minimumHorizontalRefreshRate = value;
    }

    /**
     * Gets the value of the minimumImageSize property.
     * 
     * @return
     *     possible object is
     *     {@link LengthSevenDigitDimension }
     *     
     */
    public LengthSevenDigitDimension getMinimumImageSize() {
        return minimumImageSize;
    }

    /**
     * Sets the value of the minimumImageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthSevenDigitDimension }
     *     
     */
    public void setMinimumImageSize(LengthSevenDigitDimension value) {
        this.minimumImageSize = value;
    }

    /**
     * Gets the value of the minimumThrowDistance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinimumThrowDistance() {
        return minimumThrowDistance;
    }

    /**
     * Sets the value of the minimumThrowDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinimumThrowDistance(BigDecimal value) {
        this.minimumThrowDistance = value;
    }

    /**
     * Gets the value of the minimumThrowRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumThrowRatio() {
        return minimumThrowRatio;
    }

    /**
     * Sets the value of the minimumThrowRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumThrowRatio(String value) {
        this.minimumThrowRatio = value;
    }

    /**
     * Gets the value of the minimumVerticalRefreshRate property.
     * 
     * @return
     *     possible object is
     *     {@link FrequencyFiveDigitIntegerDimension }
     *     
     */
    public FrequencyFiveDigitIntegerDimension getMinimumVerticalRefreshRate() {
        return minimumVerticalRefreshRate;
    }

    /**
     * Sets the value of the minimumVerticalRefreshRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrequencyFiveDigitIntegerDimension }
     *     
     */
    public void setMinimumVerticalRefreshRate(FrequencyFiveDigitIntegerDimension value) {
        this.minimumVerticalRefreshRate = value;
    }

    /**
     * Gets the value of the modelNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelNumber() {
        return modelNumber;
    }

    /**
     * Sets the value of the modelNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelNumber(String value) {
        this.modelNumber = value;
    }

    /**
     * Gets the value of the projectorBrightness property.
     * 
     * @return
     *     possible object is
     *     {@link LuminanceFiveDigitDimension }
     *     
     */
    public LuminanceFiveDigitDimension getProjectorBrightness() {
        return projectorBrightness;
    }

    /**
     * Sets the value of the projectorBrightness property.
     * 
     * @param value
     *     allowed object is
     *     {@link LuminanceFiveDigitDimension }
     *     
     */
    public void setProjectorBrightness(LuminanceFiveDigitDimension value) {
        this.projectorBrightness = value;
    }

    /**
     * Gets the value of the remote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemote() {
        return remote;
    }

    /**
     * Sets the value of the remote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemote(String value) {
        this.remote = value;
    }

    /**
     * Gets the value of the screenResolution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScreenResolution() {
        return screenResolution;
    }

    /**
     * Sets the value of the screenResolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScreenResolution(String value) {
        this.screenResolution = value;
    }

    /**
     * Gets the value of the screenTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link VoltageFiveDigitIntegerDimension }
     *     
     */
    public VoltageFiveDigitIntegerDimension getScreenTrigger() {
        return screenTrigger;
    }

    /**
     * Sets the value of the screenTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link VoltageFiveDigitIntegerDimension }
     *     
     */
    public void setScreenTrigger(VoltageFiveDigitIntegerDimension value) {
        this.screenTrigger = value;
    }

    /**
     * Gets the value of the threeDReady property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThreeDReady() {
        return threeDReady;
    }

    /**
     * Sets the value of the threeDReady property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThreeDReady(String value) {
        this.threeDReady = value;
    }

    /**
     * Gets the value of the wirelessStandard property.
     * 
     * @return
     *     possible object is
     *     {@link WirelessStandardTypeValues }
     *     
     */
    public WirelessStandardTypeValues getWirelessStandard() {
        return wirelessStandard;
    }

    /**
     * Sets the value of the wirelessStandard property.
     * 
     * @param value
     *     allowed object is
     *     {@link WirelessStandardTypeValues }
     *     
     */
    public void setWirelessStandard(WirelessStandardTypeValues value) {
        this.wirelessStandard = value;
    }

    /**
     * Gets the value of the zoom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoom() {
        return zoom;
    }

    /**
     * Sets the value of the zoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoom(String value) {
        this.zoom = value;
    }

    /**
     * Gets the value of the zoomRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoomRatio() {
        return zoomRatio;
    }

    /**
     * Sets the value of the zoomRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoomRatio(String value) {
        this.zoomRatio = value;
    }

    /**
     * Gets the value of the numberOfDVIPorts property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfDVIPorts() {
        return numberOfDVIPorts;
    }

    /**
     * Sets the value of the numberOfDVIPorts property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfDVIPorts(BigInteger value) {
        this.numberOfDVIPorts = value;
    }

    /**
     * Gets the value of the efficiency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEfficiency() {
        return efficiency;
    }

    /**
     * Sets the value of the efficiency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEfficiency(String value) {
        this.efficiency = value;
    }

    /**
     * Gets the value of the voltage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVoltage() {
        return voltage;
    }

    /**
     * Sets the value of the voltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVoltage(BigInteger value) {
        this.voltage = value;
    }

}
