//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.10 at 11:40:51 PM CST 
//


package com.kindminds.drs.mws.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VolumeRateUnitOfMeasure.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VolumeRateUnitOfMeasure"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="milliliters per second"/&gt;
 *     &lt;enumeration value="centiliters per second"/&gt;
 *     &lt;enumeration value="liters per second"/&gt;
 *     &lt;enumeration value="milliliters per minute"/&gt;
 *     &lt;enumeration value="liters per minute"/&gt;
 *     &lt;enumeration value="microliters per second"/&gt;
 *     &lt;enumeration value="nanoliters per second"/&gt;
 *     &lt;enumeration value="picoliters per second"/&gt;
 *     &lt;enumeration value="microliters per minute"/&gt;
 *     &lt;enumeration value="nanoliters per minute"/&gt;
 *     &lt;enumeration value="picoliters per minute"/&gt;
 *     &lt;enumeration value="gallons_per_day"/&gt;
 *     &lt;enumeration value="liters_per_day"/&gt;
 *     &lt;enumeration value="liters"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "VolumeRateUnitOfMeasure")
@XmlEnum
public enum VolumeRateUnitOfMeasure {

    @XmlEnumValue("milliliters per second")
    MILLILITERS___PER___SECOND("milliliters per second"),
    @XmlEnumValue("centiliters per second")
    CENTILITERS___PER___SECOND("centiliters per second"),
    @XmlEnumValue("liters per second")
    LITERS___PER___SECOND("liters per second"),
    @XmlEnumValue("milliliters per minute")
    MILLILITERS___PER___MINUTE("milliliters per minute"),
    @XmlEnumValue("liters per minute")
    LITERS___PER___MINUTE("liters per minute"),
    @XmlEnumValue("microliters per second")
    MICROLITERS___PER___SECOND("microliters per second"),
    @XmlEnumValue("nanoliters per second")
    NANOLITERS___PER___SECOND("nanoliters per second"),
    @XmlEnumValue("picoliters per second")
    PICOLITERS___PER___SECOND("picoliters per second"),
    @XmlEnumValue("microliters per minute")
    MICROLITERS___PER___MINUTE("microliters per minute"),
    @XmlEnumValue("nanoliters per minute")
    NANOLITERS___PER___MINUTE("nanoliters per minute"),
    @XmlEnumValue("picoliters per minute")
    PICOLITERS___PER___MINUTE("picoliters per minute"),
    @XmlEnumValue("gallons_per_day")
    GALLONS___PER___DAY("gallons_per_day"),
    @XmlEnumValue("liters_per_day")
    LITERS___PER___DAY("liters_per_day"),
    @XmlEnumValue("liters")
    LITERS("liters");
    private final String value;

    VolumeRateUnitOfMeasure(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VolumeRateUnitOfMeasure fromValue(String v) {
        for (VolumeRateUnitOfMeasure c: VolumeRateUnitOfMeasure.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
